//! Routes an opcode to the `exec_ops_group_NN` slice of `exec_one_dispatch` that runs it.
//!
//! Generated by `scripts/gen-exec-route.py` from the group functions in
//! `vm_exec_dispatch.rs`; `make check-exec-route` fails when this file is stale.

use super::*;

impl Interpreter {
    // Cost: O(1), a jump on the opcode discriminant.
    #[inline(always)]
    pub(super) fn route_op(
        &mut self,
        code: &CompiledCode,
        ip: &mut usize,
        compiled_fns: &CompiledFns,
    ) -> Result<(), RuntimeError> {
        match &code.ops[*ip] {
            OpCode::CallTrir { .. }
            | OpCode::GetGlobal(..)
            | OpCode::GetUpvalue { .. }
            | OpCode::LoadConst(..)
            | OpCode::LoadFalse
            | OpCode::LoadNil
            | OpCode::LoadRegexClosure { .. }
            | OpCode::LoadTrue
            | OpCode::PatchRegexAdverbContinue
            | OpCode::PatchRegexAdverbPos => self.exec_ops_group_00(code, ip, compiled_fns),
            OpCode::GetArrayVar(..) | OpCode::GetHashVar(..) | OpCode::GetSelfOrNoSelf(..) => {
                self.exec_ops_group_01(code, ip, compiled_fns)
            }
            OpCode::CheckDynamicVarDeclared(..)
            | OpCode::GetBareWord(..)
            | OpCode::GetBareWordOverScalar(..)
            | OpCode::GetCallTempRaw(..)
            | OpCode::GetExportTermOrJump { .. }
            | OpCode::GetLexicalStash { .. }
            | OpCode::GetOurVar(..)
            | OpCode::GetPseudoStash(..)
            | OpCode::GetPseudoStashKeyed(..)
            | OpCode::GetShadowableTerm { .. }
            | OpCode::PushLastRegisteredClass
            | OpCode::PushLastRegisteredRole
            | OpCode::RoleGroupToCandidate
            | OpCode::SetCallTemp(..)
            | OpCode::SetGlobal(..)
            | OpCode::SetGlobalRaw(..) => self.exec_ops_group_02(code, ip, compiled_fns),
            OpCode::Add
            | OpCode::BoolBitNeg
            | OpCode::DeSlip
            | OpCode::Decont
            | OpCode::DecontListElems
            | OpCode::DeitemizeForBind
            | OpCode::DeitemizeZen
            | OpCode::DerefContainer
            | OpCode::Div
            | OpCode::EnterPointyTopic
            | OpCode::ExitPointyTopic
            | OpCode::GetGivenPointyTopic
            | OpCode::IntBitNeg
            | OpCode::Itemize
            | OpCode::ItemizeVar(..)
            | OpCode::LoadEnterResult
            | OpCode::MakeSlip
            | OpCode::Mod
            | OpCode::Mul
            | OpCode::NativeIntArithmetic { .. }
            | OpCode::Negate
            | OpCode::NormalizeReturnSlip
            | OpCode::Pow
            | OpCode::PushEnterResult
            | OpCode::RestoreTopic
            | OpCode::SaveTopic
            | OpCode::SetTopic
            | OpCode::SetVarType { .. }
            | OpCode::SetVarTypeHoisted { .. }
            | OpCode::SetVarTypeScoped { .. }
            | OpCode::StrBitNeg
            | OpCode::Sub => self.exec_ops_group_03(code, ip, compiled_fns),
            OpCode::ApproxEq
            | OpCode::AttrContainerRef(..)
            | OpCode::BoolCoerce
            | OpCode::CaptureRwArgCell
            | OpCode::CaptureVarCell
            | OpCode::Concat
            | OpCode::ConsumeReifiedSeq
            | OpCode::ContainerEq(..)
            | OpCode::ContainerEqDeconted { .. }
            | OpCode::ContainerEqIndexed { .. }
            | OpCode::ContainerEqNamed { .. }
            | OpCode::FlattenSlurpy
            | OpCode::MarkAccessorRefContext
            | OpCode::MarkArrayShareSource(..)
            | OpCode::MarkBindContext
            | OpCode::MarkConstantContext
            | OpCode::MarkExplicitInitializerContext
            | OpCode::MarkLvalueInvocantRefContext(..)
            | OpCode::MarkParamRawBindContext
            | OpCode::MarkReadonlyRwTail
            | OpCode::MarkRebindContext
            | OpCode::MarkRwArgRefContext { .. }
            | OpCode::MarkRwArgRefContextCallee(..)
            | OpCode::MarkScalarBindContext
            | OpCode::MarkShapedDeclContext
            | OpCode::MarkVarDeclContext
            | OpCode::Not
            | OpCode::NotThreaded
            | OpCode::NumEq
            | OpCode::NumGe
            | OpCode::NumGt
            | OpCode::NumLe
            | OpCode::NumLt
            | OpCode::NumNe
            | OpCode::NumNeNative(..)
            | OpCode::ResolveAttrRwCandidate(..)
            | OpCode::StashVarDeclInit
            | OpCode::WrapScalar
            | OpCode::WrapTypedContainer(..)
            | OpCode::WrapVarRef { .. } => self.exec_ops_group_04(code, ip, compiled_fns),
            OpCode::After
            | OpCode::Before
            | OpCode::ButMixin
            | OpCode::ButMixinTupleElem { .. }
            | OpCode::Cmp
            | OpCode::Coll
            | OpCode::ContainerEqRaw
            | OpCode::ContainerEqRawAggregate
            | OpCode::ContainerizePair
            | OpCode::DivisibleBy
            | OpCode::Does
            | OpCode::DoesVar(..)
            | OpCode::Eqv
            | OpCode::FunctionCompose
            | OpCode::Gcd
            | OpCode::InfixMax
            | OpCode::InfixMin
            | OpCode::IntDiv
            | OpCode::IntMod
            | OpCode::Isa
            | OpCode::JumpIfNotRole(..)
            | OpCode::Lcm
            | OpCode::Leg
            | OpCode::ListRepeat
            | OpCode::MakeNamedArg
            | OpCode::MakePair
            | OpCode::MakeRoleInit
            | OpCode::NotDivisibleBy
            | OpCode::ScalarizeRegexMatchResult
            | OpCode::SmartMatchExpr { .. }
            | OpCode::Spaceship
            | OpCode::StrEq
            | OpCode::StrGe
            | OpCode::StrGt
            | OpCode::StrLe
            | OpCode::StrLt
            | OpCode::StrNe
            | OpCode::StrictEq
            | OpCode::StrictNe
            | OpCode::StringRepeat
            | OpCode::Unicmp => self.exec_ops_group_05(code, ip, compiled_fns),
            OpCode::BitAnd
            | OpCode::BitOr
            | OpCode::BitShiftLeft
            | OpCode::BitShiftRight
            | OpCode::BitXor
            | OpCode::BoolBitAnd
            | OpCode::BoolBitOr
            | OpCode::BoolBitXor
            | OpCode::CallDefined
            | OpCode::Goto
            | OpCode::Jump(..)
            | OpCode::JumpIfFalse(..)
            | OpCode::JumpIfNotNil(..)
            | OpCode::JumpIfTrue(..)
            | OpCode::JunctionAll
            | OpCode::JunctionAllN(..)
            | OpCode::JunctionAny
            | OpCode::JunctionAnyN(..)
            | OpCode::JunctionOne
            | OpCode::JunctionOneN(..)
            | OpCode::Label(..)
            | OpCode::Sequence { .. }
            | OpCode::SetAddition
            | OpCode::SetCont
            | OpCode::SetDiff
            | OpCode::SetElem
            | OpCode::SetIntersect
            | OpCode::SetMultiply
            | OpCode::SetStrictSubset
            | OpCode::SetStrictSuperset
            | OpCode::SetSubset
            | OpCode::SetSuperset
            | OpCode::SetSymDiff
            | OpCode::SetUnion
            | OpCode::StrBitAnd
            | OpCode::StrBitOr
            | OpCode::StrBitXor
            | OpCode::StrShiftLeft
            | OpCode::StrShiftRight
            | OpCode::XorXor => self.exec_ops_group_06(code, ip, compiled_fns),
            OpCode::CoerceToList
            | OpCode::Dup
            | OpCode::MarkPromiseSink
            | OpCode::Pop
            | OpCode::PopBlockFrame
            | OpCode::PushBlockFrame
            | OpCode::SinkPop(..)
            | OpCode::SinkPopAssign
            | OpCode::ThrowIfFailure
            | OpCode::WarnSuppressPop
            | OpCode::WarnSuppressPush => self.exec_ops_group_07(code, ip, compiled_fns),
            OpCode::ArrayPush { .. }
            | OpCode::CallFunc { .. }
            | OpCode::CallFuncNamed { .. }
            | OpCode::CallMethod { .. }
            | OpCode::CallMethodDynamic { .. }
            | OpCode::CallMethodDynamicMut { .. }
            | OpCode::CallMethodMut { .. }
            | OpCode::CallOnCodeVar { .. }
            | OpCode::CallOnValue { .. }
            | OpCode::MakeArray(..)
            | OpCode::MakeCapture(..)
            | OpCode::MakeHash(..)
            | OpCode::MakeHashFromPairs(..)
            | OpCode::MakeRange
            | OpCode::MakeRangeExcl
            | OpCode::MakeRangeExclBoth
            | OpCode::MakeRangeExclStart
            | OpCode::MakeRealArray(..)
            | OpCode::MakeRealArrayNoFlatten(..)
            | OpCode::Note(..)
            | OpCode::NqpAttrC(..)
            | OpCode::NqpCreateC(..)
            | OpCode::NqpOp { .. }
            | OpCode::Print(..)
            | OpCode::Put(..)
            | OpCode::Say(..) => self.exec_ops_group_08(code, ip, compiled_fns),
            OpCode::ClearElementSource
            | OpCode::DeleteIndexExpr
            | OpCode::DeleteIndexNamed(..)
            | OpCode::HyperSlice(..)
            | OpCode::Index { .. }
            | OpCode::IndexArgRef(..)
            | OpCode::IndexAutovivifyLazy { .. }
            | OpCode::IndexAutovivifyLazyTerminal { .. }
            | OpCode::IndexInvocantRef { .. }
            | OpCode::IndexVarRef { .. }
            | OpCode::Last(..)
            | OpCode::LastValue
            | OpCode::LoopControlLabelArg(..)
            | OpCode::MultiDimIndex { .. }
            | OpCode::MultiDimIndexAssign { .. }
            | OpCode::MultiDimIndexAssignGeneric { .. }
            | OpCode::MultiDimIndexAssignNested { .. }
            | OpCode::MultiDimIndexBindRef { .. }
            | OpCode::Next(..)
            | OpCode::NextValue
            | OpCode::Proceed
            | OpCode::ReactDone
            | OpCode::Redo(..)
            | OpCode::RwArgCalleeBindsContainer(..)
            | OpCode::StringConcat(..)
            | OpCode::Succeed
            | OpCode::SupplyBodyDone
            | OpCode::TagContainerRef(..)
            | OpCode::TagContainerRefReversed(..)
            | OpCode::TagElementSource { .. }
            | OpCode::TagElementSourcePath { .. } => self.exec_ops_group_09(code, ip, compiled_fns),
            OpCode::IndexAssignDeepNested { .. }
            | OpCode::IndexAssignExprNamed { .. }
            | OpCode::IndexAssignExprNested { .. }
            | OpCode::IndexAssignPseudoStashKeyed { .. }
            | OpCode::IndexAssignPseudoStashNamed { .. }
            | OpCode::IndexElemAutoviv { .. }
            | OpCode::MetaAssignIdentity(..)
            | OpCode::NumCoerce
            | OpCode::PostDecrement(..)
            | OpCode::PostDecrementIndex(..)
            | OpCode::PostIncrement(..)
            | OpCode::PostIncrementIndex(..)
            | OpCode::PreDecrement(..)
            | OpCode::PreDecrementIndex(..)
            | OpCode::PreIncrement(..)
            | OpCode::PreIncrementIndex(..)
            | OpCode::StrCoerce
            | OpCode::UndefineAggregate(..)
            | OpCode::UptoRange => self.exec_ops_group_10(code, ip, compiled_fns),
            OpCode::AssignExpr(..)
            | OpCode::AtomicCompoundVar { .. }
            | OpCode::CStyleLoop { .. }
            | OpCode::Default { .. }
            | OpCode::Die { .. }
            | OpCode::ForLoop(..)
            | OpCode::GetCaptureVar(..)
            | OpCode::GetCodeVar(..)
            | OpCode::GetCodeVarLocal { .. }
            | OpCode::Given { .. }
            | OpCode::RepeatLoop { .. }
            | OpCode::RestoreForParam
            | OpCode::RuntimeHasDecl(..)
            | OpCode::TopicDotAssign(..)
            | OpCode::TryCatch { .. }
            | OpCode::When { .. }
            | OpCode::WhileLoop { .. } => self.exec_ops_group_11(code, ip, compiled_fns),
            OpCode::BlockMagic
            | OpCode::ExistsEnvIndex(..)
            | OpCode::ExistsExpr
            | OpCode::ExistsIndexAdv(..)
            | OpCode::ExistsIndexNamedAdv { .. }
            | OpCode::Fail
            | OpCode::GetEnvIndex(..)
            | OpCode::NonDestructiveSubst { .. }
            | OpCode::PackageScope { .. }
            | OpCode::Reduction(..)
            | OpCode::RegisterPackage { .. }
            | OpCode::RegisterPackageMy { .. }
            | OpCode::Return
            | OpCode::ReturnFromNonRoutine(..)
            | OpCode::RoutineMagic
            | OpCode::SetCurrentPackage { .. }
            | OpCode::SetPackageKind { .. }
            | OpCode::Subst { .. }
            | OpCode::Take
            | OpCode::Transliterate { .. } => self.exec_ops_group_12(code, ip, compiled_fns),
            OpCode::CheckPhaserEnd
            | OpCode::CheckPhaserStart { .. }
            | OpCode::ClearPackageStub { .. }
            | OpCode::DeclareRequireStub { .. }
            | OpCode::FlipFlopExpr { .. }
            | OpCode::HyperFuncOp { .. }
            | OpCode::HyperMethodCall { .. }
            | OpCode::HyperMethodCallDynamic { .. }
            | OpCode::HyperOp { .. }
            | OpCode::IndirectCodeLookup(..)
            | OpCode::IndirectTypeLookup
            | OpCode::IndirectTypeLookupStore
            | OpCode::InfixFunc { .. }
            | OpCode::MetaOp { .. }
            | OpCode::MetaOpAssign { .. }
            | OpCode::MetaOpNary { .. }
            | OpCode::PhaserEnd { .. }
            | OpCode::RegisterPackageStub { .. }
            | OpCode::SetPragma(..)
            | OpCode::StateVarInit(..)
            | OpCode::SymbolicDeref { .. }
            | OpCode::SymbolicDerefStore(..)
            | OpCode::Trace(..)
            | OpCode::TypeCheck(..)
            | OpCode::TypeCheckBind(..) => self.exec_ops_group_13(code, ip, compiled_fns),
            OpCode::AugmentClass { .. }
            | OpCode::BeginOnceExpr { .. }
            | OpCode::BlockLocalScope { .. }
            | OpCode::BlockScope { .. }
            | OpCode::CaptureNestedMethodEnv(..)
            | OpCode::CheckPhaser { .. }
            | OpCode::DoBlockExpr { .. }
            | OpCode::DoGivenExpr { .. }
            | OpCode::Eager
            | OpCode::EndBeginPrologue
            | OpCode::ImportModule { .. }
            | OpCode::ImportScope { .. }
            | OpCode::IndexAssignGeneric { .. }
            | OpCode::LeaveGuard { .. }
            | OpCode::LoopExitGuard { .. }
            | OpCode::MakeAnonSub(..)
            | OpCode::MakeAnonSubParams(..)
            | OpCode::MakeBlockClosure(..)
            | OpCode::MakeGather(..)
            | OpCode::MakeLambda(..)
            | OpCode::NeedModule(..)
            | OpCode::NoModule(..)
            | OpCode::OnceExpr { .. }
            | OpCode::PreloadModule(..)
            | OpCode::RegisterDecl(..)
            | OpCode::RegisterEnum(..)
            | OpCode::ResetStateLocals { .. }
            | OpCode::RoutineScope { .. }
            | OpCode::StateVarInitGuard(..)
            | OpCode::SucceedBarrier { .. }
            | OpCode::ThrowUndeclaredRoutine(..)
            | OpCode::UseLibPath
            | OpCode::UseModule { .. } => self.exec_ops_group_14(code, ip, compiled_fns),
            OpCode::ApplyVarTrait { .. }
            | OpCode::AssignExprLocal(..)
            | OpCode::AssignReadOnly
            | OpCode::BindCallerVar { .. }
            | OpCode::BoxOuterRef { .. }
            | OpCode::CheckReadOnly(..)
            | OpCode::ConcatAssignLocal(..)
            | OpCode::DeclareOurScalar { .. }
            | OpCode::GetCallerOuterVar { .. }
            | OpCode::GetCallerVar { .. }
            | OpCode::GetCallersVar { .. }
            | OpCode::GetDynamicVar(..)
            | OpCode::GetLocal(..)
            | OpCode::GetLocalDeferred(..)
            | OpCode::GetLocalMetaAssign { .. }
            | OpCode::GetLocalRaw(..)
            | OpCode::GetOuterCapture { .. }
            | OpCode::GetOuterVar { .. }
            | OpCode::GetScalarContainer { .. }
            | OpCode::MarkSigillessBindSource(..)
            | OpCode::PublishExportStashVar { .. }
            | OpCode::ReactScope { .. }
            | OpCode::RegisterSubset { .. }
            | OpCode::RegisterVarExport { .. }
            | OpCode::SetCallerVar { .. }
            | OpCode::SetLocal(..)
            | OpCode::SetLocalDecl { .. }
            | OpCode::SetVarDynamic { .. }
            | OpCode::SigillessAggregateStore { .. }
            | OpCode::WheneverScope { .. } => self.exec_ops_group_15(code, ip, compiled_fns),
            OpCode::LetBlock { .. }
            | OpCode::LetSave { .. }
            | OpCode::LetSaveElem { .. }
            | OpCode::LetSaveElemVivified { .. }
            | OpCode::MarkSigillessBind(..)
            | OpCode::MarkVarReadonly(..) => self.exec_ops_group_16(code, ip, compiled_fns),
        }
    }
}
