mod attribute_core_traits;
mod attribute_identity;
mod builtin_method_wrap;
mod container_store;
pub(crate) mod core_infix_names;
pub(crate) mod deprecation;
pub(crate) mod did_you_mean;
mod dispatch;
pub(crate) use dispatch::Resolved;
mod dispatch_candidates;
pub(crate) mod dispatch_key;
mod dispatch_narrow;
mod dispatch_proto;
mod dispatch_proto_call;
mod dispatch_proto_candidates;
mod dispatch_proto_dispatchee;
mod dispatch_proto_rewrite;
pub(crate) mod dispatch_resolve;
mod end_phasers;
mod eval_check;
mod eval_decl_scans;
mod eval_import_scope;
mod eval_name_scans;
mod eval_routine_magicals;
mod eval_type_scans;
mod eval_var_scan;
mod exception_message;
pub(crate) mod fn_keys_index;
pub(crate) mod function_table;
mod function_table_family;
mod gc_roots;
mod gen_cache;
mod handle;
mod handle_io;
mod handle_open;
mod handle_read;
mod handle_read_chars;
mod handle_seq_reader;
pub(crate) mod hoist_visibility;
mod imported_trait_dispatcher;
pub(crate) mod incdec_rw_sub;
mod inline_package_subs;
mod io;
mod io_doc;
mod io_env;
mod io_handles;
mod io_pod;
pub(crate) mod io_pod_blocks;
mod io_pod_config;
mod io_pod_entries;
mod io_pod_format;
mod io_pod_heredoc;
mod io_pod_table;
mod io_spec_rel2abs;
mod io_sysinfo;
pub(crate) mod io_sysinfo_host;
mod io_sysinfo_kernel;
mod io_sysinfo_user;
pub(crate) mod io_sysinfo_vm_config;
pub(crate) mod iterator_map_grep_stream;
mod iterator_protocol;
mod list_element_stringify;
mod listop_functions;
pub(crate) mod locals;
mod lock_async_recursion;
mod lock_reentry;
pub(crate) mod loop_handler_depth;
mod lvalue_container_return;
mod lvalue_quanthash_store;
mod main_args;
mod main_usage;
mod main_usage_program;
pub(crate) mod mark_context;
mod metamodel;
mod metamodel_new_type;
mod metamodel_role_how;
mod method_dispatch_lazy;
mod method_object_bound;
