mod methods_introspect;
pub(crate) use methods_introspect::embedded_container_type_name;
mod methods_io_dispatch;
mod methods_list_view_default;
mod methods_match_dispatch;
mod methods_mixin_dispatch;
mod methods_mixin_what_cache;
mod methods_mut;
mod methods_mut_dispatch;
mod methods_mut_hash;
mod methods_mut_method_lvalue;
mod methods_mut_proxy;
mod methods_mut_rw_attr;
mod methods_mut_substr_buf;
mod methods_native_bypass;
mod methods_object;
mod methods_object_attr_constraints;
mod methods_object_role_submethods;
pub(crate) mod multi_dispatch_plan;
pub(crate) mod multi_dispatch_program;
mod object_hash_assign;
pub(crate) use methods_object_attr_constraints::AttrWhereScope;
mod code_do_attr;
pub(crate) mod find_method_intercept;
mod methods_dispatcher_raku;
