mod methods_object_default_ctor;
mod methods_object_dispatch_new;
mod methods_object_native_ctors_buf_num;
mod methods_object_native_ctors_io;
mod methods_object_native_ctors_misc;
mod methods_object_native_ctors_temporal;
mod methods_pick_roll;
mod methods_promise;
mod methods_promise_class;
mod methods_promise_scheduler;
mod methods_qualified;
mod methods_quanthash_ctor;
mod methods_raku_dispatch;
mod methods_regex_routine;
mod methods_seq_dispatch;
pub(crate) mod methods_signature;
mod methods_signature_candidates;
pub(crate) mod methods_signature_errors;
mod methods_signature_shaped;
mod methods_string;
mod methods_string_codec;
mod methods_string_encoding;
mod methods_string_index;
mod methods_string_search;
mod methods_string_subst_repl;
mod methods_string_substr;
pub(crate) mod methods_sub;
mod methods_sub_prec;
mod methods_sub_rw_proxy;
mod methods_subscript_protocol;
mod methods_supply_dispatch;
mod methods_temporal;
mod methods_trans;
mod methods_type_coerce;
mod methods_walk;
mod mixin_role_attrs;
