mod methods;
mod methods_adhoc_slurpy;
mod methods_aggregate_ctor;
mod methods_call_dispatch;
mod methods_call_helpers;
mod methods_classhow;
mod methods_classhow_attribute;
mod methods_classhow_attribute_table;
mod methods_classhow_builtin_methods;
mod methods_classhow_dispatch;
mod methods_classhow_arms_1;
mod methods_classhow_arms_2;
mod methods_classhow_arms_3;
mod methods_classhow_arms_4;
mod methods_classhow_arms_5;
mod methods_classhow_arms_6;
mod methods_classhow_grammar_tokens;
mod methods_classhow_lookup;
mod methods_classhow_method_obj;
mod methods_classhow_mro;
mod methods_classhow_parents;
mod methods_classhow_private_methods;
mod methods_collection;
pub(crate) mod methods_collection_ops;
mod methods_definitehow;
mod methods_dispatch_match;
mod methods_dispatch_match2;
mod methods_dispatch_match3;
mod methods_dispatch_new;
mod methods_distribution;
mod methods_distribution_cur_compunit;
mod methods_distribution_cur_files;
mod methods_distribution_cur_inst;
mod methods_distribution_cur_resolve;
mod methods_distribution_helpers;
mod methods_enum_dispatch;
mod methods_enum_roles;
mod methods_enumhow;
mod methods_format;
mod methods_grammar;
mod methods_grammar_action_env;
mod methods_grammar_deferred_repeats;
mod methods_grammar_method_start;
mod methods_grammar_replay_spans;
mod methods_grammar_wrapped_start;
pub(crate) mod methods_instance_ops;
pub(crate) mod module_merge;
mod module_preload_failure;
mod pragma_monkey_eval;
mod pragma_strict;
pub(crate) mod process_routines;
pub(crate) mod process_stash;
mod str_subclass_stringy;
mod subscript_adverb_assoc;
pub(crate) mod thread_usage;
pub(crate) use str_subclass_stringy::{str_mixin_payload, str_subclass_payload};
