//! MoarVM's Unicode property and property-value codes, as `nqp::unipropcode`
//! and `nqp::unipvalcode` answer them (#11495).
//!
//! **Every number here was read off rakudo, not invented**: nqp code compares
//! `getuniprop_int` results and `unipvalcode` handles as plain integers, so a
//! self-consistent numbering of mutsu's own would run such code silently wrong.
//! Regenerate a table by asking rakudo for each name:
//!
//! ```text
//! raku -e 'use nqp; say nqp::unipropcode("Alphabetic")'                # 33
//! raku -e 'use nqp; say nqp::getuniprop_str($cp, nqp::unipropcode("Script"))'
//! ```
//!
//! (the Script table walks every codepoint 0..0x10FFFF and records each
//! `getuniprop_int` / `getuniprop_str` pair; the short aliases come from probing
//! every four-letter `Xxxx` spelling with `unipvalcode`).

/// MoarVM's General_Category property value codes, in its enumeration order.
/// The index into this table *is* the value `nqp::getuniprop_int` returns;
/// the second field is the long value name `unipvalcode` also accepts.
pub(super) const GENERAL_CATEGORY_VALUES: [(&str, &str); 30] = [
    ("Cn", "Unassigned"),
    ("Lu", "Uppercase_Letter"),
    ("Ll", "Lowercase_Letter"),
    ("Lt", "Titlecase_Letter"),
    ("Lm", "Modifier_Letter"),
    ("Lo", "Other_Letter"),
    ("Mn", "Nonspacing_Mark"),
    ("Me", "Enclosing_Mark"),
    ("Mc", "Spacing_Mark"),
    ("Nd", "Decimal_Number"),
    ("Nl", "Letter_Number"),
    ("No", "Other_Number"),
    ("Zs", "Space_Separator"),
    ("Zl", "Line_Separator"),
    ("Zp", "Paragraph_Separator"),
    ("Cc", "Control"),
    ("Cf", "Format"),
    ("Co", "Private_Use"),
    ("Cs", "Surrogate"),
    ("Pd", "Dash_Punctuation"),
    ("Ps", "Open_Punctuation"),
    ("Pe", "Close_Punctuation"),
    ("Pc", "Connector_Punctuation"),
    ("Po", "Other_Punctuation"),
    ("Sm", "Math_Symbol"),
    ("Sc", "Currency_Symbol"),
    ("Sk", "Modifier_Symbol"),
    ("So", "Other_Symbol"),
    ("Pi", "Initial_Punctuation"),
    ("Pf", "Final_Punctuation"),
];

/// The two further General_Category value aliases MoarVM resolves (the
/// one-letter groups `L`, `P`, ... are NOT values to it: they answer 0).
pub(super) const GENERAL_CATEGORY_ALIASES: [(&str, i64); 2] = [("cntrl", 15), ("digit", 9)];

/// MoarVM's Script property values: the index is the value code, then the
/// long name (what `getuniprop_str` answers) and its short aliases.
pub(super) static SCRIPT_VALUES: [(&str, &[&str]); 175] = [
    ("Unknown", &[]),
    ("Common", &["Zyyy"]),
    ("Latin", &["Latn"]),
    ("Greek", &["Grek"]),
    ("Cyrillic", &["Cyrl"]),
    ("Armenian", &["Armn"]),
    ("Hebrew", &["Hebr"]),
    ("Arabic", &["Arab"]),
    ("Syriac", &["Syrc"]),
    ("Thaana", &["Thaa"]),
    ("Devanagari", &["Deva"]),
    ("Bengali", &["Beng"]),
    ("Gurmukhi", &["Guru"]),
    ("Gujarati", &["Gujr"]),
    ("Oriya", &["Orya"]),
    ("Tamil", &["Taml"]),
    ("Telugu", &["Telu"]),
    ("Kannada", &["Knda"]),
    ("Malayalam", &["Mlym"]),
    ("Sinhala", &["Sinh"]),
    ("Thai", &[]),
    ("Lao", &["Laoo"]),
    ("Tibetan", &["Tibt"]),
    ("Myanmar", &["Mymr"]),
    ("Georgian", &["Geor"]),
    ("Hangul", &["Hang"]),
    ("Ethiopic", &["Ethi"]),
    ("Cherokee", &["Cher"]),
    ("Canadian_Aboriginal", &["Cans"]),
    ("Ogham", &["Ogam"]),
    ("Runic", &["Runr"]),
    ("Khmer", &["Khmr"]),
    ("Mongolian", &["Mong"]),
    ("Hiragana", &["Hira"]),
    ("Katakana", &["Kana"]),
    ("Bopomofo", &["Bopo"]),
    ("Han", &["Hani"]),
    ("Yi", &["Yiii"]),
    ("Old_Italic", &["Ital"]),
    ("Gothic", &["Goth"]),
    ("Deseret", &["Dsrt"]),
    ("Inherited", &["Qaai", "Zinh"]),
    ("Tagalog", &["Tglg"]),
    ("Hanunoo", &["Hano"]),
    ("Buhid", &["Buhd"]),
    ("Tagbanwa", &["Tagb"]),
    ("Limbu", &["Limb"]),
    ("Tai_Le", &["Tale"]),
    ("Linear_B", &["Linb"]),
    ("Ugaritic", &["Ugar"]),
    ("Shavian", &["Shaw"]),
    ("Osmanya", &["Osma"]),
    ("Cypriot", &["Cprt"]),
    ("Braille", &["Brai"]),
    ("Buginese", &["Bugi"]),
    ("Coptic", &["Copt", "Qaac"]),
    ("New_Tai_Lue", &["Talu"]),
    ("Glagolitic", &["Glag"]),
    ("Tifinagh", &["Tfng"]),
    ("Syloti_Nagri", &["Sylo"]),
    ("Old_Persian", &["Xpeo"]),
    ("Kharoshthi", &["Khar"]),
    ("Balinese", &["Bali"]),
    ("Cuneiform", &["Xsux"]),
    ("Phoenician", &["Phnx"]),
    ("Phags_Pa", &["Phag"]),
    ("Nko", &["Nkoo"]),
    ("Sundanese", &["Sund"]),
    ("Lepcha", &["Lepc"]),
    ("Ol_Chiki", &["Olck"]),
    ("Vai", &["Vaii"]),
    ("Saurashtra", &["Saur"]),
    ("Kayah_Li", &["Kali"]),
    ("Rejang", &["Rjng"]),
    ("Lycian", &["Lyci"]),
    ("Carian", &["Cari"]),
    ("Lydian", &["Lydi"]),
    ("Cham", &[]),
    ("Tai_Tham", &["Lana"]),
    ("Tai_Viet", &["Tavt"]),
    ("Avestan", &["Avst"]),
    ("Egyptian_Hieroglyphs", &["Egyp"]),
    ("Samaritan", &["Samr"]),
    ("Lisu", &[]),
    ("Bamum", &["Bamu"]),
    ("Javanese", &["Java"]),
    ("Meetei_Mayek", &["Mtei"]),
    ("Imperial_Aramaic", &["Armi"]),
    ("Old_South_Arabian", &["Sarb"]),
    ("Inscriptional_Parthian", &["Prti"]),
    ("Inscriptional_Pahlavi", &["Phli"]),
    ("Old_Turkic", &["Orkh"]),
    ("Kaithi", &["Kthi"]),
    ("Batak", &["Batk"]),
    ("Brahmi", &["Brah"]),
    ("Mandaic", &["Mand"]),
    ("Chakma", &["Cakm"]),
    ("Meroitic_Cursive", &["Merc"]),
    ("Meroitic_Hieroglyphs", &["Mero"]),
    ("Miao", &["Plrd"]),
    ("Sharada", &["Shrd"]),
    ("Sora_Sompeng", &["Sora"]),
    ("Takri", &["Takr"]),
    ("Caucasian_Albanian", &["Aghb"]),
    ("Bassa_Vah", &["Bass"]),
    ("Duployan", &["Dupl"]),
    ("Elbasan", &["Elba"]),
    ("Grantha", &["Gran"]),
    ("Pahawh_Hmong", &["Hmng"]),
    ("Khojki", &["Khoj"]),
    ("Linear_A", &["Lina"]),
    ("Mahajani", &["Mahj"]),
    ("Manichaean", &["Mani"]),
    ("Mende_Kikakui", &["Mend"]),
    ("Modi", &[]),
    ("Mro", &["Mroo"]),
    ("Old_North_Arabian", &["Narb"]),
    ("Nabataean", &["Nbat"]),
    ("Palmyrene", &["Palm"]),
    ("Pau_Cin_Hau", &["Pauc"]),
    ("Old_Permic", &["Perm"]),
    ("Psalter_Pahlavi", &["Phlp"]),
    ("Siddham", &["Sidd"]),
    ("Khudawadi", &["Sind"]),
    ("Tirhuta", &["Tirh"]),
    ("Warang_Citi", &["Wara"]),
    ("Ahom", &[]),
    ("Anatolian_Hieroglyphs", &["Hluw"]),
    ("Hatran", &["Hatr"]),
    ("Multani", &["Mult"]),
    ("Old_Hungarian", &["Hung"]),
    ("SignWriting", &["Sgnw"]),
    ("Adlam", &["Adlm"]),
    ("Bhaiksuki", &["Bhks"]),
    ("Marchen", &["Marc"]),
    ("Newa", &[]),
    ("Osage", &["Osge"]),
    ("Tangut", &["Tang"]),
    ("Masaram_Gondi", &["Gonm"]),
    ("Nushu", &["Nshu"]),
    ("Soyombo", &["Soyo"]),
    ("Zanabazar_Square", &["Zanb"]),
    ("Dogra", &["Dogr"]),
    ("Gunjala_Gondi", &["Gong"]),
    ("Makasar", &["Maka"]),
    ("Medefaidrin", &["Medf"]),
    ("Hanifi_Rohingya", &["Rohg"]),
    ("Sogdian", &["Sogd"]),
    ("Old_Sogdian", &["Sogo"]),
    ("Elymaic", &["Elym"]),
    ("Nandinagari", &["Nand"]),
    ("Nyiakeng_Puachue_Hmong", &["Hmnp"]),
    ("Wancho", &["Wcho"]),
    ("Chorasmian", &["Chrs"]),
    ("Dives_Akuru", &["Diak"]),
    ("Khitan_Small_Script", &["Kits"]),
    ("Yezidi", &["Yezi"]),
    ("Cypro_Minoan", &["Cpmn"]),
    ("Old_Uyghur", &["Ougr"]),
    ("Tangsa", &["Tnsa"]),
    ("Toto", &[]),
    ("Vithkuqi", &["Vith"]),
    ("Kawi", &[]),
    ("Nag_Mundari", &["Nagm"]),
    ("Garay", &["Gara"]),
    ("Gurung_Khema", &["Gukh"]),
    ("Kirat_Rai", &["Krai"]),
    ("Ol_Onal", &["Onao"]),
    ("Sunuwar", &["Sunu"]),
    ("Todhri", &["Todr"]),
    ("Tulu_Tigalari", &["Tutg"]),
    ("Sidetic", &["Sidt"]),
    ("Tai_Yo", &["Tayo"]),
    ("Tolong_Siki", &["Tols"]),
    ("Beria_Erfe", &["Berf"]),
];

/// The binary properties mutsu can answer (`builtins::uniprop`'s
/// `try_binary_property` set), with MoarVM's property code for each. The
/// first name is the canonical one, the rest its aliases. Sorted by code.
pub(super) static BINARY_PROPERTIES: [(i64, &[&str]); 60] = [
    (26, &["ASCII_Hex_Digit", "AHex"]),
    (33, &["Alphabetic", "Alpha"]),
    (36, &["Bidi_Control", "Bidi_C"]),
    (37, &["Bidi_Mirrored", "Bidi_M"]),
    (40, &["Case_Ignorable", "CI"]),
    (41, &["Cased"]),
    (42, &["Changes_When_Casefolded", "CWCF"]),
    (43, &["Changes_When_Casemapped", "CWCM"]),
    (44, &["Changes_When_Lowercased", "CWL"]),
    (45, &["Changes_When_NFKC_Casefolded", "CWKCF"]),
    (46, &["Changes_When_Titlecased", "CWT"]),
    (47, &["Changes_When_Uppercased", "CWU"]),
    (48, &["Dash"]),
    (49, &["Default_Ignorable_Code_Point", "DI"]),
    (50, &["Deprecated", "Dep"]),
    (51, &["Diacritic", "Dia"]),
    (52, &["Emoji"]),
    (53, &["Emoji_Component"]),
    (54, &["Emoji_Modifier"]),
    (55, &["Emoji_Modifier_Base"]),
    (56, &["Emoji_Presentation"]),
    (57, &["Extended_Pictographic"]),
    (58, &["Extender", "Ext"]),
    (59, &["Full_Composition_Exclusion", "Comp_Ex"]),
    (60, &["Grapheme_Base", "Gr_Base"]),
    (61, &["Grapheme_Extend", "Gr_Ext"]),
    (62, &["Grapheme_Link", "Gr_Link"]),
    (63, &["Hex_Digit", "Hex"]),
    (64, &["Hyphen"]),
    (65, &["IDS_Binary_Operator", "IDSB"]),
    (66, &["IDS_Trinary_Operator", "IDST"]),
    (70, &["ID_Continue", "IDC"]),
    (71, &["ID_Start", "IDS"]),
    (72, &["Ideographic", "Ideo"]),
    (73, &["Join_Control", "Join_C"]),
    (77, &["Lowercase", "Lower"]),
    (80, &["Math"]),
    (87, &["Noncharacter_Code_Point", "NChar"]),
    (88, &["Other_Alphabetic", "OAlpha"]),
    (90, &["Other_Default_Ignorable_Code_Point", "ODI"]),
    (91, &["Other_Grapheme_Extend", "OGr_Ext"]),
    (92, &["Other_ID_Continue", "OIDC"]),
    (93, &["Other_ID_Start", "OIDS"]),
    (94, &["Other_Lowercase", "OLower"]),
    (95, &["Other_Math", "OMath"]),
    (96, &["Other_Uppercase", "OUpper"]),
    (98, &["Pattern_Syntax"]),
    (99, &["Pattern_White_Space"]),
    (101, &["Quotation_Mark", "QMark"]),
    (102, &["Radical"]),
    (103, &["Regional_Indicator"]),
    (105, &["Sentence_Terminal", "STerm"]),
    (106, &["Soft_Dotted", "SD"]),
    (107, &["Terminal_Punctuation", "Term"]),
    (108, &["Unified_Ideograph", "UIdeo"]),
    (109, &["Uppercase", "Upper"]),
    (110, &["Variation_Selector", "VS"]),
    (111, &["White_Space", "WSpace", "space"]),
    (112, &["XID_Continue", "XIDC"]),
    (113, &["XID_Start", "XIDS"]),
];
