//! Generated data table for [`super::native_method_row`] -- see that module's
//! doc comment for what this is and how it was produced. Kept in its own file
//! so the ~340 literal rows do not push the logic/tests in
//! `native_method_row.rs` past the repo's 500-line-per-file guideline.

/// `(owner, name, arity_bits, flag_bits)`.
#[rustfmt::skip]
pub(super) const RAW_ROWS: &[(&str, &str, u8, u8)] = &[
    ("Str", "chars", 1, 1),
    ("Str", "codes", 1, 1),
    ("Str", "comb", 7, 1),
    ("Str", "chomp", 1, 1),
    ("Str", "chop", 3, 1),
    ("Str", "contains", 2, 1),
    ("Str", "ends-with", 2, 0),
    ("Str", "fc", 1, 1),
    ("Str", "flip", 1, 1),
    ("Str", "index", 2, 1),
    ("Str", "indices", 8, 4),
    ("Str", "lc", 1, 1),
    ("Str", "lines", 3, 1),
    ("Str", "match", 8, 4),
    ("Str", "ords", 1, 1),
    ("Str", "pred", 1, 1),
    ("Str", "rindex", 2, 1),
    ("Str", "samecase", 2, 1),
    ("Str", "samemark", 2, 1),
    ("Str", "split", 6, 1),
    ("Str", "starts-with", 2, 0),
    ("Str", "substr", 6, 1),
    ("Str", "succ", 1, 1),
    ("Str", "tc", 1, 1),
    ("Str", "trim", 1, 1),
    ("Str", "trim-leading", 1, 1),
    ("Str", "trim-trailing", 1, 1),
    ("Str", "uc", 1, 1),
    ("Str", "words", 3, 1),
    ("Str", "wordcase", 1, 1),
    ("Str", "NFC", 1, 1),
    ("Str", "NFD", 1, 1),
    ("Str", "NFKC", 1, 1),
    ("Str", "NFKD", 1, 1),
    ("Str", "encode", 1, 1),
    ("Str", "uniparse", 1, 1),
    ("Str", "unimatch", 6, 1),
    ("Str", "uniprops", 3, 1),
    ("Str", "parse-names", 1, 1),
    ("Str", "parse-base", 2, 1),
    ("Str", "subst", 8, 4),
    ("Str", "subst-mutate", 8, 2),
    ("Str", "substr-rw", 8, 4),
    ("Str", "substr-eq", 4, 0),
    ("Str", "trans", 8, 4),
    ("Str", "IO", 8, 4),
    ("Str", "Numeric", 1, 0),
    ("Str", "Int", 1, 1),
    ("Str", "Num", 1, 0),
    ("Str", "Rat", 3, 1),
    ("Str", "Bool", 1, 1),
    ("Str", "Str", 3, 1),
    ("Str", "gist", 1, 1),
    ("Str", "raku", 1, 1),
    ("Str", "elems", 1, 1),
    ("Str", "fmt", 7, 1),
    ("Int", "abs", 1, 1),
    ("Int", "ceiling", 1, 1),
    ("Int", "floor", 1, 1),
    ("Int", "round", 3, 1),
    ("Int", "sign", 1, 1),
    ("Int", "sqrt", 1, 1),
    ("Int", "log", 3, 1),
    ("Int", "log10", 1, 1),
    ("Int", "exp", 3, 1),
    ("Int", "roots", 2, 1),
    ("Int", "is-prime", 1, 1),
    ("Int", "chr", 1, 1),
    ("Int", "base", 6, 1),
    ("Int", "polymod", 8, 5),
    ("Int", "expmod", 4, 1),
    ("Int", "pred", 1, 1),
    ("Int", "succ", 1, 1),
    ("Int", "Numeric", 1, 1),
    ("Int", "Int", 1, 1),
    ("Int", "Num", 1, 0),
    ("Int", "Rat", 3, 1),
    ("Int", "Bool", 1, 1),
    ("Int", "Str", 3, 1),
    ("Int", "gist", 1, 1),
    ("Int", "raku", 1, 1),
    ("Num", "abs", 1, 1),
    ("Num", "ceiling", 1, 1),
    ("Num", "floor", 1, 1),
    ("Num", "round", 3, 1),
    ("Num", "sign", 1, 1),
    ("Num", "sqrt", 1, 1),
    ("Num", "log", 3, 1),
    ("Num", "log10", 1, 1),
    ("Num", "exp", 3, 1),
    ("Num", "roots", 2, 1),
    ("Num", "is-prime", 1, 1),
    ("Num", "chr", 1, 1),
    ("Num", "base", 6, 1),
    ("Num", "polymod", 8, 5),
    ("Num", "expmod", 4, 1),
    ("Num", "pred", 1, 1),
    ("Num", "succ", 1, 1),
    ("Num", "Numeric", 1, 1),
    ("Num", "Int", 1, 1),
    ("Num", "Num", 1, 1),
    ("Num", "Rat", 3, 1),
    ("Num", "Bool", 1, 1),
    ("Num", "Str", 3, 1),
    ("Num", "gist", 1, 1),
    ("Num", "raku", 1, 1),
    ("Rat", "abs", 1, 1),
    ("Rat", "ceiling", 1, 1),
    ("Rat", "floor", 1, 1),
    ("Rat", "round", 3, 1),
    ("Rat", "sign", 1, 1),
    ("Rat", "sqrt", 1, 1),
    ("Rat", "log", 3, 1),
    ("Rat", "log10", 1, 1),
    ("Rat", "exp", 3, 1),
    ("Rat", "roots", 2, 1),
    ("Rat", "is-prime", 1, 1),
    ("Rat", "chr", 1, 1),
    ("Rat", "base", 6, 1),
    ("Rat", "polymod", 8, 5),
    ("Rat", "expmod", 4, 1),
    ("Rat", "pred", 1, 1),
    ("Rat", "succ", 1, 1),
    ("Rat", "Numeric", 1, 1),
    ("Rat", "Int", 1, 1),
    ("Rat", "Num", 1, 0),
    ("Rat", "Rat", 3, 1),
    ("Rat", "Bool", 1, 1),
    ("Rat", "Str", 3, 1),
    ("Rat", "gist", 1, 1),
    ("Rat", "raku", 1, 1),
    ("Complex", "abs", 1, 1),
    ("Complex", "ceiling", 1, 1),
    ("Complex", "floor", 1, 1),
    ("Complex", "round", 3, 1),
    ("Complex", "sign", 1, 1),
    ("Complex", "sqrt", 1, 1),
    ("Complex", "log", 3, 1),
    ("Complex", "log10", 1, 1),
    ("Complex", "exp", 3, 1),
    ("Complex", "roots", 2, 1),
    ("Complex", "is-prime", 1, 1),
    ("Complex", "chr", 1, 1),
    ("Complex", "base", 4, 1),
    ("Complex", "polymod", 8, 5),
    ("Complex", "expmod", 4, 1),
    ("Complex", "pred", 1, 1),
    ("Complex", "succ", 1, 1),
    ("Complex", "Numeric", 1, 1),
    ("Complex", "Int", 1, 1),
    ("Complex", "Num", 8, 4),
    ("Complex", "Rat", 3, 1),
    ("Complex", "Bool", 1, 1),
    ("Complex", "Str", 3, 1),
    ("Complex", "gist", 1, 1),
    ("Complex", "raku", 1, 1),
    ("List", "elems", 1, 1),
    ("List", "end", 1, 1),
    ("List", "keys", 1, 0),
    ("List", "values", 1, 0),
    ("List", "kv", 1, 0),
    ("List", "pairs", 1, 0),
    ("List", "antipairs", 1, 0),
    ("List", "join", 3, 1),
    ("List", "map", 8, 2),
    ("List", "grep", 8, 2),
    ("List", "first", 1, 0),
    ("List", "sort", 1, 0),
    ("List", "reverse", 1, 0),
    ("List", "rotate", 8, 2),
    ("List", "unique", 1, 1),
    ("List", "repeated", 1, 1),
    ("List", "squish", 1, 0),
    ("List", "flat", 7, 1),
    ("List", "eager", 8, 4),
    ("List", "lazy", 1, 1),
    ("List", "head", 3, 1),
    ("List", "tail", 3, 1),
    ("List", "skip", 8, 4),
    ("List", "push", 8, 2),
    ("List", "pop", 8, 2),
    ("List", "shift", 8, 2),
    ("List", "unshift", 8, 2),
    ("List", "splice", 8, 2),
    ("List", "append", 8, 2),
    ("List", "prepend", 8, 2),
    ("List", "classify", 8, 2),
    ("List", "categorize", 8, 2),
    ("List", "min", 1, 0),
    ("List", "max", 1, 0),
    ("List", "minmax", 1, 0),
    ("List", "minpairs", 8, 4),
    ("List", "maxpairs", 8, 4),
    ("List", "sum", 1, 0),
    ("List", "pick", 3, 1),
    ("List", "roll", 3, 1),
    ("List", "permutations", 1, 1),
    ("List", "combinations", 3, 1),
    ("List", "rotor", 8, 2),
    ("List", "batch", 2, 1),
    ("List", "produce", 8, 2),
    ("List", "reduce", 8, 2),
    ("List", "Bool", 1, 1),
    ("List", "Str", 3, 1),
    ("List", "gist", 1, 1),
    ("List", "raku", 1, 1),
    ("List", "Numeric", 1, 0),
    ("List", "Int", 1, 0),
    ("List", "Array", 1, 1),
    ("List", "List", 1, 1),
    ("Array", "elems", 1, 1),
    ("Array", "end", 1, 1),
    ("Array", "keys", 1, 0),
    ("Array", "values", 1, 0),
    ("Array", "kv", 1, 0),
    ("Array", "pairs", 1, 0),
    ("Array", "antipairs", 1, 0),
    ("Array", "join", 3, 1),
    ("Array", "map", 8, 2),
    ("Array", "grep", 8, 2),
    ("Array", "first", 1, 0),
    ("Array", "sort", 1, 0),
    ("Array", "reverse", 1, 0),
    ("Array", "rotate", 8, 2),
    ("Array", "unique", 1, 1),
    ("Array", "repeated", 1, 1),
    ("Array", "squish", 1, 0),
    ("Array", "flat", 7, 1),
    ("Array", "eager", 8, 4),
    ("Array", "lazy", 1, 1),
    ("Array", "head", 3, 1),
    ("Array", "tail", 3, 1),
    ("Array", "skip", 8, 4),
    ("Array", "push", 8, 2),
    ("Array", "pop", 8, 2),
    ("Array", "shift", 8, 2),
    ("Array", "unshift", 8, 2),
    ("Array", "splice", 8, 2),
    ("Array", "append", 8, 2),
    ("Array", "prepend", 8, 2),
    ("Array", "classify", 8, 2),
    ("Array", "categorize", 8, 2),
    ("Array", "min", 1, 0),
    ("Array", "max", 1, 0),
    ("Array", "minmax", 1, 0),
    ("Array", "minpairs", 8, 4),
    ("Array", "maxpairs", 8, 4),
    ("Array", "sum", 1, 0),
    ("Array", "pick", 3, 1),
    ("Array", "roll", 3, 1),
    ("Array", "permutations", 1, 1),
    ("Array", "combinations", 3, 1),
    ("Array", "rotor", 8, 2),
    ("Array", "batch", 2, 1),
    ("Array", "produce", 8, 2),
    ("Array", "reduce", 8, 2),
    ("Array", "Bool", 1, 1),
    ("Array", "Str", 3, 1),
    ("Array", "gist", 1, 1),
    ("Array", "raku", 1, 1),
    ("Array", "Numeric", 1, 0),
    ("Array", "Int", 1, 0),
    ("Array", "Array", 1, 1),
    ("Array", "List", 1, 1),
    ("Hash", "elems", 1, 1),
    ("Hash", "keys", 1, 0),
    ("Hash", "values", 1, 0),
    ("Hash", "kv", 1, 0),
    ("Hash", "pairs", 1, 0),
    ("Hash", "antipairs", 1, 0),
    ("Hash", "push", 8, 2),
    ("Hash", "append", 8, 2),
    ("Hash", "classify-list", 8, 4),
    ("Hash", "categorize-list", 8, 4),
    ("Hash", "Bool", 1, 1),
    ("Hash", "Str", 3, 1),
    ("Hash", "gist", 1, 1),
    ("Hash", "raku", 1, 1),
    ("Hash", "Numeric", 1, 0),
    ("Hash", "Int", 1, 0),
    ("Bool", "pred", 1, 1),
    ("Bool", "succ", 1, 1),
    ("Bool", "pick", 3, 1),
    ("Bool", "roll", 3, 1),
    ("Bool", "Numeric", 1, 0),
    ("Bool", "Int", 1, 0),
    ("Bool", "Num", 1, 0),
    ("Bool", "Rat", 3, 1),
    ("Bool", "Bool", 1, 1),
    ("Bool", "Str", 3, 1),
    ("Bool", "gist", 1, 1),
    ("Bool", "raku", 1, 1),
    ("Range", "min", 1, 0),
    ("Range", "max", 1, 0),
    ("Range", "bounds", 1, 0),
    ("Range", "elems", 1, 1),
    ("Range", "list", 1, 1),
    ("Range", "flat", 7, 1),
    ("Range", "reverse", 1, 0),
    ("Range", "pick", 3, 1),
    ("Range", "roll", 3, 1),
    ("Range", "sum", 1, 0),
    ("Range", "rand", 1, 0),
    ("Range", "minmax", 1, 0),
    ("Range", "infinite", 1, 0),
    ("Range", "is-int", 1, 0),
    ("Range", "Bool", 1, 1),
    ("Range", "Str", 3, 1),
    ("Range", "gist", 1, 1),
    ("Range", "raku", 1, 1),
    ("Range", "Numeric", 1, 0),
    ("Range", "Int", 1, 0),
    ("Range", "excludes-min", 1, 0),
    ("Range", "excludes-max", 1, 0),
    ("Blob", "allocate", 8, 4),
    ("Blob", "new", 8, 2),
    ("Blob", "push", 8, 2),
    ("Blob", "pop", 8, 2),
    ("Blob", "shift", 8, 2),
    ("Blob", "unshift", 8, 2),
    ("Blob", "append", 8, 2),
    ("Blob", "prepend", 8, 2),
    ("Blob", "splice", 8, 2),
    ("Blob", "reallocate", 8, 4),
    ("Blob", "subbuf", 6, 0),
    ("Blob", "subbuf-rw", 4, 0),
    ("Blob", "decode", 1, 0),
    ("Blob", "elems", 1, 0),
    ("Blob", "bytes", 1, 0),
    ("Blob", "of", 1, 0),
    ("Blob", "reverse", 1, 0),
    ("Blob", "list", 1, 0),
    ("Blob", "Blob", 1, 0),
    ("Blob", "Buf", 1, 0),
    ("Blob", "Bool", 1, 0),
    ("Blob", "Str", 3, 0),
    ("Blob", "gist", 1, 0),
    ("Blob", "raku", 1, 0),
    // ADR-0019 E2b: universal Any/Mu methods, added by hand (not probed via
    // `builtin_sample_value`, which has no representative sample for an
    // abstract owner) after `dispatch_owner_coverage`'s 2026-08-10 sweep
    // showed these dominating `native_call_unmodeled` (Str x so alone was
    // 54% of ~38k hits) -- `dispatch_core_str::dispatch`/`dispatch_core_coerce::dispatch`
    // recognize `so`/`not`/`defined` unconditionally for every receiver type
    // (see the `try_dispatch!` chain in `methods_0arg/mod.rs`), so one row
    // per name at the owner that actually declares it (`Any`) is correct and
    // complete once the coverage check walks the MRO chain to find it (see
    // `Interpreter::record_native_row_coverage`) rather than doing a flat
    // point lookup at the receiver's own concrete owner.
    ("Any", "so", 1, 0),
    ("Any", "not", 1, 0),
    ("Any", "defined", 1, 1),
    // `.DEFINITE` is a quoted pseudo-method (like `.WHAT`/`.HOW`/`.WHICH`),
    // deliberately excluded from `MU_METHODS`'s `.^methods` introspection
    // list since it is a compiler-level construct rather than an ordinary
    // dispatchable method -- but `dispatch_core_coerce::dispatch` still
    // recognizes it via the plain arity-0 cascade for any receiver, so it
    // needs a SPECIAL row (never claims a `.^methods`-visible slot) to stop
    // being counted as unmodeled.
    ("Mu", "DEFINITE", 1, 4),
    // ADR-0019 E2b: `Pair`/`Seq` rows, hand-probed against a real
    // `Value::pair`/`Value::seq` sample (2026-08-10) -- neither owner has a
    // `builtin_type_method_names` entry to draw candidates from (see
    // `builtin_type_method_names`'s `_ => Vec::new()` default), so the
    // candidate list was curated from the `Seq`/`Pair` type docs plus the
    // `native_call_unmodeled` sweep breakdown instead of the usual
    // probe-every-catalog-name pass. `so`/`not`/`defined` are deliberately
    // absent here: they are already covered by the `Any` rows above via the
    // chain-walk in `Interpreter::record_native_row_coverage`. Verified by
    // `pair_seq_rows_are_backed_by_the_cascade` in `native_method_row.rs`.
    ("Pair", "antipair", 1, 0),
    ("Pair", "Array", 1, 0),
    ("Pair", "batch", 2, 0),
    ("Pair", "Bool", 1, 0),
    ("Pair", "cache", 1, 0),
    ("Pair", "elems", 1, 0),
    ("Pair", "end", 1, 0),
    ("Pair", "flat", 7, 0),
    ("Pair", "gist", 1, 0),
    ("Pair", "head", 3, 0),
    ("Pair", "invert", 1, 0),
    ("Pair", "item", 1, 0),
    ("Pair", "join", 3, 0),
    ("Pair", "key", 1, 0),
    ("Pair", "keys", 1, 0),
    ("Pair", "kv", 1, 0),
    ("Pair", "lazy", 1, 0),
    ("Pair", "list", 1, 0),
    ("Pair", "List", 1, 0),
    ("Pair", "max", 1, 0),
    ("Pair", "min", 1, 0),
    ("Pair", "pairs", 1, 0),
    ("Pair", "pick", 3, 0),
    ("Pair", "raku", 1, 0),
    ("Pair", "reverse", 1, 0),
    ("Pair", "roll", 3, 0),
    ("Pair", "sink", 1, 0),
    ("Pair", "Slip", 1, 0),
    ("Pair", "Str", 3, 0),
    ("Pair", "tail", 3, 0),
    ("Pair", "unique", 1, 0),
    ("Pair", "value", 1, 0),
    ("Pair", "values", 1, 0),
    ("Pair", "WHICH", 1, 0),
    ("Seq", "Array", 1, 0),
    ("Seq", "batch", 2, 0),
    ("Seq", "Bool", 1, 0),
    ("Seq", "cache", 1, 0),
    ("Seq", "elems", 1, 0),
    ("Seq", "end", 1, 0),
    ("Seq", "flat", 7, 0),
    ("Seq", "gist", 1, 0),
    ("Seq", "head", 3, 0),
    ("Seq", "invert", 1, 0),
    ("Seq", "item", 1, 0),
    ("Seq", "join", 3, 0),
    ("Seq", "keys", 1, 0),
    ("Seq", "kv", 1, 0),
    ("Seq", "lazy", 1, 0),
    ("Seq", "list", 1, 0),
    ("Seq", "List", 1, 0),
    ("Seq", "pairs", 1, 0),
    ("Seq", "pick", 3, 0),
    ("Seq", "raku", 1, 0),
    ("Seq", "reverse", 1, 0),
    ("Seq", "roll", 3, 0),
    ("Seq", "sink", 1, 0),
    ("Seq", "Slip", 1, 0),
    ("Seq", "Str", 3, 0),
    ("Seq", "tail", 3, 0),
    ("Seq", "unique", 1, 0),
    ("Seq", "values", 1, 0),
    ("Seq", "WHICH", 1, 0),
    // ADR-0019 E2b: `Match` rows, hand-probed against a real Match value
    // produced by running `'foo' ~~ /f(o)(o)/` through the interpreter
    // (2026-08-10) -- like `Pair`/`Seq`, `Match` has no
    // `builtin_type_method_names` entry to draw candidates from. Two
    // candidate sources were probed: the explicit 0-arg arm in
    // `methods_0arg/mod.rs` (`"from" | "to" | "pos" | ...`), and every `Str`
    // row name above -- that arm's `_` default falls through to
    // `native_method_0arg` on the matched string
    // (`Value::str(target.to_string_value())`), and the narg cascades for
    // string-shaped methods (`split`/`substr`/`comb`/...) coerce via
    // `target.to_string_value()` regardless of receiver type, so most of
    // `Str`'s surface is reachable from a `Match` receiver too. Only names
    // the probe actually recognized (non-zero arity bits) are listed here --
    // `replace-with`/`ends-with`/`indices`/`match`/`starts-with`/`subst`/
    // `subst-mutate`/`substr-rw`/`substr-eq`/`trans`/`IO` returned zero and
    // are deliberately absent (not natively recognized for a Match
    // receiver). `so`/`not`/`defined` are deliberately absent here too: a
    // Match's `dispatch_owner_chain` includes `Any`, so they are already
    // covered by the `Any` rows above via the chain-walk in
    // `Interpreter::record_native_row_coverage`, same as `Pair`/`Seq`.
    // Verified by `match_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("Match", "pos", 1, 0),
    ("Match", "target", 1, 0),
    ("Match", "clone", 1, 0),
    ("Match", "orig", 1, 0),
    ("Match", "from", 1, 0),
    ("Match", "to", 1, 0),
    ("Match", "made", 1, 0),
    ("Match", "actions", 1, 0),
    ("Match", "ast", 1, 0),
    ("Match", "Bool", 1, 0),
    ("Match", "Numeric", 1, 0),
    ("Match", "caps", 1, 0),
    ("Match", "chunks", 1, 0),
    ("Match", "list", 1, 0),
    ("Match", "hash", 1, 0),
    ("Match", "Hash", 1, 0),
    ("Match", "Array", 1, 0),
    ("Match", "prematch", 1, 0),
    ("Match", "postmatch", 1, 0),
    ("Match", "perl", 1, 0),
    ("Match", "WHICH", 1, 0),
    ("Match", "keys", 1, 0),
    ("Match", "values", 1, 0),
    ("Match", "pairs", 1, 0),
    ("Match", "kv", 1, 0),
    ("Match", "elems", 1, 0),
    ("Match", "Capture", 1, 0),
    ("Match", "chars", 1, 0),
    ("Match", "codes", 1, 0),
    ("Match", "comb", 7, 0),
    ("Match", "chomp", 1, 0),
    ("Match", "chop", 3, 0),
    ("Match", "contains", 2, 0),
    ("Match", "fc", 1, 0),
    ("Match", "flip", 1, 0),
    ("Match", "index", 2, 0),
    ("Match", "lc", 1, 0),
    ("Match", "lines", 3, 0),
    ("Match", "ords", 1, 0),
    ("Match", "pred", 1, 0),
    ("Match", "rindex", 2, 0),
    ("Match", "samecase", 2, 0),
    ("Match", "samemark", 2, 0),
    ("Match", "split", 6, 0),
    ("Match", "substr", 6, 0),
    ("Match", "succ", 1, 0),
    ("Match", "tc", 1, 0),
    ("Match", "trim", 1, 0),
    ("Match", "trim-leading", 1, 0),
    ("Match", "trim-trailing", 1, 0),
    ("Match", "uc", 1, 0),
    ("Match", "words", 3, 0),
    ("Match", "wordcase", 1, 0),
    ("Match", "NFC", 1, 0),
    ("Match", "NFD", 1, 0),
    ("Match", "NFKC", 1, 0),
    ("Match", "NFKD", 1, 0),
    ("Match", "encode", 1, 0),
    ("Match", "uniparse", 1, 0),
    ("Match", "unimatch", 6, 0),
    ("Match", "uniprops", 3, 0),
    ("Match", "parse-names", 1, 0),
    ("Match", "parse-base", 2, 0),
    ("Match", "Int", 1, 0),
    ("Match", "Num", 1, 0),
    ("Match", "Rat", 3, 0),
    ("Match", "Str", 3, 0),
    ("Match", "gist", 1, 0),
    ("Match", "raku", 1, 0),
    ("Match", "fmt", 7, 0),
];
