//! Generated data table for [`super::native_method_row`] -- see that module's
//! doc comment for what this is and how it was produced. Kept in its own file
//! so the ~340 literal rows do not push the logic/tests in
//! `native_method_row.rs` past the repo's 500-line-per-file guideline.

use std::collections::HashSet;
use std::sync::OnceLock;

pub(super) type RawRow = (&'static str, &'static str, u8, u8);

/// [`RAW_ROWS`] with every repeated `(owner, name)` key folded into its first
/// occurrence, in table order. Readers that must see each key once (the
/// lookup table, `.^methods` enumeration) read this, never `RAW_ROWS`
/// directly. Repeats are allowed so that sibling PRs adding the same row
/// merge cleanly instead of breaking `main` (2026-10-03); the
/// `raw_rows_repeated_keys_agree` test still rejects a repeat whose arity or
/// flags differ, since folding that would silently drop one claim.
// Cost: O(1) after the first call; that call is O(r), r = rows in `RAW_ROWS`.
pub(super) fn rows() -> &'static [RawRow] {
    static ROWS: OnceLock<Vec<RawRow>> = OnceLock::new();
    ROWS.get_or_init(|| fold_repeated_keys(RAW_ROWS))
}

/// Keeps the first row of each `(owner, name)` key, in order.
// Cost: O(r), r = `raw.len()`.
pub(super) fn fold_repeated_keys(raw: &[RawRow]) -> Vec<RawRow> {
    let mut seen = HashSet::new();
    raw.iter()
        .filter(|&&(owner, name, _, _)| seen.insert((owner, name)))
        .copied()
        .collect()
}

/// `(owner, name, arity_bits, flag_bits)`. A key may appear more than once
/// with identical values; see [`rows`].
#[rustfmt::skip]
pub(super) const RAW_ROWS: &[(&str, &str, u8, u8)] = &[
    ("Str", "chars", 1, 25),
    ("Str", "codes", 1, 25),
    ("Str", "comb", 7, 25),
    ("Str", "chomp", 1, 25),
    ("Str", "chop", 3, 25),
    ("Str", "contains", 2, 25),
    ("Str", "ends-with", 2, 24),
    ("Str", "fc", 1, 25),
    ("Str", "flip", 1, 25),
    ("Str", "index", 2, 25),
    ("Str", "indices", 8, 28),
    ("Str", "lc", 1, 25),
    ("Str", "lines", 3, 25),
    ("Str", "match", 8, 28),
    ("Str", "ords", 1, 25),
    ("Str", "pred", 1, 25),
    ("Str", "rindex", 2, 25),
    ("Str", "samecase", 2, 25),
    ("Str", "samemark", 2, 25),
    ("Str", "split", 6, 25),
    ("Str", "starts-with", 2, 24),
    ("Str", "substr", 6, 25),
    ("Str", "succ", 1, 25),
    ("Str", "tc", 1, 25),
    ("Str", "trim", 1, 25),
    ("Str", "trim-leading", 1, 25),
    ("Str", "trim-trailing", 1, 25),
    ("Str", "uc", 1, 25),
    ("Str", "words", 3, 25),
    ("Str", "wordcase", 1, 25),
    ("Str", "NFC", 1, 25),
    ("Str", "NFD", 1, 25),
    ("Str", "NFKC", 1, 25),
    ("Str", "NFKD", 1, 25),
    ("Str", "encode", 1, 25),
    ("Str", "uniparse", 1, 25),
    ("Str", "unimatch", 6, 25),
    ("Str", "uniprops", 3, 25),
    ("Str", "parse-names", 1, 9),
    ("Str", "parse-base", 2, 25),
    ("Str", "subst", 8, 28),
    ("Str", "subst-mutate", 8, 26),
    ("Str", "substr-rw", 8, 28),
    ("Str", "substr-eq", 4, 24),
    ("Str", "trans", 8, 28),
    ("Str", "IO", 8, 28),
    ("Str", "Numeric", 1, 24),
    ("Str", "Int", 1, 25),
    ("Str", "Num", 1, 24),
    ("Str", "Rat", 3, 9),
    ("Str", "Bool", 1, 25),
    ("Str", "Str", 3, 25),
    ("Str", "gist", 1, 25),
    ("Str", "raku", 1, 25),
    ("Str", "elems", 1, 9),
    ("Str", "fmt", 7, 9),
    ("Int", "abs", 1, 25),
    ("Int", "ceiling", 1, 25),
    ("Int", "floor", 1, 25),
    ("Int", "round", 3, 25),
    ("Int", "sign", 1, 25),
    ("Int", "sqrt", 1, 25),
    ("Int", "log", 3, 25),
    ("Int", "log10", 1, 25),
    ("Int", "exp", 3, 25),
    ("Int", "roots", 2, 25),
    ("Int", "is-prime", 1, 25),
    ("Int", "chr", 1, 25),
    ("Int", "base", 6, 25),
    ("Int", "polymod", 8, 29),
    ("Int", "expmod", 4, 25),
    ("Int", "pred", 1, 25),
    ("Int", "succ", 1, 25),
    ("Int", "Numeric", 1, 25),
    ("Int", "Int", 1, 25),
    ("Int", "Num", 1, 24),
    ("Int", "Rat", 3, 25),
    ("Int", "Bool", 1, 25),
    ("Int", "Str", 3, 25),
    ("Int", "gist", 1, 25),
    ("Int", "raku", 1, 25),
    ("Num", "abs", 1, 25),
    ("Num", "ceiling", 1, 25),
    ("Num", "floor", 1, 25),
    ("Num", "round", 3, 25),
    ("Num", "sign", 1, 25),
    ("Num", "sqrt", 1, 25),
    ("Num", "log", 3, 25),
    ("Num", "log10", 1, 25),
    ("Num", "exp", 3, 25),
    ("Num", "roots", 2, 25),
    ("Num", "is-prime", 1, 25),
    ("Num", "chr", 1, 9),
    ("Num", "base", 6, 25),
    ("Num", "polymod", 8, 29),
    ("Num", "expmod", 4, 9),
    ("Num", "pred", 1, 25),
    ("Num", "succ", 1, 25),
    ("Num", "Numeric", 1, 25),
    ("Num", "Int", 1, 25),
    ("Num", "Num", 1, 25),
    ("Num", "Rat", 3, 25),
    ("Num", "Bool", 1, 25),
    ("Num", "Str", 3, 25),
    ("Num", "gist", 1, 25),
    ("Num", "raku", 1, 25),
    ("Num", "Bridge", 1, 24),
    ("Num", "Capture", 1, 24),
    ("Num", "Complex", 1, 24),
    ("Num", "FatRat", 3, 24),
    ("Num", "Real", 1, 24),
    ("Num", "WHICH", 1, 24),
    ("Num", "acos", 1, 24),
    ("Num", "acosec", 1, 24),
    ("Num", "acosech", 1, 24),
    ("Num", "acosh", 1, 24),
    ("Num", "acotan", 1, 24),
    ("Num", "acotanh", 1, 24),
    ("Num", "asec", 1, 24),
    ("Num", "asech", 1, 24),
    ("Num", "asin", 1, 24),
    ("Num", "asinh", 1, 24),
    ("Num", "atan", 1, 24),
    ("Num", "atan2", 3, 24),
    ("Num", "atanh", 1, 24),
    ("Num", "cis", 1, 24),
    ("Num", "conj", 1, 24),
    ("Num", "cos", 1, 24),
    ("Num", "cosec", 1, 24),
    ("Num", "cosech", 1, 24),
    ("Num", "cosh", 1, 24),
    ("Num", "cotan", 1, 24),
    ("Num", "cotanh", 1, 24),
    ("Num", "isNaN", 1, 24),
    ("Num", "log2", 1, 24),
    ("Num", "narrow", 1, 24),
    ("Num", "rand", 1, 24),
    ("Num", "sec", 1, 24),
    ("Num", "sech", 1, 24),
    ("Num", "sin", 1, 24),
    ("Num", "sinh", 1, 24),
    ("Num", "tan", 1, 24),
    ("Num", "tanh", 1, 24),
    ("Num", "truncate", 1, 24),
    ("Num", "unpolar", 2, 24),
    ("Rat", "abs", 1, 25),
    ("Rat", "ceiling", 1, 25),
    ("Rat", "floor", 1, 25),
    ("Rat", "round", 3, 25),
    ("Rat", "sign", 1, 25),
    ("Rat", "sqrt", 1, 25),
    ("Rat", "log", 3, 25),
    ("Rat", "log10", 1, 25),
    ("Rat", "exp", 3, 25),
    ("Rat", "roots", 2, 25),
    ("Rat", "is-prime", 1, 25),
    ("Rat", "chr", 1, 9),
    ("Rat", "base", 6, 25),
    ("Rat", "polymod", 8, 29),
    ("Rat", "expmod", 4, 9),
    ("Rat", "pred", 1, 25),
    ("Rat", "succ", 1, 25),
    ("Rat", "Numeric", 1, 25),
    ("Rat", "Int", 1, 25),
    ("Rat", "Num", 1, 24),
    ("Rat", "Rat", 3, 25),
    ("Rat", "Bool", 1, 25),
    ("Rat", "Str", 3, 25),
    ("Rat", "gist", 1, 25),
    ("Rat", "raku", 1, 25),
    ("Complex", "abs", 1, 25),
    ("Complex", "ceiling", 1, 25),
    ("Complex", "floor", 1, 25),
    ("Complex", "round", 3, 25),
    ("Complex", "sign", 1, 9),
    ("Complex", "sqrt", 1, 25),
    ("Complex", "log", 3, 25),
    ("Complex", "log10", 1, 25),
    ("Complex", "exp", 3, 25),
    ("Complex", "roots", 2, 25),
    ("Complex", "is-prime", 1, 9),
    ("Complex", "chr", 1, 9),
    ("Complex", "expmod", 4, 9),
    ("Complex", "pred", 1, 25),
    ("Complex", "succ", 1, 25),
    ("Complex", "Numeric", 1, 25),
    ("Complex", "Int", 1, 25),
    ("Complex", "Num", 8, 28),
    ("Complex", "Rat", 3, 25),
    ("Complex", "Bool", 1, 25),
    ("Complex", "Str", 3, 25),
    ("Complex", "gist", 1, 25),
    ("Complex", "raku", 1, 25),
    ("List", "elems", 1, 25),
    ("List", "end", 1, 25),
    ("List", "keys", 1, 24),
    ("List", "values", 1, 24),
    ("List", "kv", 1, 24),
    ("List", "pairs", 1, 24),
    ("List", "antipairs", 1, 24),
    ("List", "join", 3, 25),
    ("List", "map", 8, 10),
    ("List", "grep", 8, 10),
    ("List", "first", 1, 8),
    ("List", "sort", 1, 24),
    ("List", "reverse", 1, 24),
    ("List", "rotate", 8, 26),
    ("List", "unique", 1, 9),
    ("List", "repeated", 1, 9),
    ("List", "squish", 1, 8),
    ("List", "flat", 7, 25),
    ("List", "eager", 8, 28),
    ("List", "lazy", 1, 25),
    ("List", "head", 3, 25),
    ("List", "tail", 3, 25),
    ("List", "skip", 8, 12),
    ("List", "push", 8, 26),
    ("List", "pop", 8, 26),
    ("List", "shift", 8, 26),
    ("List", "unshift", 8, 26),
    ("List", "splice", 8, 10),
    ("List", "append", 8, 26),
    ("List", "prepend", 8, 26),
    ("List", "classify", 8, 10),
    ("List", "categorize", 8, 10),
    ("List", "min", 1, 8),
    ("List", "max", 1, 8),
    ("List", "minmax", 1, 8),
    ("List", "minpairs", 8, 12),
    ("List", "maxpairs", 8, 12),
    ("List", "sum", 1, 24),
    ("List", "pick", 3, 25),
    ("List", "roll", 3, 25),
    ("List", "permutations", 1, 25),
    ("List", "combinations", 3, 25),
    ("List", "rotor", 8, 10),
    ("List", "batch", 2, 9),
    ("List", "produce", 8, 10),
    ("List", "reduce", 8, 10),
    ("List", "Bool", 1, 25),
    ("List", "Str", 3, 25),
    ("List", "gist", 1, 25),
    ("List", "raku", 1, 25),
    ("List", "Numeric", 1, 24),
    ("List", "Int", 1, 24),
    ("List", "Array", 1, 25),
    ("List", "List", 1, 25),
    // ADR-0019 E2b: `List`/`Array` rows for names absent from `LIST_METHODS`
    // (`builtin_type_method_names`'s candidate source for these two owners),
    // hand-probed against a real `Value::array` sample (2026-08-10) the same
    // way the `Match` rows above were -- `list`/`item`/`Slip`/`WHICH`/
    // `AT-POS`/etc. are real recognized names the original 14-slice
    // candidate list never included, not a probing gap. `dynamic` is
    // deliberately `Array`-only (not `List`): the cascade's own guard
    // (`methods_0arg/mod.rs`) restricts `.dynamic` to non-`List`-kind Array
    // values. Verified by `array_list_extra_rows_are_backed_by_the_cascade`
    // in `native_method_row.rs`.
    ("List", "list", 1, 24),
    ("List", "item", 1, 24),
    ("List", "Slip", 1, 24),
    ("List", "cache", 1, 0),
    ("List", "sink", 1, 24),
    ("List", "invert", 1, 24),
    ("List", "WHICH", 1, 0),
    ("List", "AT-POS", 2, 24),
    ("List", "EXISTS-POS", 2, 24),
    ("List", "is-lazy", 1, 24),
    ("List", "Capture", 1, 24),
    ("List", "hyper", 1, 24),
    ("List", "race", 1, 24),
    ("List", "Supply", 1, 24),
    ("Array", "elems", 1, 9),
    ("Array", "end", 1, 9),
    ("Array", "keys", 1, 8),
    ("Array", "values", 1, 8),
    ("Array", "kv", 1, 8),
    ("Array", "pairs", 1, 8),
    ("Array", "antipairs", 1, 8),
    ("Array", "join", 3, 9),
    ("Array", "map", 8, 10),
    ("Array", "grep", 8, 10),
    ("Array", "first", 1, 8),
    ("Array", "sort", 1, 8),
    ("Array", "reverse", 1, 24),
    ("Array", "rotate", 8, 26),
    ("Array", "unique", 1, 9),
    ("Array", "repeated", 1, 9),
    ("Array", "squish", 1, 8),
    ("Array", "flat", 7, 25),
    ("Array", "eager", 8, 12),
    ("Array", "lazy", 1, 9),
    ("Array", "head", 3, 9),
    ("Array", "tail", 3, 25),
    ("Array", "skip", 8, 12),
    ("Array", "push", 8, 26),
    ("Array", "pop", 8, 26),
    ("Array", "shift", 8, 26),
    ("Array", "unshift", 8, 26),
    ("Array", "splice", 8, 26),
    ("Array", "append", 8, 26),
    ("Array", "prepend", 8, 26),
    ("Array", "classify", 8, 10),
    ("Array", "categorize", 8, 10),
    ("Array", "min", 1, 8),
    ("Array", "max", 1, 8),
    ("Array", "minmax", 1, 8),
    ("Array", "minpairs", 8, 12),
    ("Array", "maxpairs", 8, 12),
    ("Array", "sum", 1, 8),
    ("Array", "pick", 3, 9),
    ("Array", "roll", 3, 9),
    ("Array", "permutations", 1, 9),
    ("Array", "combinations", 3, 9),
    ("Array", "rotor", 8, 10),
    ("Array", "batch", 2, 9),
    ("Array", "produce", 8, 10),
    ("Array", "reduce", 8, 10),
    ("Array", "Bool", 1, 9),
    ("Array", "Str", 3, 9),
    ("Array", "gist", 1, 9),
    ("Array", "raku", 1, 25),
    ("Array", "Numeric", 1, 8),
    ("Array", "Int", 1, 8),
    ("Array", "Array", 1, 9),
    ("Array", "List", 1, 25),
    ("Array", "list", 1, 8),
    ("Array", "item", 1, 8),
    ("Array", "Slip", 1, 24),
    ("Array", "cache", 1, 0),
    ("Array", "sink", 1, 8),
    ("Array", "invert", 1, 8),
    ("Array", "WHICH", 1, 24),
    ("Array", "AT-POS", 2, 24),
    ("Array", "EXISTS-POS", 2, 8),
    ("Array", "is-lazy", 1, 8),
    ("Array", "Capture", 1, 8),
    ("Array", "dynamic", 1, 24),
    ("Array", "hyper", 1, 8),
    ("Array", "race", 1, 8),
    ("Array", "Supply", 1, 8),
    ("Hash", "elems", 1, 9),
    ("Hash", "keys", 1, 8),
    ("Hash", "values", 1, 8),
    ("Hash", "kv", 1, 8),
    ("Hash", "pairs", 1, 8),
    ("Hash", "antipairs", 1, 8),
    ("Hash", "push", 8, 26),
    ("Hash", "append", 8, 26),
    ("Hash", "classify-list", 8, 28),
    ("Hash", "categorize-list", 8, 28),
    ("Hash", "Bool", 1, 9),
    ("Hash", "Str", 3, 25),
    ("Hash", "gist", 1, 25),
    ("Hash", "raku", 1, 25),
    ("Hash", "Numeric", 1, 8),
    ("Hash", "Int", 1, 8),
    ("Bool", "pred", 1, 25),
    ("Bool", "succ", 1, 25),
    ("Bool", "pick", 3, 25),
    ("Bool", "roll", 3, 25),
    ("Bool", "Numeric", 1, 24),
    ("Bool", "Int", 1, 24),
    ("Bool", "Num", 1, 8),
    ("Bool", "Rat", 3, 9),
    ("Bool", "Bool", 1, 25),
    ("Bool", "Str", 3, 25),
    ("Bool", "gist", 1, 25),
    ("Bool", "raku", 1, 25),
    ("Bool", "Capture", 1, 8),
    ("Bool", "Complex", 1, 8),
    ("Bool", "FatRat", 3, 8),
    ("Bool", "Real", 1, 24),
    ("Bool", "WHICH", 1, 8),
    ("Bool", "abs", 1, 8),
    ("Bool", "atan2", 2, 8),
    ("Bool", "base", 4, 8),
    ("Bool", "byte", 1, 8),
    ("Bool", "chr", 1, 8),
    ("Bool", "conj", 1, 8),
    ("Bool", "expmod", 4, 8),
    ("Bool", "int", 1, 8),
    ("Bool", "int16", 1, 8),
    ("Bool", "int32", 1, 8),
    ("Bool", "int64", 1, 8),
    ("Bool", "int8", 1, 8),
    ("Bool", "is-prime", 1, 8),
    ("Bool", "isNaN", 1, 8),
    ("Bool", "key", 1, 16),
    ("Bool", "narrow", 1, 8),
    ("Bool", "rand", 1, 8),
    ("Bool", "roots", 2, 8),
    ("Bool", "uint", 1, 8),
    ("Bool", "uint16", 1, 8),
    ("Bool", "uint32", 1, 8),
    ("Bool", "uint64", 1, 8),
    ("Bool", "uint8", 1, 8),
    ("Bool", "unimatch", 6, 8),
    ("Bool", "uniname", 1, 8),
    ("Bool", "uniprop", 3, 8),
    ("Bool", "unival", 1, 8),
    ("Bool", "value", 1, 16),
    ("Range", "min", 1, 24),
    ("Range", "max", 1, 24),
    ("Range", "bounds", 1, 24),
    ("Range", "elems", 1, 25),
    ("Range", "list", 1, 25),
    ("Range", "flat", 7, 25),
    ("Range", "reverse", 1, 24),
    ("Range", "pick", 3, 25),
    ("Range", "roll", 3, 25),
    ("Range", "sum", 1, 24),
    ("Range", "rand", 1, 24),
    ("Range", "minmax", 1, 24),
    ("Range", "infinite", 1, 24),
    ("Range", "is-int", 1, 24),
    ("Range", "Bool", 1, 25),
    ("Range", "Str", 3, 25),
    ("Range", "gist", 1, 9),
    ("Range", "raku", 1, 25),
    ("Range", "Numeric", 1, 24),
    ("Range", "Int", 1, 8),
    ("Range", "excludes-min", 1, 24),
    ("Range", "excludes-max", 1, 24),
    ("Blob", "allocate", 8, 28),
    ("Blob", "new", 8, 26),
    ("Blob", "push", 8, 10),
    ("Blob", "pop", 8, 10),
    ("Blob", "shift", 8, 10),
    ("Blob", "unshift", 8, 10),
    ("Blob", "append", 8, 10),
    ("Blob", "prepend", 8, 10),
    ("Blob", "splice", 8, 10),
    ("Blob", "reallocate", 8, 12),
    ("Blob", "subbuf", 6, 24),
    ("Blob", "subbuf-rw", 4, 8),
    // `decode` is recognized at both A0 (default encoding) and A1 (explicit
    // encoding name, `dispatch_1arg.rs`) -- the A1 arm needs a real encoding
    // name (`"utf-8"`), not the generic empty-string dummy
    // `native_method_arities` tries, so it was originally under-counted as
    // A0-only. Confirmed with a direct `native_method_1arg` probe,
    // 2026-08-10.
    ("Blob", "decode", 3, 24),
    ("Blob", "elems", 1, 24),
    ("Blob", "bytes", 1, 24),
    ("Blob", "of", 1, 24),
    ("Blob", "reverse", 1, 24),
    ("Blob", "list", 1, 24),
    ("Blob", "contents", 1, 24),
    ("Blob", "Blob", 1, 8),
    ("Blob", "Buf", 1, 24),
    ("Blob", "Bool", 1, 24),
    ("Blob", "Str", 3, 24),
    ("Blob", "gist", 1, 24),
    ("Blob", "raku", 1, 24),
    // ADR-0019 E2b (sixth slice, 2026-08-10): `Blob`/`Buf`-family extra rows
    // found once the `record_native_row_coverage` `canonical_builtin_owner`
    // fold (`receiver_class.rs`) started routing `Buf`/`utf8`/`Buf[uint8]`
    // receivers to this table's `Blob` rows -- `values`/`List`/the
    // `read-*`/`write-*` native-endian accessor family
    // (`dispatch_1arg.rs`) were never probed by the original 11-owner E2a
    // generation pass (`Blob` was not one of the 11). `read-*` is A1
    // (offset) or A2 (offset, endianness), never A0.
    ("Blob", "values", 1, 0),
    ("Blob", "List", 1, 0),
    ("Blob", "read-uint8", 6, 24),
    ("Blob", "read-int8", 6, 24),
    ("Blob", "read-uint16", 6, 24),
    ("Blob", "read-int16", 6, 24),
    ("Blob", "read-uint32", 6, 24),
    // `.DEFINITE` is a quoted pseudo-method (like `.WHAT`/`.HOW`/`.WHICH`),
    // deliberately excluded from `MU_METHODS`'s `.^methods` introspection
    // list since it is a compiler-level construct rather than an ordinary
    // dispatchable method -- but `dispatch_core_coerce::dispatch` still
    // recognizes it via the plain arity-0 cascade for any receiver, so it
    // needs a SPECIAL row (never claims a `.^methods`-visible slot) to stop
    // being counted as unmodeled.
    ("Mu", "DEFINITE", 1, 28),
    // ADR-0019 E2b: `Pair`/`Seq` rows, hand-probed against a real
    // `Value::pair`/`Value::seq` sample (2026-08-10) -- neither owner has a
    // `builtin_type_method_names` entry to draw candidates from (see
    // `builtin_type_method_names`'s `_ => Vec::new()` default), so the
    // candidate list was curated from the `Seq`/`Pair` type docs plus the
    // `native_call_unmodeled` sweep breakdown instead of the usual
    // probe-every-catalog-name pass. `so`/`not`/`defined` are deliberately
    // absent here: they are already covered by the `Any` rows above via the
    // chain-walk in `Interpreter::record_native_row_coverage`. Verified by
    // `pair_seq_rows_are_backed_by_the_cascade` in `native_method_row.rs`.
    ("Pair", "antipair", 1, 16),
    ("Pair", "Array", 1, 0),
    ("Pair", "batch", 2, 0),
    ("Pair", "Bool", 1, 0),
    ("Pair", "cache", 1, 0),
    ("Pair", "elems", 1, 0),
    ("Pair", "end", 1, 0),
    ("Pair", "flat", 7, 0),
    ("Pair", "gist", 1, 16),
    ("Pair", "head", 3, 0),
    ("Pair", "invert", 1, 16),
    ("Pair", "item", 1, 0),
    ("Pair", "join", 3, 0),
    ("Pair", "key", 1, 16),
    ("Pair", "keys", 1, 16),
    ("Pair", "kv", 1, 16),
    ("Pair", "list", 1, 0),
    ("Pair", "List", 1, 0),
    ("Pair", "max", 1, 0),
    ("Pair", "min", 1, 0),
    ("Pair", "pairs", 1, 16),
    ("Pair", "pick", 3, 0),
    ("Pair", "raku", 1, 16),
    ("Pair", "reverse", 1, 0),
    ("Pair", "roll", 3, 0),
    ("Pair", "sink", 1, 0),
    ("Pair", "Slip", 1, 0),
    ("Pair", "Str", 3, 16),
    ("Pair", "tail", 3, 0),
    ("Pair", "unique", 1, 0),
    ("Pair", "value", 1, 16),
    ("Pair", "values", 1, 16),
    ("Pair", "WHICH", 1, 16),
    ("Seq", "Array", 1, 16),
    ("Seq", "batch", 2, 0),
    ("Seq", "Bool", 1, 16),
    ("Seq", "cache", 1, 16),
    ("Seq", "elems", 1, 16),
    ("Seq", "end", 1, 16),
    ("Seq", "flat", 7, 16),
    ("Seq", "gist", 1, 16),
    ("Seq", "head", 3, 16),
    ("Seq", "invert", 1, 0),
    ("Seq", "item", 1, 16),
    ("Seq", "join", 3, 16),
    ("Seq", "keys", 1, 0),
    ("Seq", "kv", 1, 0),
    ("Seq", "lazy", 1, 16),
    ("Seq", "list", 1, 16),
    ("Seq", "List", 1, 16),
    ("Seq", "pairs", 1, 0),
    ("Seq", "pick", 3, 0),
    ("Seq", "raku", 1, 16),
    ("Seq", "reverse", 1, 16),
    ("Seq", "roll", 3, 0),
    ("Seq", "sink", 1, 16),
    ("Seq", "Slip", 1, 16),
    ("Seq", "Str", 3, 16),
    ("Seq", "tail", 3, 0),
    ("Seq", "unique", 1, 0),
    ("Seq", "values", 1, 0),
    ("Seq", "WHICH", 1, 0),
    // ADR-0019 E2b: `Match` rows, hand-probed against a real Match value
    // produced by running `'foo' ~~ /f(o)(o)/` through the interpreter
    // (2026-08-10) -- like `Pair`/`Seq`, `Match` has no
    // `builtin_type_method_names` entry to draw candidates from. Two
    // candidate sources were probed: the explicit 0-arg arm in
    // `methods_0arg/mod.rs` (`"from" | "to" | "pos" | ...`), and every `Str`
    // row name above -- that arm's `_` default falls through to
    // `native_method_0arg` on the matched string
    // (`Value::str(target.to_string_value())`), and the narg cascades for
    // string-shaped methods (`split`/`substr`/`comb`/...) coerce via
    // `target.to_string_value()` regardless of receiver type, so most of
    // `Str`'s surface is reachable from a `Match` receiver too. Only names
    // the probe actually recognized (non-zero arity bits) are listed here --
    // `ends-with`/`indices`/`match`/`starts-with`/`subst`/
    // `subst-mutate`/`substr-rw`/`substr-eq`/`trans`/`IO` returned zero and
    // are deliberately absent (not natively recognized for a Match
    // receiver). `so`/`not`/`defined` are deliberately absent here too: a
    // Match's `dispatch_owner_chain` includes `Any`, so they are already
    // covered by the `Any` rows above via the chain-walk in
    // `Interpreter::record_native_row_coverage`, same as `Pair`/`Seq`.
    // Verified by `match_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("Match", "pos", 1, 16),
    ("Match", "target", 1, 16),
    ("Match", "clone", 1, 16),
    ("Match", "orig", 1, 16),
    ("Match", "from", 1, 16),
    ("Match", "to", 1, 16),
    ("Match", "made", 1, 16),
    ("Match", "actions", 1, 16),
    ("Match", "ast", 1, 16),
    ("Match", "Bool", 1, 16),
    ("Match", "Numeric", 1, 16),
    ("Match", "caps", 1, 16),
    ("Match", "chunks", 1, 16),
    ("Match", "list", 1, 0),
    ("Match", "hash", 1, 0),
    ("Match", "Hash", 1, 0),
    ("Match", "Array", 1, 0),
    ("Match", "prematch", 1, 16),
    ("Match", "postmatch", 1, 16),
    ("Match", "replace-with", 2, 16),
    ("Match", "perl", 1, 0),
    ("Match", "WHICH", 1, 16),
    ("Match", "keys", 1, 0),
    ("Match", "values", 1, 0),
    ("Match", "pairs", 1, 0),
    ("Match", "kv", 1, 0),
    ("Match", "elems", 1, 0),
    ("Match", "Capture", 1, 0),
    ("Match", "chars", 1, 16),
    ("Match", "codes", 1, 0),
    ("Match", "comb", 7, 0),
    ("Match", "chomp", 1, 0),
    ("Match", "chop", 3, 0),
    ("Match", "contains", 2, 0),
    ("Match", "fc", 1, 0),
    ("Match", "flip", 1, 0),
    ("Match", "index", 2, 0),
    ("Match", "lc", 1, 0),
    ("Match", "lines", 3, 0),
    ("Match", "ords", 1, 0),
    ("Match", "rindex", 2, 0),
    ("Match", "samecase", 2, 0),
    ("Match", "samemark", 2, 0),
    ("Match", "split", 6, 0),
    ("Match", "substr", 6, 0),
    ("Match", "tc", 1, 0),
    ("Match", "trim", 1, 0),
    ("Match", "trim-leading", 1, 0),
    ("Match", "trim-trailing", 1, 0),
    ("Match", "uc", 1, 0),
    ("Match", "words", 3, 0),
    ("Match", "wordcase", 1, 0),
    ("Match", "NFC", 1, 0),
    ("Match", "NFD", 1, 0),
    ("Match", "NFKC", 1, 0),
    ("Match", "NFKD", 1, 0),
    ("Match", "encode", 1, 0),
    ("Match", "uniparse", 1, 0),
    ("Match", "unimatch", 6, 0),
    ("Match", "uniprops", 3, 0),
    ("Match", "parse-names", 1, 0),
    ("Match", "Int", 1, 16),
    ("Match", "Num", 1, 16),
    ("Match", "Rat", 3, 0),
    ("Match", "Str", 3, 16),
    ("Match", "gist", 1, 16),
    ("Match", "raku", 1, 16),
    ("Match", "fmt", 7, 0),
    // ADR-0019 E2b (fifth slice, 2026-08-10): seven more `Any` universal
    // pseudo-methods, alongside the existing `so`/`not`/`defined`/`DEFINITE`
    // rows above -- `self`/`clone`/`WHERE`/`WHICH`/`sink`/`item`/`serial`
    // each have a receiver-type-agnostic `_ => ...` fallback arm in
    // `dispatch_core_coerce.rs` (`self`/`WHERE`/`WHICH`/`serial`/`clone`) or
    // `dispatch_core_math.rs` (`sink`/`item`), found by reading every match
    // arm in those two files rather than guessing from the sweep breakdown
    // alone. Verified by
    // `any_second_batch_universal_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("Any", "self", 1, 0),
    ("Any", "clone", 1, 0),
    ("Any", "WHICH", 1, 0),
    ("Any", "sink", 1, 0),
    ("Any", "item", 1, 0),
    ("Any", "serial", 1, 24),
    // ADR-0019 E2b (fifth slice): `Str` extra rows, hand-probed against a
    // real `Value::str_from("abc")` sample -- the Unicode-method cluster
    // (`ord`/`uniname`/`uninames`/`unival`/`univals`/`chrs`/`bytes`) lives in
    // `dispatch_core_unicode.rs` alongside the already-modeled `uniprops`;
    // `uniprop` (singular; distinct from the plural `uniprops` row above) is
    // in the same file. `AST` is `Str`-only (`methods_0arg/mod.rs`, parses
    // the string as Raku source, ADR-0010). `indent` is 1-arg
    // (`methods_narg/dispatch_1arg.rs`). `sprintf`'s recognition depends on
    // the receiver's own content (needs exactly one `%`-directive), not just
    // arg shape -- see the dedicated probe sample in
    // `fifth_slice_extra_rows_are_backed_by_the_cascade`. The remaining
    // names (`list`/`UInt`/`FatRat`/`tclc`/`Range`/`Complex`/`Version`/
    // `Real`/`Date`/`DateTime`/`reverse`/`byte`/`perl`) are ordinary coercion
    // arms that also happen to fire for a plain `Str` receiver. Verified by
    // `fifth_slice_extra_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("Str", "uniprop", 3, 24),
    ("Str", "AST", 1, 0),
    ("Str", "indent", 2, 24),
    ("Str", "list", 1, 0),
    ("Str", "UInt", 1, 0),
    ("Str", "FatRat", 3, 0),
    ("Str", "sprintf", 2, 0),
    ("Str", "ord", 1, 24),
    ("Str", "uniname", 1, 24),
    ("Str", "uninames", 1, 24),
    ("Str", "unival", 1, 24),
    ("Str", "univals", 1, 24),
    ("Str", "chrs", 1, 0),
    ("Str", "tclc", 1, 24),
    ("Str", "Range", 1, 0),
    ("Str", "Complex", 1, 0),
    ("Str", "Version", 1, 24),
    ("Str", "Real", 1, 0),
    ("Str", "Date", 1, 24),
    ("Str", "DateTime", 1, 24),
    ("Str", "reverse", 1, 0),
    ("Str", "byte", 1, 0),
    ("Str", "perl", 1, 0),
    ("Str", "Capture", 1, 24),
    ("Str", "Stringy", 1, 24),
    ("Str", "WHICH", 1, 24),
    ("Str", "naive-word-wrapper", 1, 24),
    // ADR-0019 E2b (fifth slice): `Hash` extra rows, hand-probed against a
    // real `Value::hash(...)` sample. `pick`/`roll` (1-arg count form, plus
    // a bare 0-arg single-pick) live in `dispatch_1arg.rs`/
    // `dispatch_core_range.rs`. `EXISTS-KEY`/`AT-KEY`/`AT-POS`/
    // `EXISTS-POS` are the postcircumfix-subscript protocol methods
    // (`dispatch_1arg.rs`). `List`/`Array`/`invert`/`flat`/`dynamic`/`perl`
    // are ordinary coercion/collection arms that also fire for a Hash
    // receiver. Verified by
    // `fifth_slice_extra_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("Hash", "pick", 3, 8),
    ("Hash", "EXISTS-KEY", 2, 8),
    ("Hash", "AT-KEY", 2, 24),
    ("Hash", "List", 1, 8),
    ("Hash", "invert", 1, 8),
    ("Hash", "flat", 7, 8),
    ("Hash", "Array", 1, 0),
    ("Hash", "AT-POS", 2, 0),
    ("Hash", "EXISTS-POS", 2, 0),
    ("Hash", "dynamic", 1, 24),
    ("Hash", "roll", 3, 8),
    ("Hash", "perl", 1, 0),
    ("Hash", "Capture", 1, 8),
    ("Hash", "WHICH", 1, 24),
    ("Hash", "clone", 1, 24),
    ("Hash", "contains", 2, 8),
    ("Hash", "default", 1, 24),
    ("Hash", "fmt", 7, 8),
    ("Hash", "hash", 1, 8),
    ("Hash", "head", 3, 8),
    ("Hash", "hyper", 1, 8),
    ("Hash", "index", 2, 8),
    ("Hash", "item", 1, 8),
    ("Hash", "lazy", 1, 8),
    ("Hash", "list", 1, 8),
    ("Hash", "race", 1, 8),
    // ADR-0019 E2b (fifth slice): `Int` extra rows, hand-probed against a
    // real `Value::int(2)` sample. `rand`/`elems`/`lsb`/`msb` live in the
    // shared numeric-method cluster `dispatch_core_numeric.rs`, which is
    // tried for every receiver by name only (not gated on a numeric
    // `ValueView`) -- `elems`/`rand` end up recognized for a bare `Int` the
    // same way `uc`/`lc`/`fc`/`tc` do for a bare `Str` (already modeled).
    // `flip`/`uniprop`/`uc` reach an `Int` receiver the same way: their
    // dispatch arms call `target.to_string_value()` unconditionally.
    // `numerator`/`denominator`/`UInt`/`Real`/`Version`/`Complex`/`perl`/
    // `reverse`/`kv`/`pairs`/`int8`/`wordcase`/`rindex`/`EXISTS-KEY`/
    // `AT-KEY`/`EXISTS-POS`/`Array`/`Supply`/`fmt` are ordinary
    // coercion/collection/subscript arms that also fire for a plain `Int`
    // receiver (real Raku semantics for some of these are a separate
    // question from whether mutsu's cascade recognizes the name -- E2b only
    // models the latter). Verified by
    // `fifth_slice_extra_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("Int", "rand", 1, 24),
    ("Int", "elems", 1, 0),
    ("Int", "flip", 1, 0),
    ("Int", "uniprop", 3, 24),
    ("Int", "fmt", 7, 0),
    ("Int", "EXISTS-POS", 2, 0),
    ("Int", "Array", 1, 0),
    ("Int", "lsb", 1, 24),
    ("Int", "msb", 1, 24),
    ("Int", "Supply", 1, 0),
    ("Int", "pairs", 1, 0),
    ("Int", "denominator", 1, 0),
    ("Int", "numerator", 1, 0),
    ("Int", "kv", 1, 0),
    ("Int", "int8", 1, 24),
    ("Int", "rindex", 2, 0),
    ("Int", "EXISTS-KEY", 2, 0),
    ("Int", "AT-KEY", 2, 0),
    ("Int", "UInt", 1, 0),
    ("Int", "wordcase", 1, 0),
    ("Int", "uc", 1, 0),
    ("Int", "Real", 1, 24),
    ("Int", "Version", 1, 0),
    ("Int", "Complex", 1, 24),
    ("Int", "perl", 1, 0),
    ("Int", "reverse", 1, 0),
    ("Int", "Bridge", 1, 24),
    ("Int", "Capture", 1, 24),
    ("Int", "FatRat", 3, 24),
    ("Int", "WHICH", 1, 24),
    ("Int", "acos", 1, 24),
    ("Int", "acosec", 1, 24),
    ("Int", "acosech", 1, 24),
    ("Int", "acosh", 1, 24),
    ("Int", "acotan", 1, 24),
    ("Int", "acotanh", 1, 24),
    ("Int", "asec", 1, 24),
    ("Int", "asech", 1, 24),
    ("Int", "asin", 1, 24),
    ("Int", "asinh", 1, 24),
    ("Int", "atan", 1, 24),
    ("Int", "atan2", 3, 24),
    ("Int", "atanh", 1, 24),
    ("Int", "byte", 1, 24),
    ("Int", "cis", 1, 24),
    ("Int", "conj", 1, 24),
    ("Int", "cos", 1, 24),
    ("Int", "cosec", 1, 24),
    ("Int", "cosech", 1, 24),
    ("Int", "cosh", 1, 24),
    ("Int", "cotan", 1, 24),
    ("Int", "cotanh", 1, 24),
    ("Int", "int", 1, 24),
    ("Int", "int16", 1, 24),
    ("Int", "int32", 1, 24),
    ("Int", "int64", 1, 24),
    ("Int", "isNaN", 1, 24),
    ("Int", "log2", 1, 24),
    ("Int", "narrow", 1, 24),
    ("Int", "sec", 1, 24),
    ("Int", "sech", 1, 24),
    ("Int", "sin", 1, 24),
    ("Int", "sinh", 1, 24),
    ("Int", "tan", 1, 24),
    ("Int", "tanh", 1, 24),
    ("Int", "truncate", 1, 24),
    ("Int", "uint", 1, 24),
    ("Int", "uint16", 1, 24),
    ("Int", "uint32", 1, 24),
    ("Int", "uint64", 1, 24),
    ("Int", "uint8", 1, 24),
    ("Int", "unimatch", 6, 24),
    ("Int", "uniname", 1, 24),
    ("Int", "unival", 1, 24),
    ("Int", "unpolar", 2, 24),
    // ADR-0019 E2b (sixth slice, 2026-08-10): `Set`/`SetHash`/`Bag`/
    // `BagHash`/`Mix`/`MixHash` rows, hand-probed against real values built
    // via `set(...)`/`SetHash.new(...)`/etc through the interpreter --
    // none of the six owners has a `builtin_type_method_names` entry, same
    // situation as `Pair`/`Seq`/`Match`. `grab` (weighted removal) is
    // deliberately absent from `Set`/`SetHash`: those carry no weights, and
    // the cascade genuinely does not recognize it there (confirmed by
    // `setbagmix_rows_are_backed_by_the_cascade` in `native_method_row.rs`,
    // which also probes the `Set`/`SetHash` omission directly).
    ("Set", "keys", 1, 16),
    ("Set", "values", 1, 16),
    ("Set", "kv", 1, 16),
    ("Set", "pairs", 1, 16),
    ("Set", "elems", 1, 16),
    ("Set", "gist", 1, 16),
    ("Set", "raku", 1, 16),
    ("Set", "Str", 3, 16),
    ("Set", "Bool", 1, 16),
    ("Set", "list", 1, 16),
    ("Set", "List", 1, 0),
    ("Set", "Array", 1, 0),
    ("Set", "total", 1, 16),
    // Immutable `Set`'s `grab` IS recognized by the pure cascade
    // (`dispatch_core_range.rs`'s `ValueView::Set(_, false)` arm) -- it
    // always errors ("Cannot call .grab on an immutable Set"), but `Some`
    // still counts as recognized. The mutable `SetHash` variant
    // (`Set(_, true)`) falls through to the slow path instead (same as
    // `BagHash`/`MixHash` above), so `SetHash` deliberately has no `grab`
    // row here (defaults to `N`/`SPECIAL`).
    ("Set", "grab", 3, 16),
    ("Set", "pick", 3, 16),
    ("Set", "roll", 3, 16),
    ("Set", "WHICH", 1, 16),
    ("Set", "ACCEPTS", 2, 16),
    ("Set", "AT-KEY", 2, 16),
    ("Set", "Capture", 1, 16),
    ("Set", "EXISTS-KEY", 2, 16),
    ("Set", "antipairs", 1, 16),
    ("Set", "default", 1, 16),
    ("Set", "fmt", 7, 16),
    ("Set", "grabpairs", 3, 16),
    ("Set", "hash", 1, 16),
    ("Set", "of", 1, 16),
    ("Set", "pickpairs", 1, 16),
    ("SetHash", "keys", 1, 16),
    ("SetHash", "values", 1, 16),
    ("SetHash", "kv", 1, 16),
    ("SetHash", "pairs", 1, 16),
    ("SetHash", "elems", 1, 16),
    ("SetHash", "gist", 1, 16),
    ("SetHash", "raku", 1, 16),
    ("SetHash", "Str", 3, 16),
    ("SetHash", "Bool", 1, 16),
    ("SetHash", "list", 1, 16),
    ("SetHash", "List", 1, 0),
    ("SetHash", "Array", 1, 0),
    ("SetHash", "total", 1, 16),
    ("SetHash", "pick", 3, 16),
    ("SetHash", "roll", 3, 16),
    ("SetHash", "WHICH", 1, 0),
    ("SetHash", "ACCEPTS", 2, 16),
    ("SetHash", "AT-KEY", 2, 16),
    ("SetHash", "Capture", 1, 16),
    ("SetHash", "EXISTS-KEY", 2, 16),
    ("SetHash", "antipairs", 1, 16),
    ("SetHash", "clone", 1, 16),
    ("SetHash", "default", 1, 16),
    ("SetHash", "fmt", 7, 16),
    ("SetHash", "hash", 1, 16),
    ("SetHash", "of", 1, 16),
    ("SetHash", "pickpairs", 1, 16),
    ("Bag", "keys", 1, 16),
    ("Bag", "values", 1, 16),
    ("Bag", "kv", 1, 16),
    ("Bag", "pairs", 1, 16),
    ("Bag", "elems", 1, 16),
    ("Bag", "gist", 1, 16),
    ("Bag", "raku", 1, 16),
    ("Bag", "Str", 3, 16),
    ("Bag", "Bool", 1, 16),
    ("Bag", "list", 1, 16),
    ("Bag", "List", 1, 0),
    ("Bag", "Array", 1, 0),
    ("Bag", "total", 1, 16),
    ("Bag", "Numeric", 1, 16),
    ("Bag", "grab", 3, 16),
    ("Bag", "pick", 3, 16),
    ("Bag", "roll", 3, 16),
    ("Bag", "WHICH", 1, 16),
    ("Bag", "ACCEPTS", 2, 16),
    ("Bag", "AT-KEY", 2, 16),
    ("Bag", "Capture", 1, 16),
    ("Bag", "EXISTS-KEY", 2, 16),
    ("Bag", "antipairs", 1, 16),
    ("Bag", "default", 1, 16),
    ("Bag", "fmt", 7, 16),
    ("Bag", "grabpairs", 3, 16),
    ("Bag", "hash", 1, 16),
    ("Bag", "invert", 1, 16),
    ("Bag", "kxxv", 1, 16),
    ("Bag", "of", 1, 16),
    ("Bag", "pickpairs", 3, 16),
    ("BagHash", "keys", 1, 16),
    ("BagHash", "values", 1, 16),
    ("BagHash", "kv", 1, 16),
    ("BagHash", "pairs", 1, 16),
    ("BagHash", "elems", 1, 16),
    ("BagHash", "gist", 1, 16),
    ("BagHash", "raku", 1, 16),
    ("BagHash", "Str", 3, 16),
    ("BagHash", "Bool", 1, 16),
    ("BagHash", "list", 1, 16),
    ("BagHash", "List", 1, 0),
    ("BagHash", "Array", 1, 0),
    ("BagHash", "total", 1, 16),
    ("BagHash", "Numeric", 1, 16),
    // `grab` on the *mutable* `BagHash`/`MixHash` variant is served by the
    // `&mut self` slow path (`methods_mut_dispatch.rs`), not the pure
    // arity cascade -- unlike the immutable `Bag`/`Mix`, whose `grab` the
    // cascade DOES recognize (always erroring "immutable", still `Some`).
    // Confirmed by probe: `native_method_arities` returns 0 for a `BagHash`
    // sample. SPECIAL, not omitted, to keep the choice explicit.
    ("BagHash", "grab", 8, 20),
    // `add`/`remove` are declared on `BagHash` itself in rakudo (NOT on the
    // `Baggy` role), so only this owner gets them. Served by the Tier-A
    // mutable-method path (`vm/vm_call_method_mut_ops.rs`), hence
    // MUTATES_RECEIVER rather than an arity-cascade bit.
    ("BagHash", "add", 8, 26),
    ("BagHash", "remove", 8, 26),
    ("BagHash", "pick", 3, 16),
    ("BagHash", "roll", 3, 16),
    ("BagHash", "WHICH", 1, 0),
    ("BagHash", "ACCEPTS", 2, 16),
    ("BagHash", "AT-KEY", 2, 16),
    ("BagHash", "Capture", 1, 16),
    ("BagHash", "EXISTS-KEY", 2, 16),
    ("BagHash", "antipairs", 1, 16),
    ("BagHash", "clone", 1, 16),
    ("BagHash", "default", 1, 16),
    ("BagHash", "fmt", 7, 16),
    ("BagHash", "hash", 1, 16),
    ("BagHash", "invert", 1, 16),
    ("BagHash", "kxxv", 1, 16),
    ("BagHash", "of", 1, 16),
    ("BagHash", "pickpairs", 3, 16),
    ("Mix", "keys", 1, 16),
    ("Mix", "values", 1, 16),
    ("Mix", "kv", 1, 16),
    ("Mix", "pairs", 1, 16),
    ("Mix", "elems", 1, 16),
    ("Mix", "gist", 1, 16),
    ("Mix", "raku", 1, 16),
    ("Mix", "Str", 3, 16),
    ("Mix", "Bool", 1, 16),
    ("Mix", "list", 1, 16),
    ("Mix", "List", 1, 0),
    ("Mix", "Array", 1, 0),
    ("Mix", "total", 1, 16),
    ("Mix", "Numeric", 1, 16),
    ("Mix", "grab", 3, 16),
    ("Mix", "pick", 3, 16),
    ("Mix", "roll", 3, 16),
    ("Mix", "WHICH", 1, 16),
    ("Mix", "ACCEPTS", 2, 16),
    ("Mix", "AT-KEY", 2, 16),
    ("Mix", "Capture", 1, 16),
    ("Mix", "EXISTS-KEY", 2, 16),
    ("Mix", "antipairs", 1, 16),
    ("Mix", "default", 1, 16),
    ("Mix", "fmt", 7, 16),
    ("Mix", "grabpairs", 3, 16),
    ("Mix", "hash", 1, 16),
    ("Mix", "invert", 1, 16),
    ("Mix", "kxxv", 1, 16),
    ("Mix", "of", 1, 16),
    ("Mix", "pickpairs", 1, 16),
    ("MixHash", "keys", 1, 16),
    ("MixHash", "values", 1, 16),
    ("MixHash", "kv", 1, 16),
    ("MixHash", "pairs", 1, 16),
    ("MixHash", "elems", 1, 16),
    ("MixHash", "gist", 1, 16),
    ("MixHash", "raku", 1, 16),
    ("MixHash", "Str", 3, 16),
    ("MixHash", "Bool", 1, 16),
    ("MixHash", "list", 1, 16),
    ("MixHash", "List", 1, 0),
    ("MixHash", "Array", 1, 0),
    ("MixHash", "total", 1, 16),
    ("MixHash", "Numeric", 1, 16),
    // Same as `BagHash`'s `grab` above: the mutable `MixHash` variant's
    // `grab` is slow-path-only, not pure-cascade-recognized.
    ("MixHash", "grab", 8, 20),
    ("MixHash", "pick", 3, 16),
    ("MixHash", "roll", 3, 16),
    ("MixHash", "WHICH", 1, 0),
    ("MixHash", "ACCEPTS", 2, 16),
    ("MixHash", "AT-KEY", 2, 16),
    ("MixHash", "Capture", 1, 16),
    ("MixHash", "EXISTS-KEY", 2, 16),
    ("MixHash", "antipairs", 1, 16),
    ("MixHash", "clone", 1, 16),
    ("MixHash", "default", 1, 16),
    ("MixHash", "fmt", 7, 16),
    ("MixHash", "hash", 1, 16),
    ("MixHash", "invert", 1, 16),
    ("MixHash", "kxxv", 1, 16),
    ("MixHash", "of", 1, 16),
    ("MixHash", "pickpairs", 1, 16),
    // ADR-0019 E2b (sixth slice): `RakuAST::StatementList` rows, hand-probed
    // against a real `Str.AST` parse tree (`'my $x = 1 + 2;'.AST`) -- no
    // `builtin_type_method_names` entry either. `RakuAST::Statement::Expression`'s
    // `expression` field accessor reaches the generic `rakuast::node_accessor`
    // dispatch (`methods_0arg/mod.rs`), the same mechanism every RakuAST node
    // class uses for its own fields, not something `StatementList`-specific.
    // Verified by `rakuast_statementlist_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("RakuAST::StatementList", "gist", 1, 0),
    ("RakuAST::StatementList", "statements", 1, 0),
    ("RakuAST::StatementList", "add-statement", 2, 0),
    ("RakuAST::StatementList", "unshift-statement", 2, 0),
    ("RakuAST::CompUnit", "replace-statement-list", 2, 0),
    ("RakuAST::Statement::Expression", "set-expression", 2, 0),
    ("RakuAST::ArgList", "push", 2, 0),
    ("RakuAST::StatementList", "raku", 1, 16),
    ("RakuAST::StatementList", "Str", 3, 16),
    ("RakuAST::StatementList", "WHICH", 1, 0),
    ("RakuAST::StatementList", "list", 1, 16),
    ("RakuAST::StatementList", "List", 1, 0),
    ("RakuAST::StatementList", "elems", 1, 0),
    ("RakuAST::StatementList", "Bool", 1, 16),
    ("RakuAST::StatementList", "flat", 7, 0),
    ("RakuAST::Statement::Expression", "expression", 1, 0),
    // ADR-0019 E2b (seventh slice, 2026-08-10): `Failure`/`X::AdHoc`/
    // `CX::Warn`/`X::TypeCheck::Assignment` rows, hand-probed against real
    // values raised via the interpreter -- `so`/`not`/`defined`/`self`/
    // `clone`/`WHERE`/`WHICH`/`sink`/`item`/`serial` are deliberately absent
    // from all four: they are the `Any` universal rows above, now reachable
    // via the chain walk after the `Exception`/`CX::Warn`/`Failure`
    // `builtin_type_catalog` fixes. `resume`/`backtrace`/`message`/`throw`/
    // `raku` vary per concrete type (confirmed by direct probe, not assumed
    // shared -- e.g. `CX::Warn` lacks `throw`/`raku`; `Failure` lacks
    // `message`/`backtrace`). Verified by
    // `exception_family_rows_are_backed_by_the_cascade` in
    // `native_method_row.rs`.
    ("Failure", "resume", 1, 0),
    ("Failure", "exception", 1, 0),
    ("Failure", "handled", 1, 0),
    ("Failure", "gist", 1, 0),
    ("Failure", "raku", 1, 0),
    ("Failure", "Str", 3, 0),
    ("Failure", "Bool", 1, 0),
    ("Failure", "throw", 1, 0),
    ("X::AdHoc", "message", 1, 16),
    ("X::AdHoc", "payload", 1, 16),
    ("X::AdHoc", "resume", 1, 0),
    ("X::AdHoc", "backtrace", 1, 0),
    ("X::AdHoc", "gist", 1, 0),
    ("X::AdHoc", "Str", 3, 0),
    ("X::AdHoc", "Bool", 1, 0),
    ("X::AdHoc", "throw", 1, 0),
    ("CX::Warn", "message", 1, 16),
    ("CX::Warn", "resume", 1, 0),
    ("CX::Warn", "backtrace", 1, 0),
    ("CX::Warn", "gist", 1, 0),
    ("CX::Warn", "Str", 3, 0),
    ("CX::Warn", "Bool", 1, 0),
    ("X::TypeCheck::Assignment", "message", 1, 16),
    ("X::TypeCheck::Assignment", "resume", 1, 0),
    ("X::TypeCheck::Assignment", "backtrace", 1, 0),
    ("X::TypeCheck::Assignment", "gist", 1, 0),
    ("X::TypeCheck::Assignment", "Str", 3, 0),
    ("X::TypeCheck::Assignment", "Bool", 1, 0),
    ("X::TypeCheck::Assignment", "throw", 1, 0),
    // ADR-0019 E2b (eighth slice, 2026-08-10): the sweep's remaining tail was a
    // long list of single-digit-to-dozens owners with no dominant offender.
    // Each row below was hand-probed against a real value of that owner
    // (constructed via the interpreter, not `builtin_sample_value`, which has
    // no entry for any of these) using `native_method_arities`, the same
    // discipline as every earlier E2b slice. Two are root-cause fixes rather
    // than plain additions:
    // - `Any`'s `gist`/`raku`/`hash` cover the BARE `Any` type object
    //   (`Any.gist` -> "(Any)"), reached via the generic `ValueView::Package`
    //   formatting arm in `dispatch_core_repr.rs` that renders every type
    //   object uniformly -- confirmed the same arm serves user classes too
    //   (`class Foo {}; Foo.gist` -> "(Foo)"), so the row is not a
    //   `Any`-sample artifact.
    // - `Exception`'s `message`/`gist`/`Str` are declared at the shared
    //   `cn == "Exception" || cn.starts_with("X::") || cn.starts_with("CX::")`
    //   gate in `methods_0arg/mod.rs`, so one `Exception`-owner row (found via
    //   the chain-walk, same as `Failure`'s fix in the seventh slice) covers
    //   every `X::*`/`CX::*` type that does NOT already have its own
    //   more-specific row above -- verified against three previously-unmodeled
    //   types (`X::Method::NotFound`, `X::Str::Sprintf::Directives::Unsupported`,
    //   `X::Str::Numeric`) without adding a row for any of them individually.
    ("Any", "hash", 1, 24),
    // #10132: raku's `Any.^lookup("list")` is defined (`Any.list` wraps the
    // invocant in a one-element List).
    ("Any", "list", 1, 25),
    ("Mu", "defined", 1, 24),
    ("Nil", "gist", 1, 0),
    ("Nil", "raku", 1, 0),
    ("Exception", "message", 1, 16),
    ("Exception", "gist", 1, 16),
    ("Exception", "Str", 3, 16),
    // ADR-0019 E2b (tenth slice): `line`/`file`/`backtrace` and `throw`/
    // `resume` are declared in the SAME `cn == "Exception" ||
    // cn.starts_with("X::") || cn.starts_with("CX::")`-gated match blocks in
    // `methods_0arg/mod.rs` as `message`/`gist`/`Str` above (the `throw`/
    // `resume` gates additionally admit `Failure` and `CX::Warn` by name, but
    // those already have their own rows), so one `Exception`-owner row each
    // covers every `X::*`/`CX::*` subtype the chain walk now reaches (see the
    // `register_x` additions in `runtime_init.rs` this same slice).
    ("Exception", "line", 1, 0),
    ("Exception", "file", 1, 0),
    ("Exception", "backtrace", 1, 16),
    ("Exception", "throw", 1, 16),
    ("Exception", "resume", 1, 16),
    ("Version", "Str", 3, 16),
    ("Version", "raku", 1, 16),
    ("Version", "gist", 1, 16),
    ("Version", "parts", 1, 16),
    ("Version", "ACCEPTS", 2, 16),
    ("Version", "Capture", 1, 16),
    ("Version", "Version", 1, 16),
    ("Version", "WHICH", 1, 16),
    ("Version", "plus", 1, 16),
    ("Version", "whatever", 1, 16),
    ("Date", "Str", 3, 16),
    ("Date", "raku", 1, 16),
    ("Date", "gist", 1, 16),
    ("Date", "IO", 8, 28),
    ("Date", "year", 1, 16),
    ("Date", "mm-dd-yyyy", 1, 16),
    ("Date", "yyyy-mm-dd", 1, 16),
    ("Date", "dd-mm-yyyy", 1, 16),
    // ADR-0051 P3 audit finds (2026-08-21): `Date.Date`/`Date.DateTime` are
    // genuine own methods (`date_method_0arg`, `methods_0arg/
    // temporal_dispatch.rs` -- the `"Date"`/`"DateTime"` arms), already
    // dispatched correctly, just missing their row (`Date.^can("Date")`/
    // `("DateTime")` raku-verified as 1, was 0 in mutsu).
    ("Date", "Date", 1, 16),
    ("Date", "DateTime", 1, 16),
    ("DateTime", "Str", 3, 16),
    ("DateTime", "raku", 1, 16),
    ("DateTime", "gist", 1, 16),
    ("DateTime", "hour", 1, 16),
    ("DateTime", "year", 1, 16),
    ("Duration", "Numeric", 1, 16),
    ("Duration", "abs", 1, 16),
    ("Duration", "Int", 1, 16),
    ("Duration", "gist", 1, 16),
    ("Duration", "raku", 1, 16),
    ("Duration", "rand", 1, 16),
    ("Backtrace", "list", 1, 16),
    ("Backtrace", "Str", 3, 16),
    ("Backtrace", "gist", 1, 16),
    ("Backtrace", "AT-POS", 2, 16),
    ("Backtrace::Frame", "is-routine", 1, 16),
    ("Backtrace::Frame", "subname", 1, 16),
    ("Backtrace::Frame", "is-hidden", 1, 16),
    ("Backtrace::Frame", "file", 1, 16),
    ("Backtrace::Frame", "line", 1, 16),
    // `.gist` moved off the fast path: `Backtrace::Frame` has no custom
    // `.gist` in Rakudo, so it falls back to the same attribute-listing
    // default `default_instance_repr` gives `.raku` (which needs `&mut
    // self` to recursively render the synthesized `code` object, so it
    // cannot live in this pure fast-path cascade). No row here, matching
    // `.raku`, which was never rowed for this owner either.
    ("Range", "hyper", 1, 24),
    ("Range", "lazy", 1, 24),
    ("Range", "int-bounds", 1, 24),
    ("Range", "Array", 1, 0),
    ("Range", "join", 1, 0),
    ("Range", "AT-POS", 2, 24),
    ("Range", "Supply", 1, 0),
    ("Range", "race", 1, 24),
    ("Range", "List", 1, 0),
    ("Range", "in-range", 2, 24),
    ("Range", "head", 3, 0),
    ("Range", "EXISTS-POS", 2, 24),
    ("Range", "batch", 2, 0),
    ("Range", "ACCEPTS", 2, 24),
    ("Range", "Capture", 1, 24),
    ("Range", "WHICH", 1, 24),
    ("Range", "contains", 2, 24),
    ("Range", "fmt", 7, 24),
    ("Range", "index", 2, 24),
    ("Range", "is-lazy", 1, 24),
    ("Range", "item", 1, 24),
    ("Rat", "FatRat", 3, 24),
    ("Rat", "nude", 1, 24),
    ("Rat", "Bridge", 1, 24),
    ("Rat", "Complex", 1, 24),
    ("Rat", "Real", 1, 24),
    ("Rat", "WHICH", 1, 24),
    ("Rat", "acos", 1, 24),
    ("Rat", "acosec", 1, 24),
    ("Rat", "acosech", 1, 24),
    ("Rat", "acosh", 1, 24),
    ("Rat", "acotan", 1, 24),
    ("Rat", "acotanh", 1, 24),
    ("Rat", "asec", 1, 24),
    ("Rat", "asech", 1, 24),
    ("Rat", "asin", 1, 24),
    ("Rat", "asinh", 1, 24),
    ("Rat", "atan", 1, 24),
    ("Rat", "atan2", 3, 24),
    ("Rat", "atanh", 1, 24),
    ("Rat", "base-repeating", 2, 24),
    ("Rat", "cis", 1, 24),
    ("Rat", "conj", 1, 24),
    ("Rat", "cos", 1, 24),
    ("Rat", "cosec", 1, 24),
    ("Rat", "cosech", 1, 24),
    ("Rat", "cosh", 1, 24),
    ("Rat", "cotan", 1, 24),
    ("Rat", "cotanh", 1, 24),
    ("Rat", "denominator", 1, 24),
    ("Rat", "isNaN", 1, 24),
    ("Rat", "log2", 1, 24),
    ("Rat", "narrow", 1, 24),
    ("Rat", "norm", 1, 24),
    ("Rat", "numerator", 1, 24),
    ("Rat", "rand", 1, 24),
    ("Rat", "sec", 1, 24),
    ("Rat", "sech", 1, 24),
    ("Rat", "sin", 1, 24),
    ("Rat", "sinh", 1, 24),
    ("Rat", "tan", 1, 24),
    ("Rat", "tanh", 1, 24),
    ("Rat", "truncate", 1, 24),
    ("Rat", "unpolar", 2, 24),
    ("Map", "raku", 1, 16),
    ("Map", "gist", 1, 16),
    ("Map", "keys", 1, 16),
    ("Map", "elems", 1, 16),
    ("Pair", "Pair", 1, 16),
    ("Pair", "ACCEPTS", 2, 16),
    ("Pair", "AT-KEY", 2, 16),
    ("Pair", "Capture", 1, 16),
    ("Pair", "EXISTS-KEY", 2, 16),
    ("Pair", "antipairs", 1, 16),
    ("Pair", "clone", 1, 16),
    ("Pair", "fmt", 7, 16),
    ("CallFrame", "defined", 1, 0),
    ("List", "tree", 1, 0),
    ("List", "pairup", 1, 0),
    ("List", "hash", 1, 0),
    ("List", "fmt", 7, 24),
    ("List", "chrs", 1, 24),
    ("Array", "tree", 1, 0),
    ("Array", "pairup", 1, 0),
    ("Array", "hash", 1, 0),
    ("Array", "fmt", 7, 24),
    ("Array", "chrs", 1, 8),
    ("Array", "clone", 1, 24),
    ("Array", "default", 1, 24),
    ("Attribute", "defined", 1, 0),
    ("IO::Path::Parts", "AT-KEY", 2, 16),
    ("IO::Path::Parts", "AT-POS", 2, 16),
    ("Capture", "list", 1, 16),
    ("Capture", "hash", 1, 16),
    ("Capture", "AT-KEY", 2, 16),
    ("Capture", "AT-POS", 2, 16),
    ("Capture", "Bool", 1, 16),
    ("Capture", "Capture", 1, 16),
    ("Capture", "EXISTS-KEY", 2, 16),
    ("Capture", "EXISTS-POS", 2, 16),
    ("Capture", "Numeric", 1, 16),
    ("Capture", "Str", 3, 16),
    ("Capture", "WHICH", 1, 16),
    ("Capture", "antipairs", 1, 16),
    ("Capture", "elems", 1, 16),
    ("Capture", "gist", 1, 16),
    ("Capture", "keys", 1, 16),
    ("Capture", "kv", 1, 16),
    ("Capture", "pairs", 1, 16),
    ("Capture", "raku", 1, 16),
    ("Capture", "values", 1, 16),
    ("Complex", "UInt", 1, 0),
    ("Complex", "isNaN", 1, 24),
    ("Instant", "to-posix", 1, 16),
    ("Instant", "Numeric", 1, 16),
    ("Instant", "DateTime", 1, 16),
    // ADR-0051 P3 audit find (2026-08-21): `Instant.Date` is a genuine own
    // method too (`methods_0arg/mod.rs`'s `"Date"` arm right next to the
    // `"DateTime"` arm above), already dispatched correctly, just missing
    // its row (`Instant.^can("Date")` raku-verified as 1, was 0 in mutsu).
    ("Instant", "Date", 1, 16),
    // ADR-0051 P2 (2026-09-27): `succ`/`pred`/`base`/`polymod` reach
    // `Instant`/`Duration` through their `Real` role in raku (`.^can` is 1 for
    // each), not through `Cool` -- whose rows for those four names were a
    // false claim (`Cool.^can("succ")` is 0) and are gone. `lazy` likewise
    // lives on the `Iterable` family (`Map`, `List`, `Seq`, `Range`), not on
    // `Any` (`Any.^can("lazy")` is 0).
    ("Instant", "succ", 1, 16),
    ("Instant", "rand", 1, 16),
    ("Instant", "pred", 1, 16),
    ("Instant", "rand", 1, 16),
    ("Instant", "base", 6, 16),
    ("Instant", "polymod", 8, 16),
    ("Instant", "Bool", 1, 16),
    ("Instant", "Bridge", 1, 16),
    ("Instant", "Complex", 1, 16),
    ("Instant", "FatRat", 3, 16),
    ("Instant", "Instant", 1, 16),
    ("Instant", "Int", 1, 16),
    ("Instant", "Num", 1, 16),
    ("Instant", "Rat", 3, 16),
    ("Instant", "Str", 3, 16),
    ("Instant", "abs", 1, 16),
    ("Instant", "gist", 1, 16),
    ("Instant", "isNaN", 1, 16),
    ("Instant", "narrow", 1, 16),
    ("Instant", "raku", 1, 16),
    ("Instant", "tai", 1, 16),
    ("Duration", "succ", 1, 16),
    ("Duration", "pred", 1, 16),
    ("Duration", "base", 6, 16),
    ("Duration", "polymod", 8, 16),
    ("Duration", "Bool", 1, 16),
    ("Duration", "Bridge", 1, 16),
    ("Duration", "Complex", 1, 16),
    ("Duration", "FatRat", 3, 16),
    ("Duration", "Num", 1, 16),
    ("Duration", "Rat", 3, 16),
    ("Duration", "Str", 3, 16),
    ("Duration", "isNaN", 1, 16),
    ("Duration", "narrow", 1, 16),
    ("Duration", "tai", 1, 16),
    ("Map", "lazy", 1, 24),
    // #9948: `hyper`/`race` are `Iterable` methods in raku (`Seq.^can` and
    // `Map.^can` are 1 for both); `List`/`Array`/`Range` already had rows.
    ("Seq", "hyper", 1, 24),
    ("Seq", "race", 1, 24),
    ("Map", "hyper", 1, 24),
    ("Map", "race", 1, 24),
    ("Map", "AT-KEY", 2, 16),
    ("Map", "Bool", 1, 16),
    ("Map", "Capture", 1, 16),
    ("Map", "EXISTS-KEY", 2, 16),
    ("Map", "Int", 1, 16),
    ("Map", "List", 1, 16),
    ("Map", "Numeric", 1, 16),
    ("Map", "Str", 3, 16),
    ("Map", "antipairs", 1, 16),
    ("Map", "clone", 1, 16),
    ("Map", "contains", 2, 16),
    ("Map", "flat", 7, 16),
    ("Map", "fmt", 7, 16),
    ("Map", "hash", 1, 16),
    ("Map", "head", 3, 16),
    ("Map", "index", 2, 16),
    ("Map", "invert", 1, 16),
    ("Map", "item", 1, 16),
    ("Map", "kv", 1, 16),
    ("Map", "list", 1, 16),
    ("Map", "pairs", 1, 16),
    ("Map", "pick", 3, 16),
    ("Map", "roll", 3, 16),
    ("Map", "values", 1, 16),
    // ...and the `Iterable` role type object answers all three itself
    // (`Iterable.hyper.configuration` is how `hyperize` reads its defaults).
    ("Iterable", "lazy", 1, 25),
    ("Iterable", "hyper", 1, 25),
    ("Iterable", "race", 1, 25),
    ("Uni", "Str", 3, 16),
    ("Uni", "AT-POS", 2, 16),
    ("Uni", "Bool", 1, 16),
    ("Uni", "EXISTS-POS", 2, 16),
    ("Uni", "Int", 1, 16),
    ("Uni", "NFC", 1, 16),
    ("Uni", "NFD", 1, 16),
    ("Uni", "NFKC", 1, 16),
    ("Uni", "NFKD", 1, 16),
    ("Uni", "Numeric", 1, 16),
    ("Uni", "codes", 1, 16),
    ("Uni", "elems", 1, 16),
    ("Uni", "encode", 1, 16),
    ("Uni", "gist", 1, 16),
    ("Uni", "list", 1, 16),
    ("Uni", "raku", 1, 16),
    ("Supply", "list", 1, 16),
    ("Junction", "gist", 1, 16),
    ("Junction", "Bool", 1, 16),
    ("Seq", "is-lazy", 1, 16),
    ("Seq", "AT-POS", 2, 16),
    ("Seq", "Capture", 1, 16),
    ("Seq", "EXISTS-POS", 2, 16),
    ("Seq", "Stringy", 1, 16),
    ("Seq", "fmt", 7, 16),
    ("Match", "Stringy", 1, 0),
    ("Match", "join", 3, 0),
    ("Match", "AT-POS", 2, 0),
    ("Match", "not", 1, 16),
    // ADR-0019 E2b (ninth slice, 2026-08-10): three more coherent clusters
    // hand-probed the same way -- the full `Date`/`DateTime` accessor
    // surface and `Backtrace`/`Backtrace::Frame`/`Complex` extras left after
    // the eighth slice's partial coverage. The remaining sweep tail after
    // this slice is genuinely one-off (RakuAST node accessors, NativeCall
    // `CArray[T]` variants, ad-hoc test-fixture class names) with no
    // reusable owner cluster left -- see the ADR progress note for why
    // chasing it further has diminishing returns.
    ("Date", "day", 1, 16),
    ("Date", "month", 1, 16),
    ("Date", "formatter", 1, 16),
    ("Date", "day-of-week", 1, 16),
    ("Date", "succ", 1, 16),
    // ADR-0051 P3 audit find (2026-08-21): `Date.pred` (`date_method_0arg`'s
    // `"pred"` arm, next to the already-rowed `"succ"` arm above) was
    // already dispatched correctly, just missing its row.
    ("Date", "pred", 1, 16),
    ("Date", "perl", 1, 0),
    ("Date", "days-in-year", 1, 16),
    ("Date", "daycount", 1, 16),
    ("DateTime", "minute", 1, 16),
    ("DateTime", "Date", 1, 16),
    ("DateTime", "offset-in-minutes", 1, 16),
    ("DateTime", "day", 1, 16),
    ("DateTime", "month", 1, 16),
    ("DateTime", "second", 1, 16),
    ("DateTime", "timezone", 1, 16),
    ("DateTime", "days-in-year", 1, 16),
    ("DateTime", "dd-mm-yyyy", 1, 16),
    ("DateTime", "mm-dd-yyyy", 1, 16),
    ("DateTime", "yyyy-mm-dd", 1, 16),
    ("DateTime", "offset-in-hours", 1, 16),
    ("DateTime", "Instant", 1, 16),
    // Dateish / DateTime surface that `.can` / `can-ok` / `.^can` must see
    // (raku-verified; all already dispatched, just missing rows --
    // `Date::Calendar::Strftime`'s `%V` gates on `$date.can('week-number')`).
    ("Date", "week", 1, 16),
    ("Date", "week-number", 1, 16),
    ("Date", "week-year", 1, 16),
    ("Date", "weekday-of-month", 1, 16),
    ("Date", "days-in-month", 1, 16),
    ("Date", "is-leap-year", 1, 16),
    ("Date", "day-of-year", 1, 16),
    ("Date", "day-of-month", 1, 16),
    ("Date", "earlier", 8, 28),
    ("Date", "later", 8, 28),
    ("Date", "truncated-to", 8, 28),
    ("Date", "Int", 1, 16),
    ("Date", "Numeric", 1, 16),
    ("Date", "WHICH", 1, 16),
    ("DateTime", "week", 1, 16),
    ("DateTime", "week-number", 1, 16),
    ("DateTime", "week-year", 1, 16),
    ("DateTime", "weekday-of-month", 1, 16),
    ("DateTime", "days-in-month", 1, 16),
    ("DateTime", "is-leap-year", 1, 16),
    ("DateTime", "day-of-year", 1, 16),
    ("DateTime", "day-of-month", 1, 16),
    ("DateTime", "earlier", 8, 28),
    ("DateTime", "later", 8, 28),
    ("DateTime", "truncated-to", 8, 28),
    ("DateTime", "posix", 1, 16),
    ("DateTime", "utc", 8, 28),
    ("DateTime", "local", 8, 28),
    ("DateTime", "whole-second", 1, 16),
    ("DateTime", "julian-date", 1, 16),
    ("DateTime", "modified-julian-date", 1, 16),
    ("DateTime", "in-timezone", 8, 28),
    // ADR-0051 P3 audit finds (2026-08-21): both already dispatched
    // correctly today (the generic by-name `.IO` interceptor already
    // stringifies any non-IO::Handle-like receiver,
    // `methods_dispatch_match.rs`; `DateTime.DateTime` already answers a
    // fresh, value-equal `DateTime` via some other existing fallback --
    // confirmed NOT an identity return, `=:=` is False in both mutsu and
    // real raku), just missing their rows (`DateTime.^can("IO")`/
    // `("DateTime")` raku-verified as 1, was 0 in mutsu).
    ("DateTime", "IO", 8, 28),
    ("DateTime", "DateTime", 8, 28),
    ("DateTime", "Numeric", 1, 16),
    ("DateTime", "WHICH", 1, 16),
    ("DateTime", "day-fraction", 1, 16),
    ("DateTime", "day-of-week", 1, 16),
    ("DateTime", "daycount", 1, 16),
    ("DateTime", "formatter", 1, 16),
    ("DateTime", "hh-mm-ss", 1, 16),
    ("DateTime", "offset", 1, 16),
    ("Backtrace", "flat", 7, 16),
    ("Backtrace", "defined", 1, 0),
    ("Backtrace", "concise", 1, 16),
    ("Backtrace", "summary", 1, 16),
    ("Backtrace", "Stringy", 1, 0),
    ("Backtrace", "full", 1, 16),
    ("Backtrace", "nice", 3, 16),
    ("Backtrace", "next-interesting-index", 7, 16),
    ("Backtrace", "outer-caller-idx", 2, 16),
    ("Backtrace::Frame", "is-setting", 1, 16),
    ("Backtrace::Frame", "code", 1, 16),
    ("Backtrace::Frame", "Str", 3, 16),
    ("Complex", "re", 1, 24),
    ("Complex", "im", 1, 24),
    ("Complex", "reals", 1, 24),
    ("Complex", "conj", 1, 24),
    ("Complex", "reverse", 1, 0),
    ("Complex", "Complex", 1, 24),
    ("Complex", "FatRat", 3, 24),
    ("Complex", "Real", 1, 24),
    ("Complex", "WHICH", 1, 24),
    ("Complex", "acos", 1, 24),
    ("Complex", "acosec", 1, 24),
    ("Complex", "acosech", 1, 24),
    ("Complex", "acosh", 1, 24),
    ("Complex", "acotan", 1, 24),
    ("Complex", "acotanh", 1, 24),
    ("Complex", "asec", 1, 24),
    ("Complex", "asech", 1, 24),
    ("Complex", "asin", 1, 24),
    ("Complex", "asinh", 1, 24),
    ("Complex", "atan", 1, 24),
    ("Complex", "atanh", 1, 24),
    ("Complex", "cis", 1, 24),
    ("Complex", "cos", 1, 24),
    ("Complex", "cosec", 1, 24),
    ("Complex", "cosech", 1, 24),
    ("Complex", "cosh", 1, 24),
    ("Complex", "cotan", 1, 24),
    ("Complex", "cotanh", 1, 24),
    ("Complex", "log2", 1, 24),
    ("Complex", "narrow", 1, 24),
    ("Complex", "polar", 1, 24),
    ("Complex", "sec", 1, 24),
    ("Complex", "sech", 1, 24),
    ("Complex", "sin", 1, 24),
    ("Complex", "sinh", 1, 24),
    ("Complex", "tan", 1, 24),
    ("Complex", "tanh", 1, 24),
    ("Complex", "truncate", 1, 24),
    // ADR-0019 E2b (eleventh slice, 2026-08-10): the RakuAST node-accessor
    // family, the largest remaining homogeneous cluster after the tenth
    // slice closed `X::*`. Every field-accessor call on a `RakuAST::*` node
    // (`rakuast::node_accessor`, `methods_0arg/mod.rs`) is served by ONE
    // shared, data-driven 0-arg dispatch site that reads the node's own
    // `fields` list by name -- there is no per-class Rust match arm to point
    // a comment at, so each row here is simply "this class's real field
    // list", hand-probed against live nodes built the same two ways the
    // existing `t/rakuast-construct-*.t` suite already does: direct
    // `RakuAST::Foo.new(...)` construction for `Parameter`/
    // `ParameterTarget::Var`/`Type::Simple`/`StrLiteral`, and `Q[...].AST`
    // deparse for everything reached more naturally by parsing (a plain
    // string literal like `"abc"` deparses to `QuotedString`, not
    // `StrLiteral` -- confirmed by direct probe, not assumed). See
    // `rakuast::accessor_names` for the (separate, and in a few cases
    // incomplete -- e.g. it does not list `QuotedString`/`Call::Name::
    // WithoutParentheses`/`Statement::If`/`PointyBlock`) introspection-only
    // registry `.^methods`/`.^attributes` read; `node_accessor`'s real
    // per-instance `fields` list is the actual source of truth these rows
    // were verified against.
    ("RakuAST::IntLiteral", "value", 1, 0),
    ("RakuAST::RatLiteral", "value", 1, 0),
    ("RakuAST::StrLiteral", "value", 1, 0),
    ("RakuAST::QuotedString", "segments", 1, 0),
    ("RakuAST::Var::Lexical", "name", 1, 0),
    ("RakuAST::VarDeclaration::Simple", "sigil", 1, 0),
    ("RakuAST::VarDeclaration::Simple", "desigilname", 1, 0),
    ("RakuAST::VarDeclaration::Simple", "initializer", 1, 0),
    ("RakuAST::Initializer::Assign", "expression", 1, 0),
    ("RakuAST::ApplyInfix", "left", 1, 0),
    ("RakuAST::ApplyInfix", "right", 1, 0),
    ("RakuAST::ApplyPrefix", "operand", 1, 0),
    ("RakuAST::Call::Name::WithoutParentheses", "name", 1, 0),
    ("RakuAST::Statement::If", "condition", 1, 0),
    ("RakuAST::Statement::If", "then", 1, 0),
    ("RakuAST::Block", "body", 1, 0),
    ("RakuAST::Blockoid", "statement-list", 1, 0),
    ("RakuAST::PointyBlock", "signature", 1, 0),
    ("RakuAST::Sub", "name", 1, 0),
    ("RakuAST::Sub", "signature", 1, 0),
    ("RakuAST::Sub", "body", 1, 0),
    ("RakuAST::Signature", "parameters", 1, 0),
    ("RakuAST::Parameter", "type", 1, 0),
    ("RakuAST::Parameter", "names", 1, 0),
    ("RakuAST::Parameter", "target", 1, 0),
    ("RakuAST::Parameter", "optional", 1, 0),
    ("RakuAST::Parameter", "default", 1, 0),
    ("RakuAST::Parameter", "where", 1, 0),
    ("RakuAST::Parameter", "slurpy", 1, 0),
    ("RakuAST::ParameterTarget::Var", "name", 1, 0),
    ("RakuAST::Type::Simple", "name", 1, 0),
    // ADR-0019 E11 slice 2 (2026-08-14): rows for the seven owners E2a's
    // original generation pass never covered -- `builtin_sample_value` (the
    // sample-value probe `#[cfg(test)]` helper) had no branch for `Cool`
    // (abstract, no concrete instance), `Any`/`Mu` beyond the handful E2b
    // added by hand, or `Sub`/`Signature`/`IO::Path`/`IO::Handle` (need a
    // real interpreter-constructed value, not a bare `Value::` literal) --
    // see the E11 progress note in the ADR for the gap this closes (E7 step
    // 4's `.^can` shadow-check found `real=true shadow=false` mismatches for
    // any name only reachable via one of these owners, e.g. `12345.chars`,
    // reachable only via a `Cool` row since `Int` has no `chars` row of its
    // own). Hand-probed against real samples: `Cool` against an `Int(2)` and
    // a numeric-parseable `Str("5")` (both exercise the same bridging
    // coercion `"abc".abs` fails to reach -- a plain non-numeric `Str` is
    // content-dependently unrecognized, matching `native_probe_recognizes_
    // per_type_methods`'s existing `Str` sample discrimination, so a
    // numeric-looking sample was used instead of widening that discrimination);
    // `Any`/`Mu` against `Value::package(Symbol::intern(owner))` (the bare
    // type object -- the same sample `eighth_slice_tail_rows_are_backed_by_
    // the_cascade` re-verifies every `Any`/`Mu` row against below, so a
    // definite value like `Int(2)` would over-claim: `Int(2).reverse` is
    // native-recognized but the abstract `Any.reverse` is not, confirmed
    // against real `raku` returning `((Any))` for the latter where mutsu
    // currently errors "No such method" -- a genuine dispatch gap, not this
    // slice's concern, but the row's arity bits must reflect it); `Code`
    // (the folded owner for
    // `Sub`/`Method`/`Block`/`Routine`, see `canonical_builtin_owner`)
    // against a real `sub ($a,$b) {...}` value; `Signature` against
    // `&sub.signature`; `IO::Path` against `"tmp".IO`; `IO::Handle` against
    // a FRESH `"...".IO.open(:w)` handle per candidate name (a handle is
    // stateful, so probing `close` early would starve every later candidate
    // of a real open handle). Candidate names are each owner's declared
    // `builtin_type_method_names` list (`COOL_OWN`+`NUMERIC_COERCIONS`,
    // `ANY_METHODS`, `MU_METHODS`, `CODE_METHODS`, `SIGNATURE_METHODS`,
    // `IO_PATH_METHODS`, `IO_HANDLE_METHODS`) -- every declared name gets a
    // row regardless of probe outcome (`.^can` in real Raku is a static
    // "does the class declare this" check, confirmed via `raku -e 'say
    // Cool.can("abs")'` returning true independent of receiver content), so
    // a name the probe cascade does not recognize at any pure arity still
    // gets a conservative `N`/`SPECIAL` row (existence, not invocation, is
    // what E7 step 4 needs) rather than being omitted. Six `Any` and two
    // `Signature`/two `Mu` candidates already had rows from earlier E2b
    // slices (`so`/`not`/`defined`/`WHERE`/`gist`/`raku` on `Any`,
    // `defined` on `Mu`, `gist`/`raku` on `Signature`) and were left as-is
    // rather than duplicated.
    ("Cool", "substr", 6, 25),
    ("Cool", "chars", 1, 25),
    ("Cool", "codes", 1, 25),
    ("Cool", "chomp", 1, 25),
    ("Cool", "chop", 3, 25),
    ("Cool", "contains", 2, 25),
    ("Cool", "comb", 7, 25),
    ("Cool", "ends-with", 2, 24),
    ("Cool", "fc", 1, 25),
    ("Cool", "flip", 1, 25),
    ("Cool", "index", 2, 25),
    ("Cool", "indices", 8, 28),
    ("Cool", "lc", 1, 25),
    ("Cool", "lines", 3, 25),
    ("Cool", "match", 8, 12),
    ("Cool", "ords", 1, 25),
    ("Cool", "rindex", 2, 25),
    ("Cool", "samecase", 2, 25),
    ("Cool", "split", 6, 25),
    ("Cool", "starts-with", 2, 24),
    ("Cool", "tc", 1, 25),
    ("Cool", "trim", 1, 25),
    ("Cool", "trim-leading", 1, 25),
    ("Cool", "trim-trailing", 1, 25),
    ("Cool", "uc", 1, 25),
    ("Cool", "words", 3, 25),
    ("Cool", "wordcase", 1, 25),
    ("Cool", "abs", 1, 25),
    ("Cool", "ceiling", 1, 25),
    ("Cool", "floor", 1, 25),
    ("Cool", "round", 3, 25),
    ("Cool", "sign", 1, 25),
    ("Cool", "sqrt", 1, 25),
    ("Cool", "log", 3, 25),
    ("Cool", "log10", 1, 25),
    ("Cool", "exp", 3, 25),
    ("Cool", "is-prime", 1, 25),
    ("Cool", "chr", 1, 25),
    ("Cool", "Numeric", 1, 8),
    ("Cool", "Int", 1, 24),
    ("Cool", "Num", 1, 24),
    ("Cool", "Rat", 3, 25),
    ("Cool", "Bool", 1, 9),
    ("Cool", "Str", 3, 9),
    ("Cool", "gist", 1, 9),
    ("Cool", "raku", 1, 9),
    // ADR-0051 P3 (2026-08-21): the rest of `cool_only_builtin_method`'s
    // 94-name list that genuinely resolves via `Cool` in real Rakudo
    // (`Cool.^can(name)` verified nonzero for every row below) but had no
    // row at all -- e2_native_method_exists therefore answered `false` for
    // these on every Cool-derived type (`Instant`/`Duration`/`IO::Path`/
    // `Match` after P1's ancestry fix), which would make P4's gate
    // wrongly reject a genuine call. Arity/TYPE_OBJECT_OK probed against
    // the same `Int(2)`/`Str("5")` pair as the rest of this block, PLUS a
    // direct `Int.<name>` invocation against real `raku` to settle
    // TYPE_OBJECT_OK precisely (`tmp/type_obj_probe.p6`): every name here
    // dies on an indefinite receiver in real Rakudo except `Version`
    // (`Int.Version` succeeds), so only `Version` carries the bit.
    // `sprintf`/`subst`/`IO`/`samespace`/`trans` are handled by named
    // interceptors ahead of the arity cascades (mirrors the existing
    // `("Str", "subst"/"IO"/"trans", 8, 12)` rows), hence `N`/`SPECIAL`.
    // Six cool_only names are deliberately NOT here because real Rakudo's
    // `Cool.^can` is 0 for them -- they resolve through a different,
    // narrower path than `Cool` even though a plain Any-derived class also
    // lacks them (confirmed against `raku`, 2026-08-21):
    // `Date`/`DateTime` are `Str`-only multi candidates (already own rows
    // under `"Str"`), and `lazy`/`race`/`hyper`/`parse-base` resolve
    // through neither `Cool` nor `Any` (some other role/mixin the row
    // catalog does not model per-role) -- adding a `Cool` row for any of
    // these six would be a false claim, not a fix.
    ("Cool", "tclc", 1, 24),
    ("Cool", "subst", 8, 28),
    ("Cool", "sprintf", 8, 28),
    ("Cool", "printf", 8, 28),
    ("Cool", "ord", 1, 24),
    ("Cool", "truncate", 1, 24),
    ("Cool", "log2", 1, 24),
    ("Cool", "sin", 1, 24),
    ("Cool", "cos", 1, 24),
    ("Cool", "tan", 1, 24),
    ("Cool", "asin", 1, 24),
    ("Cool", "acos", 1, 24),
    ("Cool", "atan", 1, 24),
    ("Cool", "atan2", 3, 24),
    ("Cool", "sinh", 1, 24),
    ("Cool", "cosh", 1, 24),
    ("Cool", "tanh", 1, 24),
    ("Cool", "asinh", 1, 24),
    ("Cool", "acosh", 1, 24),
    ("Cool", "atanh", 1, 24),
    ("Cool", "sec", 1, 24),
    ("Cool", "cosec", 1, 24),
    ("Cool", "cotan", 1, 24),
    ("Cool", "sech", 1, 24),
    ("Cool", "cosech", 1, 24),
    ("Cool", "cotanh", 1, 24),
    ("Cool", "cis", 1, 24),
    ("Cool", "unpolar", 2, 24),
    ("Cool", "roots", 2, 24),
    ("Cool", "IO", 8, 28),
    ("Cool", "samemark", 2, 24),
    // NOTE: no `("Cool", "samespace", ...)` row -- unlike the rest of this
    // block, `.samespace` is not actually implemented anywhere in mutsu yet
    // (`"abc".samespace(...)` dies "No such method" for every receiver, not
    // just an `Instance` one), confirmed by `t/can-methods-drift.t`'s
    // "unimplemented samespace is not over-claimed" assertion. Adding a row
    // here would make `.^can`/`e2_native_method_exists` claim a capability
    // that then dies with a different, wrong error when actually invoked --
    // a genuine missing-feature gap, not an ADR-0051 ancestry/row-table gap.
    ("Cool", "trans", 8, 28),
    ("Cool", "indent", 2, 24),
    ("Cool", "uniname", 1, 24),
    ("Cool", "uninames", 1, 24),
    ("Cool", "unival", 1, 24),
    ("Cool", "univals", 1, 24),
    ("Cool", "uniprop", 3, 24),
    ("Cool", "uniprops", 3, 24),
    ("Cool", "uniparse", 1, 24),
    ("Cool", "parse-names", 1, 24),
    ("Cool", "NFC", 1, 24),
    ("Cool", "NFD", 1, 24),
    ("Cool", "NFKC", 1, 24),
    ("Cool", "NFKD", 1, 24),
    ("Cool", "encode", 1, 24),
    ("Cool", "UInt", 1, 24),
    ("Cool", "Version", 1, 25),
    // ADR-0019 E11 slice 2 (2026-08-14, follow-up): the native-int-coercion
    // method family (`42.int8`, `"42".byte`, ...), genuinely dispatched via
    // `target.isa_check("Cool")` for the eleven real coercion names,
    // unconditionally for the whole `Cool` family (`methods_0arg/mod.rs`).
    // Found via a `MUTSU_VM_STATS=1` sweep of the full `t/` suite after the
    // rest of this slice landed: one can-shadow mismatch remained
    // (`class=List method=int8 real=true shadow=false`, `t/native-int-
    // coerce-methods-are-cool-only.t`) alongside the known-and-out-of-scope
    // `class=Cancellation method=cancel` (see the ADR E11 progress note).
    // Hand-probed against the same `Int(2)`/`Str("5")` pair as the rest of
    // the `Cool` rows above, plus the bare `Cool` type object (all eleven
    // recognize at arity 0 there too, unlike most of the `Cool` block).
    //
    // **Correction (ADR-0019 Phase F box F3 step 2, 2026-08-15):** this
    // comment used to say these were "NOT in `COOL_OWN` ... deliberately
    // excluded from `.^methods`/`.^can`-by-list to avoid making every value
    // spuriously 'can' a C-width alias like `bool`". That conflated two
    // different lists: `is_native_int_coerce_method`'s exclusion concern is
    // about `NATIVE_INT_TYPES` (`bool`/`long`/`ulong`/... name a *type*, not
    // a method, and must never be dispatched as one) and is unrelated to
    // whether the eleven real coercion methods appear in `COOL_OWN`. `.^can`
    // already answered correctly for these eleven via this row's own arity
    // cascade regardless of `COOL_OWN` membership (`t/native-int-coerce-
    // methods-are-cool-only.t` pins exactly that). Only `.^methods`
    // enumeration was missing them, confirmed a genuine gap against real
    // Rakudo's `Cool.^methods` (F3 step 2's raku-verification triage) and
    // now closed via `COOL_NATIVE_INT_COERCE_TAIL` (`builtin_type_
    // methods.rs`), appended after `NUMERIC_COERCIONS` to match this block's
    // own position in `RAW_ROWS`.
    ("Cool", "int8", 1, 25),
    ("Cool", "int16", 1, 25),
    ("Cool", "int32", 1, 25),
    ("Cool", "int64", 1, 25),
    ("Cool", "uint8", 1, 25),
    ("Cool", "uint16", 1, 25),
    ("Cool", "uint32", 1, 25),
    ("Cool", "uint64", 1, 25),
    ("Cool", "byte", 1, 25),
    ("Cool", "int", 1, 25),
    ("Cool", "uint", 1, 25),
    ("Any", "say", 8, 12),
    ("Any", "put", 8, 12),
    ("Any", "print", 8, 12),
    ("Any", "note", 8, 12),
    // ADR-0019 E2b: universal Any/Mu methods, added by hand (not probed via
    // `builtin_sample_value`, which has no representative sample for an
    // abstract owner) after `dispatch_owner_coverage`'s 2026-08-10 sweep
    // showed these dominating `native_call_unmodeled` (Str x so alone was
    // 54% of ~38k hits) -- `dispatch_core_str::dispatch`/`dispatch_core_coerce::dispatch`
    // recognize `so`/`not`/`defined` unconditionally for every receiver type
    // (see the `try_dispatch!` chain in `methods_0arg/mod.rs`), so one row
    // per name at the owner that actually declares it (`Any`) is correct and
    // complete once the coverage check walks the MRO chain to find it (see
    // `Interpreter::record_native_row_coverage`) rather than doing a flat
    // point lookup at the receiver's own concrete owner.
    ("Any", "so", 1, 8),
    ("Any", "not", 1, 8),
    ("Any", "defined", 1, 9),
    ("Any", "WHAT", 8, 12),
    ("Any", "WHERE", 1, 8),
    ("Any", "HOW", 8, 12),
    ("Any", "WHY", 8, 12),
    ("Any", "iterator", 8, 28),
    ("Any", "flat", 7, 24),
    ("Any", "eager", 8, 28),
    ("Any", "map", 8, 28),
    ("Any", "grep", 8, 28),
    ("Any", "first", 8, 28),
    ("Any", "sort", 8, 28),
    ("Any", "reverse", 8, 28),
    ("Any", "unique", 1, 24),
    ("Any", "repeated", 1, 24),
    ("Any", "squish", 8, 28),
    ("Any", "head", 3, 24),
    ("Any", "tail", 3, 24),
    ("Any", "skip", 8, 28),
    ("Any", "min", 8, 28),
    ("Any", "max", 8, 28),
    ("Any", "minmax", 8, 28),
    ("Any", "elems", 1, 24),
    ("Any", "end", 1, 24),
    ("Any", "keys", 8, 28),
    ("Any", "values", 8, 28),
    ("Any", "kv", 8, 28),
    ("Any", "pairs", 8, 28),
    ("Any", "antipairs", 8, 28),
    ("Any", "classify", 8, 28),
    ("Any", "categorize", 8, 28),
    ("Any", "join", 1, 24),
    ("Any", "pick", 3, 24),
    ("Any", "roll", 1, 24),
    ("Any", "sum", 8, 28),
    ("Any", "reduce", 8, 28),
    ("Any", "produce", 8, 28),
    ("Any", "rotor", 8, 28),
    ("Any", "batch", 2, 24),
    ("Any", "Bool", 1, 8),
    ("Any", "Str", 2, 8),
    ("Any", "gist", 1, 8),
    ("Any", "raku", 1, 8),
    ("Any", "Numeric", 8, 12),
    ("Any", "Int", 8, 12),
    ("Mu", "WHAT", 8, 28),
    ("Mu", "WHERE", 1, 24),
    ("Mu", "HOW", 8, 28),
    ("Mu", "WHY", 8, 28),
    ("Mu", "WHICH", 1, 24),
    ("Mu", "Bool", 1, 24),
    ("Mu", "Str", 2, 24),
    ("Mu", "gist", 1, 24),
    ("Mu", "raku", 1, 24),
    ("Mu", "clone", 1, 24),
    ("Mu", "new", 8, 28),
    ("Code", "name", 8, 28),
    ("Code", "signature", 8, 28),
    ("Code", "arity", 8, 28),
    ("Code", "count", 8, 28),
    ("Code", "of", 8, 28),
    ("Code", "returns", 8, 28),
    // `Code.line`/`Code.file` (declaration source location) are served by the
    // same slow-path dispatch as `name`/`signature` (`runtime/methods_sub.rs`),
    // so they carry the identical `N`/`SPECIAL|INTROSPECTABLE` shape -- and,
    // like those, they ARE real `.^methods`/`.^can` entries on `Code` in Rakudo.
    ("Code", "line", 8, 28),
    ("Code", "file", 8, 28),
    ("Code", "Bool", 1, 9),
    ("Code", "Str", 3, 25),
    ("Code", "gist", 8, 13),
    ("Code", "raku", 8, 13),
    ("Code", "Capture", 1, 24),
    ("Code", "clone", 1, 16),
    ("Signature", "params", 8, 28),
    ("Signature", "arity", 8, 28),
    ("Signature", "count", 8, 28),
    ("Signature", "returns", 8, 28),
    ("Signature", "Bool", 1, 9),
    ("Signature", "Str", 2, 9),
    ("Signature", "gist", 1, 24),
    ("Signature", "raku", 1, 24),
    ("IO::Path", "absolute", 8, 28),
    ("IO::Path", "basename", 8, 28),
    ("IO::Path", "cleanup", 8, 28),
    ("IO::Path", "copy", 8, 28),
    ("IO::Path", "dirname", 8, 28),
    ("IO::Path", "e", 8, 28),
    ("IO::Path", "d", 8, 28),
    ("IO::Path", "f", 8, 28),
    ("IO::Path", "l", 8, 28),
    ("IO::Path", "r", 8, 28),
    ("IO::Path", "w", 8, 28),
    ("IO::Path", "x", 8, 28),
    ("IO::Path", "rw", 8, 28),
    ("IO::Path", "rwx", 8, 28),
    ("IO::Path", "s", 8, 28),
    ("IO::Path", "z", 8, 28),
    ("IO::Path", "extension", 8, 28),
    ("IO::Path", "IO", 8, 28),
    ("IO::Path", "lines", 2, 25),
    ("IO::Path", "mkdir", 8, 28),
    ("IO::Path", "modified", 8, 28),
    ("IO::Path", "accessed", 8, 28),
    ("IO::Path", "changed", 8, 28),
    ("IO::Path", "mode", 8, 28),
    ("IO::Path", "inode", 8, 28),
    ("IO::Path", "dev", 8, 28),
    ("IO::Path", "devtype", 8, 28),
    ("IO::Path", "move", 8, 28),
    ("IO::Path", "open", 8, 28),
    ("IO::Path", "parent", 8, 28),
    ("IO::Path", "parts", 8, 28),
    ("IO::Path", "pred", 8, 29),
    ("IO::Path", "rename", 8, 28),
    ("IO::Path", "resolve", 8, 28),
    ("IO::Path", "rmdir", 8, 28),
    ("IO::Path", "sibling", 8, 28),
    ("IO::Path", "slurp", 8, 28),
    ("IO::Path", "spurt", 8, 28),
    ("IO::Path", "succ", 8, 29),
    ("IO::Path", "symlink", 8, 28),
    ("IO::Path", "link", 8, 28),
    ("IO::Path", "add", 8, 28),
    ("IO::Path", "child", 8, 28),
    ("IO::Path", "unlink", 8, 28),
    ("IO::Path", "chown", 8, 28),
    ("IO::Path", "volume", 8, 28),
    ("IO::Path", "watch", 8, 28),
    ("IO::Path", "words", 3, 25),
    ("IO::Path", "CWD", 8, 28),
    ("IO::Path", "SPEC", 8, 28),
    ("IO::Path", "Bool", 1, 9),
    ("IO::Path", "Str", 2, 25),
    ("IO::Path", "gist", 8, 29),
    ("IO::Path", "raku", 8, 29),
    ("IO::Path", "Numeric", 8, 28),
    ("IO::Path", "Int", 8, 12),
    ("IO::Path", "comb", 1, 24),
    ("IO::Path", "split", 6, 24),
    ("IO::Handle", "open", 8, 28),
    ("IO::Handle", "close", 8, 28),
    ("IO::Handle", "path", 8, 28),
    ("IO::Handle", "IO", 8, 28),
    ("IO::Handle", "slurp", 8, 28),
    ("IO::Handle", "slurp-rest", 8, 28),
    ("IO::Handle", "spurt", 8, 28),
    ("IO::Handle", "lines", 2, 25),
    ("IO::Handle", "words", 3, 25),
    ("IO::Handle", "comb", 1, 25),
    ("IO::Handle", "split", 8, 29),
    ("IO::Handle", "print", 8, 28),
    ("IO::Handle", "print-nl", 8, 28),
    ("IO::Handle", "printf", 8, 28),
    ("IO::Handle", "say", 8, 28),
    ("IO::Handle", "put", 8, 28),
    ("IO::Handle", "get", 8, 28),
    ("IO::Handle", "getc", 8, 28),
    ("IO::Handle", "read", 8, 28),
    ("IO::Handle", "readchars", 8, 28),
    ("IO::Handle", "write", 8, 28),
    ("IO::Handle", "seek", 8, 28),
    ("IO::Handle", "tell", 8, 28),
    ("IO::Handle", "eof", 8, 28),
    ("IO::Handle", "flush", 8, 28),
    ("IO::Handle", "lock", 8, 28),
    ("IO::Handle", "unlock", 8, 28),
    ("IO::Handle", "opened", 8, 28),
    ("IO::Handle", "nl-in", 8, 28),
    ("IO::Handle", "nl-out", 1, 25),
    ("IO::Handle", "chomp", 8, 29),
    ("IO::Handle", "encoding", 8, 28),
    ("IO::Handle", "decode", 8, 12),
    ("IO::Handle", "Supply", 1, 25),
    ("IO::Handle", "native-descriptor", 8, 28),
    ("IO::Handle", "WRITE", 8, 28),
    ("IO::Handle", "READ", 8, 28),
    ("IO::Handle", "t", 8, 28),
    ("IO::Handle", "Bool", 1, 9),
    ("IO::Handle", "Str", 2, 25),
    ("IO::Handle", "gist", 8, 29),
    ("IO::Handle", "raku", 8, 13),
];
