//! Auto-generated Unicode `NamedSequences.txt` lookup table.
//!
//! Some `\c[NAME]` / `uniparse` inputs name a *sequence* of code points
//! rather than a single character (`LATIN CAPITAL LETTER E WITH VERTICAL
//! LINE BELOW AND ACUTE` is U+00C9 U+0329), so this lookup returns a
//! string, not a `char`.
//!
//! 461 entries.

/// Look up a Unicode named character sequence (the caller upper-cases the
/// name before calling).
pub(crate) fn lookup_named_sequence(upper_name: &str) -> Option<&'static str> {
    TABLE
        .binary_search_by_key(&upper_name, |&(name, _)| name)
        .ok()
        .map(|i| TABLE[i].1)
}

static TABLE: &[(&str, &str)] = &[
    ("ARABIC SEQUENCE NOON WITH KEHEH", "\u{0646}\u{06A9}"),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH AE",
        "\u{0626}\u{06D5}",
    ),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH ALEF",
        "\u{0626}\u{0627}",
    ),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA",
        "\u{0626}\u{0649}",
    ),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH E",
        "\u{0626}\u{06D0}",
    ),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH OE",
        "\u{0626}\u{06C6}",
    ),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH U",
        "\u{0626}\u{06C7}",
    ),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH WAW",
        "\u{0626}\u{0648}",
    ),
    (
        "ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH YU",
        "\u{0626}\u{06C8}",
    ),
    ("BENGALI LETTER KHINYA", "\u{0995}\u{09CD}\u{09B7}"),
    ("BENGALI SEQUENCE FOR LETTER RHA", "\u{09A2}\u{09BC}"),
    ("BENGALI SEQUENCE FOR LETTER RRA", "\u{09A1}\u{09BC}"),
    ("BENGALI SEQUENCE FOR LETTER YYA", "\u{09AF}\u{09BC}"),
    ("DEVANAGARI SEQUENCE FOR LETTER DDDHA", "\u{0921}\u{093C}"),
    ("DEVANAGARI SEQUENCE FOR LETTER FA", "\u{092B}\u{093C}"),
    ("DEVANAGARI SEQUENCE FOR LETTER GHHA", "\u{0917}\u{093C}"),
    ("DEVANAGARI SEQUENCE FOR LETTER KHHA", "\u{0916}\u{093C}"),
    ("DEVANAGARI SEQUENCE FOR LETTER QA", "\u{0915}\u{093C}"),
    ("DEVANAGARI SEQUENCE FOR LETTER RHA", "\u{0922}\u{093C}"),
    ("DEVANAGARI SEQUENCE FOR LETTER YYA", "\u{092F}\u{093C}"),
    ("DEVANAGARI SEQUENCE FOR LETTER ZA", "\u{091C}\u{093C}"),
    ("GEORGIAN LETTER U-BRJGU", "\u{10E3}\u{0302}"),
    ("GURMUKHI SEQUENCE FOR LETTER FA", "\u{0A2B}\u{0A3C}"),
    ("GURMUKHI SEQUENCE FOR LETTER GHHA", "\u{0A17}\u{0A3C}"),
    ("GURMUKHI SEQUENCE FOR LETTER KHHA", "\u{0A16}\u{0A3C}"),
    ("GURMUKHI SEQUENCE FOR LETTER LLA", "\u{0A32}\u{0A3C}"),
    ("GURMUKHI SEQUENCE FOR LETTER SHA", "\u{0A38}\u{0A3C}"),
    ("GURMUKHI SEQUENCE FOR LETTER ZA", "\u{0A1C}\u{0A3C}"),
    ("HIRAGANA LETTER BIDAKUON NGA", "\u{304B}\u{309A}"),
    ("HIRAGANA LETTER BIDAKUON NGE", "\u{3051}\u{309A}"),
    ("HIRAGANA LETTER BIDAKUON NGI", "\u{304D}\u{309A}"),
    ("HIRAGANA LETTER BIDAKUON NGO", "\u{3053}\u{309A}"),
    ("HIRAGANA LETTER BIDAKUON NGU", "\u{304F}\u{309A}"),
    ("KATAKANA LETTER AINU CE", "\u{30BB}\u{309A}"),
    ("KATAKANA LETTER AINU P", "\u{31F7}\u{309A}"),
    ("KATAKANA LETTER AINU TO", "\u{30C8}\u{309A}"),
    ("KATAKANA LETTER AINU TU", "\u{30C4}\u{309A}"),
    ("KATAKANA LETTER BIDAKUON NGA", "\u{30AB}\u{309A}"),
    ("KATAKANA LETTER BIDAKUON NGE", "\u{30B1}\u{309A}"),
    ("KATAKANA LETTER BIDAKUON NGI", "\u{30AD}\u{309A}"),
    ("KATAKANA LETTER BIDAKUON NGO", "\u{30B3}\u{309A}"),
    ("KATAKANA LETTER BIDAKUON NGU", "\u{30AF}\u{309A}"),
    ("KEYCAP ASTERISK", "\u{002A}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT EIGHT", "\u{0038}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT FIVE", "\u{0035}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT FOUR", "\u{0034}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT NINE", "\u{0039}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT ONE", "\u{0031}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT SEVEN", "\u{0037}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT SIX", "\u{0036}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT THREE", "\u{0033}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT TWO", "\u{0032}\u{FE0F}\u{20E3}"),
    ("KEYCAP DIGIT ZERO", "\u{0030}\u{FE0F}\u{20E3}"),
    ("KEYCAP NUMBER SIGN", "\u{0023}\u{FE0F}\u{20E3}"),
    ("KHMER CONSONANT SIGN COENG BA", "\u{17D2}\u{1794}"),
    ("KHMER CONSONANT SIGN COENG CA", "\u{17D2}\u{1785}"),
    ("KHMER CONSONANT SIGN COENG CHA", "\u{17D2}\u{1786}"),
    ("KHMER CONSONANT SIGN COENG CHO", "\u{17D2}\u{1788}"),
    ("KHMER CONSONANT SIGN COENG CO", "\u{17D2}\u{1787}"),
    ("KHMER CONSONANT SIGN COENG DA", "\u{17D2}\u{178A}"),
    ("KHMER CONSONANT SIGN COENG DO", "\u{17D2}\u{178C}"),
    ("KHMER CONSONANT SIGN COENG HA", "\u{17D2}\u{17A0}"),
    ("KHMER CONSONANT SIGN COENG KA", "\u{17D2}\u{1780}"),
    ("KHMER CONSONANT SIGN COENG KHA", "\u{17D2}\u{1781}"),
    ("KHMER CONSONANT SIGN COENG KHO", "\u{17D2}\u{1783}"),
    ("KHMER CONSONANT SIGN COENG KO", "\u{17D2}\u{1782}"),
    ("KHMER CONSONANT SIGN COENG LA", "\u{17D2}\u{17A1}"),
    ("KHMER CONSONANT SIGN COENG LO", "\u{17D2}\u{179B}"),
    ("KHMER CONSONANT SIGN COENG MO", "\u{17D2}\u{1798}"),
    ("KHMER CONSONANT SIGN COENG NA", "\u{17D2}\u{178E}"),
    ("KHMER CONSONANT SIGN COENG NGO", "\u{17D2}\u{1784}"),
    ("KHMER CONSONANT SIGN COENG NO", "\u{17D2}\u{1793}"),
    ("KHMER CONSONANT SIGN COENG NYO", "\u{17D2}\u{1789}"),
    ("KHMER CONSONANT SIGN COENG PHA", "\u{17D2}\u{1795}"),
    ("KHMER CONSONANT SIGN COENG PHO", "\u{17D2}\u{1797}"),
    ("KHMER CONSONANT SIGN COENG PO", "\u{17D2}\u{1796}"),
    ("KHMER CONSONANT SIGN COENG RO", "\u{17D2}\u{179A}"),
    ("KHMER CONSONANT SIGN COENG SA", "\u{17D2}\u{179F}"),
    ("KHMER CONSONANT SIGN COENG SHA", "\u{17D2}\u{179D}"),
    ("KHMER CONSONANT SIGN COENG SSA", "\u{17D2}\u{179E}"),
    ("KHMER CONSONANT SIGN COENG TA", "\u{17D2}\u{178F}"),
    ("KHMER CONSONANT SIGN COENG THA", "\u{17D2}\u{1790}"),
    ("KHMER CONSONANT SIGN COENG THO", "\u{17D2}\u{1792}"),
    ("KHMER CONSONANT SIGN COENG TO", "\u{17D2}\u{1791}"),
    ("KHMER CONSONANT SIGN COENG TTHA", "\u{17D2}\u{178B}"),
    ("KHMER CONSONANT SIGN COENG TTHO", "\u{17D2}\u{178D}"),
    ("KHMER CONSONANT SIGN COENG VO", "\u{17D2}\u{179C}"),
    ("KHMER CONSONANT SIGN COENG YO", "\u{17D2}\u{1799}"),
    ("KHMER INDEPENDENT VOWEL SIGN COENG QE", "\u{17D2}\u{17AF}"),
    ("KHMER INDEPENDENT VOWEL SIGN COENG QU", "\u{17D2}\u{17A7}"),
    ("KHMER INDEPENDENT VOWEL SIGN COENG RY", "\u{17D2}\u{17AB}"),
    ("KHMER INDEPENDENT VOWEL SIGN COENG RYY", "\u{17D2}\u{17AC}"),
    ("KHMER VOWEL SIGN AAM", "\u{17B6}\u{17C6}"),
    ("KHMER VOWEL SIGN COENG QA", "\u{17D2}\u{17A2}"),
    ("KHMER VOWEL SIGN OM", "\u{17BB}\u{17C6}"),
    (
        "LATIN CAPITAL LETTER A WITH MACRON AND GRAVE",
        "\u{0100}\u{0300}",
    ),
    (
        "LATIN CAPITAL LETTER A WITH OGONEK AND ACUTE",
        "\u{0104}\u{0301}",
    ),
    (
        "LATIN CAPITAL LETTER A WITH OGONEK AND TILDE",
        "\u{0104}\u{0303}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND CARON",
        "\u{00CA}\u{030C}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND MACRON",
        "\u{00CA}\u{0304}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH DOT ABOVE AND ACUTE",
        "\u{0116}\u{0301}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH DOT ABOVE AND TILDE",
        "\u{0116}\u{0303}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH OGONEK AND ACUTE",
        "\u{0118}\u{0301}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH OGONEK AND TILDE",
        "\u{0118}\u{0303}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW",
        "\u{0045}\u{0329}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW AND ACUTE",
        "\u{00C9}\u{0329}",
    ),
    (
        "LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW AND GRAVE",
        "\u{00C8}\u{0329}",
    ),
    (
        "LATIN CAPITAL LETTER I WITH MACRON AND GRAVE",
        "\u{012A}\u{0300}",
    ),
    (
        "LATIN CAPITAL LETTER I WITH OGONEK AND ACUTE",
        "\u{012E}\u{0301}",
    ),
    (
        "LATIN CAPITAL LETTER I WITH OGONEK AND TILDE",
        "\u{012E}\u{0303}",
    ),
    ("LATIN CAPITAL LETTER J WITH TILDE", "\u{004A}\u{0303}"),
    ("LATIN CAPITAL LETTER L WITH TILDE", "\u{004C}\u{0303}"),
    ("LATIN CAPITAL LETTER M WITH TILDE", "\u{004D}\u{0303}"),
    (
        "LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW",
        "\u{004F}\u{0329}",
    ),
    (
        "LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW AND ACUTE",
        "\u{00D3}\u{0329}",
    ),
    (
        "LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW AND GRAVE",
        "\u{00D2}\u{0329}",
    ),
    ("LATIN CAPITAL LETTER R WITH TILDE", "\u{0052}\u{0303}"),
    (
        "LATIN CAPITAL LETTER S WITH VERTICAL LINE BELOW",
        "\u{0053}\u{0329}",
    ),
    (
        "LATIN CAPITAL LETTER U WITH MACRON AND ACUTE",
        "\u{016A}\u{0301}",
    ),
    (
        "LATIN CAPITAL LETTER U WITH MACRON AND GRAVE",
        "\u{016A}\u{0300}",
    ),
    (
        "LATIN CAPITAL LETTER U WITH MACRON AND TILDE",
        "\u{016A}\u{0303}",
    ),
    (
        "LATIN CAPITAL LETTER U WITH OGONEK AND ACUTE",
        "\u{0172}\u{0301}",
    ),
    (
        "LATIN CAPITAL LETTER U WITH OGONEK AND TILDE",
        "\u{0172}\u{0303}",
    ),
    (
        "LATIN SMALL LETTER A WITH MACRON AND GRAVE",
        "\u{0101}\u{0300}",
    ),
    (
        "LATIN SMALL LETTER A WITH OGONEK AND ACUTE",
        "\u{0105}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER A WITH OGONEK AND TILDE",
        "\u{0105}\u{0303}",
    ),
    ("LATIN SMALL LETTER AE WITH GRAVE", "\u{00E6}\u{0300}"),
    (
        "LATIN SMALL LETTER E WITH CIRCUMFLEX AND CARON",
        "\u{00EA}\u{030C}",
    ),
    (
        "LATIN SMALL LETTER E WITH CIRCUMFLEX AND MACRON",
        "\u{00EA}\u{0304}",
    ),
    (
        "LATIN SMALL LETTER E WITH DOT ABOVE AND ACUTE",
        "\u{0117}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER E WITH DOT ABOVE AND TILDE",
        "\u{0117}\u{0303}",
    ),
    (
        "LATIN SMALL LETTER E WITH OGONEK AND ACUTE",
        "\u{0119}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER E WITH OGONEK AND TILDE",
        "\u{0119}\u{0303}",
    ),
    (
        "LATIN SMALL LETTER E WITH VERTICAL LINE BELOW",
        "\u{0065}\u{0329}",
    ),
    (
        "LATIN SMALL LETTER E WITH VERTICAL LINE BELOW AND ACUTE",
        "\u{00E9}\u{0329}",
    ),
    (
        "LATIN SMALL LETTER E WITH VERTICAL LINE BELOW AND GRAVE",
        "\u{00E8}\u{0329}",
    ),
    (
        "LATIN SMALL LETTER HOOKED SCHWA WITH ACUTE",
        "\u{025A}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER HOOKED SCHWA WITH GRAVE",
        "\u{025A}\u{0300}",
    ),
    (
        "LATIN SMALL LETTER I WITH DOT ABOVE AND ACUTE",
        "\u{0069}\u{0307}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER I WITH DOT ABOVE AND GRAVE",
        "\u{0069}\u{0307}\u{0300}",
    ),
    (
        "LATIN SMALL LETTER I WITH DOT ABOVE AND TILDE",
        "\u{0069}\u{0307}\u{0303}",
    ),
    (
        "LATIN SMALL LETTER I WITH MACRON AND GRAVE",
        "\u{012B}\u{0300}",
    ),
    (
        "LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND ACUTE",
        "\u{012F}\u{0307}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND TILDE",
        "\u{012F}\u{0307}\u{0303}",
    ),
    (
        "LATIN SMALL LETTER J WITH DOT ABOVE AND TILDE",
        "\u{006A}\u{0307}\u{0303}",
    ),
    ("LATIN SMALL LETTER L WITH TILDE", "\u{006C}\u{0303}"),
    ("LATIN SMALL LETTER M WITH TILDE", "\u{006D}\u{0303}"),
    (
        "LATIN SMALL LETTER NG WITH TILDE ABOVE",
        "\u{006E}\u{0360}\u{0067}",
    ),
    (
        "LATIN SMALL LETTER O WITH VERTICAL LINE BELOW",
        "\u{006F}\u{0329}",
    ),
    (
        "LATIN SMALL LETTER O WITH VERTICAL LINE BELOW AND ACUTE",
        "\u{00F3}\u{0329}",
    ),
    (
        "LATIN SMALL LETTER O WITH VERTICAL LINE BELOW AND GRAVE",
        "\u{00F2}\u{0329}",
    ),
    ("LATIN SMALL LETTER OPEN O WITH ACUTE", "\u{0254}\u{0301}"),
    ("LATIN SMALL LETTER OPEN O WITH GRAVE", "\u{0254}\u{0300}"),
    ("LATIN SMALL LETTER R WITH TILDE", "\u{0072}\u{0303}"),
    (
        "LATIN SMALL LETTER S WITH VERTICAL LINE BELOW",
        "\u{0073}\u{0329}",
    ),
    ("LATIN SMALL LETTER SCHWA WITH ACUTE", "\u{0259}\u{0301}"),
    ("LATIN SMALL LETTER SCHWA WITH GRAVE", "\u{0259}\u{0300}"),
    ("LATIN SMALL LETTER TURNED V WITH ACUTE", "\u{028C}\u{0301}"),
    ("LATIN SMALL LETTER TURNED V WITH GRAVE", "\u{028C}\u{0300}"),
    (
        "LATIN SMALL LETTER U WITH MACRON AND ACUTE",
        "\u{016B}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER U WITH MACRON AND GRAVE",
        "\u{016B}\u{0300}",
    ),
    (
        "LATIN SMALL LETTER U WITH MACRON AND TILDE",
        "\u{016B}\u{0303}",
    ),
    (
        "LATIN SMALL LETTER U WITH OGONEK AND ACUTE",
        "\u{0173}\u{0301}",
    ),
    (
        "LATIN SMALL LETTER U WITH OGONEK AND TILDE",
        "\u{0173}\u{0303}",
    ),
    (
        "MODIFIER LETTER EXTRA-HIGH EXTRA-LOW CONTOUR TONE BAR",
        "\u{02E5}\u{02E9}",
    ),
    (
        "MODIFIER LETTER EXTRA-LOW EXTRA-HIGH CONTOUR TONE BAR",
        "\u{02E9}\u{02E5}",
    ),
    ("ORIYA SEQUENCE FOR LETTER RHA", "\u{0B22}\u{0B3C}"),
    ("ORIYA SEQUENCE FOR LETTER RRA", "\u{0B21}\u{0B3C}"),
    (
        "SINHALA CONSONANT SIGN RAKAARAANSAYA",
        "\u{0DCA}\u{200D}\u{0DBB}",
    ),
    ("SINHALA CONSONANT SIGN REPAYA", "\u{0DBB}\u{0DCA}\u{200D}"),
    ("SINHALA CONSONANT SIGN YANSAYA", "\u{0DCA}\u{200D}\u{0DBA}"),
    ("TAMIL CONSONANT C", "\u{0B9A}\u{0BCD}"),
    ("TAMIL CONSONANT H", "\u{0BB9}\u{0BCD}"),
    ("TAMIL CONSONANT J", "\u{0B9C}\u{0BCD}"),
    ("TAMIL CONSONANT K", "\u{0B95}\u{0BCD}"),
    ("TAMIL CONSONANT KSS", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BCD}"),
    ("TAMIL CONSONANT L", "\u{0BB2}\u{0BCD}"),
    ("TAMIL CONSONANT LL", "\u{0BB3}\u{0BCD}"),
    ("TAMIL CONSONANT LLL", "\u{0BB4}\u{0BCD}"),
    ("TAMIL CONSONANT M", "\u{0BAE}\u{0BCD}"),
    ("TAMIL CONSONANT N", "\u{0BA8}\u{0BCD}"),
    ("TAMIL CONSONANT NG", "\u{0B99}\u{0BCD}"),
    ("TAMIL CONSONANT NN", "\u{0BA3}\u{0BCD}"),
    ("TAMIL CONSONANT NNN", "\u{0BA9}\u{0BCD}"),
    ("TAMIL CONSONANT NY", "\u{0B9E}\u{0BCD}"),
    ("TAMIL CONSONANT P", "\u{0BAA}\u{0BCD}"),
    ("TAMIL CONSONANT R", "\u{0BB0}\u{0BCD}"),
    ("TAMIL CONSONANT RR", "\u{0BB1}\u{0BCD}"),
    ("TAMIL CONSONANT S", "\u{0BB8}\u{0BCD}"),
    ("TAMIL CONSONANT SH", "\u{0BB6}\u{0BCD}"),
    ("TAMIL CONSONANT SS", "\u{0BB7}\u{0BCD}"),
    ("TAMIL CONSONANT T", "\u{0BA4}\u{0BCD}"),
    ("TAMIL CONSONANT TT", "\u{0B9F}\u{0BCD}"),
    ("TAMIL CONSONANT V", "\u{0BB5}\u{0BCD}"),
    ("TAMIL CONSONANT Y", "\u{0BAF}\u{0BCD}"),
    ("TAMIL SYLLABLE CAA", "\u{0B9A}\u{0BBE}"),
    ("TAMIL SYLLABLE CAI", "\u{0B9A}\u{0BC8}"),
    ("TAMIL SYLLABLE CAU", "\u{0B9A}\u{0BCC}"),
    ("TAMIL SYLLABLE CE", "\u{0B9A}\u{0BC6}"),
    ("TAMIL SYLLABLE CEE", "\u{0B9A}\u{0BC7}"),
    ("TAMIL SYLLABLE CI", "\u{0B9A}\u{0BBF}"),
    ("TAMIL SYLLABLE CII", "\u{0B9A}\u{0BC0}"),
    ("TAMIL SYLLABLE CO", "\u{0B9A}\u{0BCA}"),
    ("TAMIL SYLLABLE COO", "\u{0B9A}\u{0BCB}"),
    ("TAMIL SYLLABLE CU", "\u{0B9A}\u{0BC1}"),
    ("TAMIL SYLLABLE CUU", "\u{0B9A}\u{0BC2}"),
    ("TAMIL SYLLABLE HAA", "\u{0BB9}\u{0BBE}"),
    ("TAMIL SYLLABLE HAI", "\u{0BB9}\u{0BC8}"),
    ("TAMIL SYLLABLE HAU", "\u{0BB9}\u{0BCC}"),
    ("TAMIL SYLLABLE HE", "\u{0BB9}\u{0BC6}"),
    ("TAMIL SYLLABLE HEE", "\u{0BB9}\u{0BC7}"),
    ("TAMIL SYLLABLE HI", "\u{0BB9}\u{0BBF}"),
    ("TAMIL SYLLABLE HII", "\u{0BB9}\u{0BC0}"),
    ("TAMIL SYLLABLE HO", "\u{0BB9}\u{0BCA}"),
    ("TAMIL SYLLABLE HOO", "\u{0BB9}\u{0BCB}"),
    ("TAMIL SYLLABLE HU", "\u{0BB9}\u{0BC1}"),
    ("TAMIL SYLLABLE HUU", "\u{0BB9}\u{0BC2}"),
    ("TAMIL SYLLABLE JAA", "\u{0B9C}\u{0BBE}"),
    ("TAMIL SYLLABLE JAI", "\u{0B9C}\u{0BC8}"),
    ("TAMIL SYLLABLE JAU", "\u{0B9C}\u{0BCC}"),
    ("TAMIL SYLLABLE JE", "\u{0B9C}\u{0BC6}"),
    ("TAMIL SYLLABLE JEE", "\u{0B9C}\u{0BC7}"),
    ("TAMIL SYLLABLE JI", "\u{0B9C}\u{0BBF}"),
    ("TAMIL SYLLABLE JII", "\u{0B9C}\u{0BC0}"),
    ("TAMIL SYLLABLE JO", "\u{0B9C}\u{0BCA}"),
    ("TAMIL SYLLABLE JOO", "\u{0B9C}\u{0BCB}"),
    ("TAMIL SYLLABLE JU", "\u{0B9C}\u{0BC1}"),
    ("TAMIL SYLLABLE JUU", "\u{0B9C}\u{0BC2}"),
    ("TAMIL SYLLABLE KAA", "\u{0B95}\u{0BBE}"),
    ("TAMIL SYLLABLE KAI", "\u{0B95}\u{0BC8}"),
    ("TAMIL SYLLABLE KAU", "\u{0B95}\u{0BCC}"),
    ("TAMIL SYLLABLE KE", "\u{0B95}\u{0BC6}"),
    ("TAMIL SYLLABLE KEE", "\u{0B95}\u{0BC7}"),
    ("TAMIL SYLLABLE KI", "\u{0B95}\u{0BBF}"),
    ("TAMIL SYLLABLE KII", "\u{0B95}\u{0BC0}"),
    ("TAMIL SYLLABLE KO", "\u{0B95}\u{0BCA}"),
    ("TAMIL SYLLABLE KOO", "\u{0B95}\u{0BCB}"),
    ("TAMIL SYLLABLE KSSA", "\u{0B95}\u{0BCD}\u{0BB7}"),
    ("TAMIL SYLLABLE KSSAA", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BBE}"),
    ("TAMIL SYLLABLE KSSAI", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BC8}"),
    ("TAMIL SYLLABLE KSSAU", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BCC}"),
    ("TAMIL SYLLABLE KSSE", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BC6}"),
    ("TAMIL SYLLABLE KSSEE", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BC7}"),
    ("TAMIL SYLLABLE KSSI", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BBF}"),
    ("TAMIL SYLLABLE KSSII", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BC0}"),
    ("TAMIL SYLLABLE KSSO", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BCA}"),
    ("TAMIL SYLLABLE KSSOO", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BCB}"),
    ("TAMIL SYLLABLE KSSU", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BC1}"),
    ("TAMIL SYLLABLE KSSUU", "\u{0B95}\u{0BCD}\u{0BB7}\u{0BC2}"),
    ("TAMIL SYLLABLE KU", "\u{0B95}\u{0BC1}"),
    ("TAMIL SYLLABLE KUU", "\u{0B95}\u{0BC2}"),
    ("TAMIL SYLLABLE LAA", "\u{0BB2}\u{0BBE}"),
    ("TAMIL SYLLABLE LAI", "\u{0BB2}\u{0BC8}"),
    ("TAMIL SYLLABLE LAU", "\u{0BB2}\u{0BCC}"),
    ("TAMIL SYLLABLE LE", "\u{0BB2}\u{0BC6}"),
    ("TAMIL SYLLABLE LEE", "\u{0BB2}\u{0BC7}"),
    ("TAMIL SYLLABLE LI", "\u{0BB2}\u{0BBF}"),
    ("TAMIL SYLLABLE LII", "\u{0BB2}\u{0BC0}"),
    ("TAMIL SYLLABLE LLAA", "\u{0BB3}\u{0BBE}"),
    ("TAMIL SYLLABLE LLAI", "\u{0BB3}\u{0BC8}"),
    ("TAMIL SYLLABLE LLAU", "\u{0BB3}\u{0BCC}"),
    ("TAMIL SYLLABLE LLE", "\u{0BB3}\u{0BC6}"),
    ("TAMIL SYLLABLE LLEE", "\u{0BB3}\u{0BC7}"),
    ("TAMIL SYLLABLE LLI", "\u{0BB3}\u{0BBF}"),
    ("TAMIL SYLLABLE LLII", "\u{0BB3}\u{0BC0}"),
    ("TAMIL SYLLABLE LLLAA", "\u{0BB4}\u{0BBE}"),
    ("TAMIL SYLLABLE LLLAI", "\u{0BB4}\u{0BC8}"),
    ("TAMIL SYLLABLE LLLAU", "\u{0BB4}\u{0BCC}"),
    ("TAMIL SYLLABLE LLLE", "\u{0BB4}\u{0BC6}"),
    ("TAMIL SYLLABLE LLLEE", "\u{0BB4}\u{0BC7}"),
    ("TAMIL SYLLABLE LLLI", "\u{0BB4}\u{0BBF}"),
    ("TAMIL SYLLABLE LLLII", "\u{0BB4}\u{0BC0}"),
    ("TAMIL SYLLABLE LLLO", "\u{0BB4}\u{0BCA}"),
    ("TAMIL SYLLABLE LLLOO", "\u{0BB4}\u{0BCB}"),
    ("TAMIL SYLLABLE LLLU", "\u{0BB4}\u{0BC1}"),
    ("TAMIL SYLLABLE LLLUU", "\u{0BB4}\u{0BC2}"),
    ("TAMIL SYLLABLE LLO", "\u{0BB3}\u{0BCA}"),
    ("TAMIL SYLLABLE LLOO", "\u{0BB3}\u{0BCB}"),
    ("TAMIL SYLLABLE LLU", "\u{0BB3}\u{0BC1}"),
    ("TAMIL SYLLABLE LLUU", "\u{0BB3}\u{0BC2}"),
    ("TAMIL SYLLABLE LO", "\u{0BB2}\u{0BCA}"),
    ("TAMIL SYLLABLE LOO", "\u{0BB2}\u{0BCB}"),
    ("TAMIL SYLLABLE LU", "\u{0BB2}\u{0BC1}"),
    ("TAMIL SYLLABLE LUU", "\u{0BB2}\u{0BC2}"),
    ("TAMIL SYLLABLE MAA", "\u{0BAE}\u{0BBE}"),
    ("TAMIL SYLLABLE MAI", "\u{0BAE}\u{0BC8}"),
    ("TAMIL SYLLABLE MAU", "\u{0BAE}\u{0BCC}"),
    ("TAMIL SYLLABLE ME", "\u{0BAE}\u{0BC6}"),
    ("TAMIL SYLLABLE MEE", "\u{0BAE}\u{0BC7}"),
    ("TAMIL SYLLABLE MI", "\u{0BAE}\u{0BBF}"),
    ("TAMIL SYLLABLE MII", "\u{0BAE}\u{0BC0}"),
    ("TAMIL SYLLABLE MO", "\u{0BAE}\u{0BCA}"),
    ("TAMIL SYLLABLE MOO", "\u{0BAE}\u{0BCB}"),
    ("TAMIL SYLLABLE MU", "\u{0BAE}\u{0BC1}"),
    ("TAMIL SYLLABLE MUU", "\u{0BAE}\u{0BC2}"),
    ("TAMIL SYLLABLE NAA", "\u{0BA8}\u{0BBE}"),
    ("TAMIL SYLLABLE NAI", "\u{0BA8}\u{0BC8}"),
    ("TAMIL SYLLABLE NAU", "\u{0BA8}\u{0BCC}"),
    ("TAMIL SYLLABLE NE", "\u{0BA8}\u{0BC6}"),
    ("TAMIL SYLLABLE NEE", "\u{0BA8}\u{0BC7}"),
    ("TAMIL SYLLABLE NGAA", "\u{0B99}\u{0BBE}"),
    ("TAMIL SYLLABLE NGAI", "\u{0B99}\u{0BC8}"),
    ("TAMIL SYLLABLE NGAU", "\u{0B99}\u{0BCC}"),
    ("TAMIL SYLLABLE NGE", "\u{0B99}\u{0BC6}"),
    ("TAMIL SYLLABLE NGEE", "\u{0B99}\u{0BC7}"),
    ("TAMIL SYLLABLE NGI", "\u{0B99}\u{0BBF}"),
    ("TAMIL SYLLABLE NGII", "\u{0B99}\u{0BC0}"),
    ("TAMIL SYLLABLE NGO", "\u{0B99}\u{0BCA}"),
    ("TAMIL SYLLABLE NGOO", "\u{0B99}\u{0BCB}"),
    ("TAMIL SYLLABLE NGU", "\u{0B99}\u{0BC1}"),
    ("TAMIL SYLLABLE NGUU", "\u{0B99}\u{0BC2}"),
    ("TAMIL SYLLABLE NI", "\u{0BA8}\u{0BBF}"),
    ("TAMIL SYLLABLE NII", "\u{0BA8}\u{0BC0}"),
    ("TAMIL SYLLABLE NNAA", "\u{0BA3}\u{0BBE}"),
    ("TAMIL SYLLABLE NNAI", "\u{0BA3}\u{0BC8}"),
    ("TAMIL SYLLABLE NNAU", "\u{0BA3}\u{0BCC}"),
    ("TAMIL SYLLABLE NNE", "\u{0BA3}\u{0BC6}"),
    ("TAMIL SYLLABLE NNEE", "\u{0BA3}\u{0BC7}"),
    ("TAMIL SYLLABLE NNI", "\u{0BA3}\u{0BBF}"),
    ("TAMIL SYLLABLE NNII", "\u{0BA3}\u{0BC0}"),
    ("TAMIL SYLLABLE NNNAA", "\u{0BA9}\u{0BBE}"),
    ("TAMIL SYLLABLE NNNAI", "\u{0BA9}\u{0BC8}"),
    ("TAMIL SYLLABLE NNNAU", "\u{0BA9}\u{0BCC}"),
    ("TAMIL SYLLABLE NNNE", "\u{0BA9}\u{0BC6}"),
    ("TAMIL SYLLABLE NNNEE", "\u{0BA9}\u{0BC7}"),
    ("TAMIL SYLLABLE NNNI", "\u{0BA9}\u{0BBF}"),
    ("TAMIL SYLLABLE NNNII", "\u{0BA9}\u{0BC0}"),
    ("TAMIL SYLLABLE NNNO", "\u{0BA9}\u{0BCA}"),
    ("TAMIL SYLLABLE NNNOO", "\u{0BA9}\u{0BCB}"),
    ("TAMIL SYLLABLE NNNU", "\u{0BA9}\u{0BC1}"),
    ("TAMIL SYLLABLE NNNUU", "\u{0BA9}\u{0BC2}"),
    ("TAMIL SYLLABLE NNO", "\u{0BA3}\u{0BCA}"),
    ("TAMIL SYLLABLE NNOO", "\u{0BA3}\u{0BCB}"),
    ("TAMIL SYLLABLE NNU", "\u{0BA3}\u{0BC1}"),
    ("TAMIL SYLLABLE NNUU", "\u{0BA3}\u{0BC2}"),
    ("TAMIL SYLLABLE NO", "\u{0BA8}\u{0BCA}"),
    ("TAMIL SYLLABLE NOO", "\u{0BA8}\u{0BCB}"),
    ("TAMIL SYLLABLE NU", "\u{0BA8}\u{0BC1}"),
    ("TAMIL SYLLABLE NUU", "\u{0BA8}\u{0BC2}"),
    ("TAMIL SYLLABLE NYAA", "\u{0B9E}\u{0BBE}"),
    ("TAMIL SYLLABLE NYAI", "\u{0B9E}\u{0BC8}"),
    ("TAMIL SYLLABLE NYAU", "\u{0B9E}\u{0BCC}"),
    ("TAMIL SYLLABLE NYE", "\u{0B9E}\u{0BC6}"),
    ("TAMIL SYLLABLE NYEE", "\u{0B9E}\u{0BC7}"),
    ("TAMIL SYLLABLE NYI", "\u{0B9E}\u{0BBF}"),
    ("TAMIL SYLLABLE NYII", "\u{0B9E}\u{0BC0}"),
    ("TAMIL SYLLABLE NYO", "\u{0B9E}\u{0BCA}"),
    ("TAMIL SYLLABLE NYOO", "\u{0B9E}\u{0BCB}"),
    ("TAMIL SYLLABLE NYU", "\u{0B9E}\u{0BC1}"),
    ("TAMIL SYLLABLE NYUU", "\u{0B9E}\u{0BC2}"),
    ("TAMIL SYLLABLE PAA", "\u{0BAA}\u{0BBE}"),
    ("TAMIL SYLLABLE PAI", "\u{0BAA}\u{0BC8}"),
    ("TAMIL SYLLABLE PAU", "\u{0BAA}\u{0BCC}"),
    ("TAMIL SYLLABLE PE", "\u{0BAA}\u{0BC6}"),
    ("TAMIL SYLLABLE PEE", "\u{0BAA}\u{0BC7}"),
    ("TAMIL SYLLABLE PI", "\u{0BAA}\u{0BBF}"),
    ("TAMIL SYLLABLE PII", "\u{0BAA}\u{0BC0}"),
    ("TAMIL SYLLABLE PO", "\u{0BAA}\u{0BCA}"),
    ("TAMIL SYLLABLE POO", "\u{0BAA}\u{0BCB}"),
    ("TAMIL SYLLABLE PU", "\u{0BAA}\u{0BC1}"),
    ("TAMIL SYLLABLE PUU", "\u{0BAA}\u{0BC2}"),
    ("TAMIL SYLLABLE RAA", "\u{0BB0}\u{0BBE}"),
    ("TAMIL SYLLABLE RAI", "\u{0BB0}\u{0BC8}"),
    ("TAMIL SYLLABLE RAU", "\u{0BB0}\u{0BCC}"),
    ("TAMIL SYLLABLE RE", "\u{0BB0}\u{0BC6}"),
    ("TAMIL SYLLABLE REE", "\u{0BB0}\u{0BC7}"),
    ("TAMIL SYLLABLE RI", "\u{0BB0}\u{0BBF}"),
    ("TAMIL SYLLABLE RII", "\u{0BB0}\u{0BC0}"),
    ("TAMIL SYLLABLE RO", "\u{0BB0}\u{0BCA}"),
    ("TAMIL SYLLABLE ROO", "\u{0BB0}\u{0BCB}"),
    ("TAMIL SYLLABLE RRAA", "\u{0BB1}\u{0BBE}"),
    ("TAMIL SYLLABLE RRAI", "\u{0BB1}\u{0BC8}"),
    ("TAMIL SYLLABLE RRAU", "\u{0BB1}\u{0BCC}"),
    ("TAMIL SYLLABLE RRE", "\u{0BB1}\u{0BC6}"),
    ("TAMIL SYLLABLE RREE", "\u{0BB1}\u{0BC7}"),
    ("TAMIL SYLLABLE RRI", "\u{0BB1}\u{0BBF}"),
    ("TAMIL SYLLABLE RRII", "\u{0BB1}\u{0BC0}"),
    ("TAMIL SYLLABLE RRO", "\u{0BB1}\u{0BCA}"),
    ("TAMIL SYLLABLE RROO", "\u{0BB1}\u{0BCB}"),
    ("TAMIL SYLLABLE RRU", "\u{0BB1}\u{0BC1}"),
    ("TAMIL SYLLABLE RRUU", "\u{0BB1}\u{0BC2}"),
    ("TAMIL SYLLABLE RU", "\u{0BB0}\u{0BC1}"),
    ("TAMIL SYLLABLE RUU", "\u{0BB0}\u{0BC2}"),
    ("TAMIL SYLLABLE SAA", "\u{0BB8}\u{0BBE}"),
    ("TAMIL SYLLABLE SAI", "\u{0BB8}\u{0BC8}"),
    ("TAMIL SYLLABLE SAU", "\u{0BB8}\u{0BCC}"),
    ("TAMIL SYLLABLE SE", "\u{0BB8}\u{0BC6}"),
    ("TAMIL SYLLABLE SEE", "\u{0BB8}\u{0BC7}"),
    ("TAMIL SYLLABLE SHAA", "\u{0BB6}\u{0BBE}"),
    ("TAMIL SYLLABLE SHAI", "\u{0BB6}\u{0BC8}"),
    ("TAMIL SYLLABLE SHAU", "\u{0BB6}\u{0BCC}"),
    ("TAMIL SYLLABLE SHE", "\u{0BB6}\u{0BC6}"),
    ("TAMIL SYLLABLE SHEE", "\u{0BB6}\u{0BC7}"),
    ("TAMIL SYLLABLE SHI", "\u{0BB6}\u{0BBF}"),
    ("TAMIL SYLLABLE SHII", "\u{0BB6}\u{0BC0}"),
    ("TAMIL SYLLABLE SHO", "\u{0BB6}\u{0BCA}"),
    ("TAMIL SYLLABLE SHOO", "\u{0BB6}\u{0BCB}"),
    ("TAMIL SYLLABLE SHRII", "\u{0BB6}\u{0BCD}\u{0BB0}\u{0BC0}"),
    ("TAMIL SYLLABLE SHU", "\u{0BB6}\u{0BC1}"),
    ("TAMIL SYLLABLE SHUU", "\u{0BB6}\u{0BC2}"),
    ("TAMIL SYLLABLE SI", "\u{0BB8}\u{0BBF}"),
    ("TAMIL SYLLABLE SII", "\u{0BB8}\u{0BC0}"),
    ("TAMIL SYLLABLE SO", "\u{0BB8}\u{0BCA}"),
    ("TAMIL SYLLABLE SOO", "\u{0BB8}\u{0BCB}"),
    ("TAMIL SYLLABLE SSAA", "\u{0BB7}\u{0BBE}"),
    ("TAMIL SYLLABLE SSAI", "\u{0BB7}\u{0BC8}"),
    ("TAMIL SYLLABLE SSAU", "\u{0BB7}\u{0BCC}"),
    ("TAMIL SYLLABLE SSE", "\u{0BB7}\u{0BC6}"),
    ("TAMIL SYLLABLE SSEE", "\u{0BB7}\u{0BC7}"),
    ("TAMIL SYLLABLE SSI", "\u{0BB7}\u{0BBF}"),
    ("TAMIL SYLLABLE SSII", "\u{0BB7}\u{0BC0}"),
    ("TAMIL SYLLABLE SSO", "\u{0BB7}\u{0BCA}"),
    ("TAMIL SYLLABLE SSOO", "\u{0BB7}\u{0BCB}"),
    ("TAMIL SYLLABLE SSU", "\u{0BB7}\u{0BC1}"),
    ("TAMIL SYLLABLE SSUU", "\u{0BB7}\u{0BC2}"),
    ("TAMIL SYLLABLE SU", "\u{0BB8}\u{0BC1}"),
    ("TAMIL SYLLABLE SUU", "\u{0BB8}\u{0BC2}"),
    ("TAMIL SYLLABLE TAA", "\u{0BA4}\u{0BBE}"),
    ("TAMIL SYLLABLE TAI", "\u{0BA4}\u{0BC8}"),
    ("TAMIL SYLLABLE TAU", "\u{0BA4}\u{0BCC}"),
    ("TAMIL SYLLABLE TE", "\u{0BA4}\u{0BC6}"),
    ("TAMIL SYLLABLE TEE", "\u{0BA4}\u{0BC7}"),
    ("TAMIL SYLLABLE TI", "\u{0BA4}\u{0BBF}"),
    ("TAMIL SYLLABLE TII", "\u{0BA4}\u{0BC0}"),
    ("TAMIL SYLLABLE TO", "\u{0BA4}\u{0BCA}"),
    ("TAMIL SYLLABLE TOO", "\u{0BA4}\u{0BCB}"),
    ("TAMIL SYLLABLE TTAA", "\u{0B9F}\u{0BBE}"),
    ("TAMIL SYLLABLE TTAI", "\u{0B9F}\u{0BC8}"),
    ("TAMIL SYLLABLE TTAU", "\u{0B9F}\u{0BCC}"),
    ("TAMIL SYLLABLE TTE", "\u{0B9F}\u{0BC6}"),
    ("TAMIL SYLLABLE TTEE", "\u{0B9F}\u{0BC7}"),
    ("TAMIL SYLLABLE TTI", "\u{0B9F}\u{0BBF}"),
    ("TAMIL SYLLABLE TTII", "\u{0B9F}\u{0BC0}"),
    ("TAMIL SYLLABLE TTO", "\u{0B9F}\u{0BCA}"),
    ("TAMIL SYLLABLE TTOO", "\u{0B9F}\u{0BCB}"),
    ("TAMIL SYLLABLE TTU", "\u{0B9F}\u{0BC1}"),
    ("TAMIL SYLLABLE TTUU", "\u{0B9F}\u{0BC2}"),
    ("TAMIL SYLLABLE TU", "\u{0BA4}\u{0BC1}"),
    ("TAMIL SYLLABLE TUU", "\u{0BA4}\u{0BC2}"),
    ("TAMIL SYLLABLE VAA", "\u{0BB5}\u{0BBE}"),
    ("TAMIL SYLLABLE VAI", "\u{0BB5}\u{0BC8}"),
    ("TAMIL SYLLABLE VAU", "\u{0BB5}\u{0BCC}"),
    ("TAMIL SYLLABLE VE", "\u{0BB5}\u{0BC6}"),
    ("TAMIL SYLLABLE VEE", "\u{0BB5}\u{0BC7}"),
    ("TAMIL SYLLABLE VI", "\u{0BB5}\u{0BBF}"),
    ("TAMIL SYLLABLE VII", "\u{0BB5}\u{0BC0}"),
    ("TAMIL SYLLABLE VO", "\u{0BB5}\u{0BCA}"),
    ("TAMIL SYLLABLE VOO", "\u{0BB5}\u{0BCB}"),
    ("TAMIL SYLLABLE VU", "\u{0BB5}\u{0BC1}"),
    ("TAMIL SYLLABLE VUU", "\u{0BB5}\u{0BC2}"),
    ("TAMIL SYLLABLE YAA", "\u{0BAF}\u{0BBE}"),
    ("TAMIL SYLLABLE YAI", "\u{0BAF}\u{0BC8}"),
    ("TAMIL SYLLABLE YAU", "\u{0BAF}\u{0BCC}"),
    ("TAMIL SYLLABLE YE", "\u{0BAF}\u{0BC6}"),
    ("TAMIL SYLLABLE YEE", "\u{0BAF}\u{0BC7}"),
    ("TAMIL SYLLABLE YI", "\u{0BAF}\u{0BBF}"),
    ("TAMIL SYLLABLE YII", "\u{0BAF}\u{0BC0}"),
    ("TAMIL SYLLABLE YO", "\u{0BAF}\u{0BCA}"),
    ("TAMIL SYLLABLE YOO", "\u{0BAF}\u{0BCB}"),
    ("TAMIL SYLLABLE YU", "\u{0BAF}\u{0BC1}"),
    ("TAMIL SYLLABLE YUU", "\u{0BAF}\u{0BC2}"),
];
