use Test;
plan 16;
my Int @a = 1,2,3;
my @c = @a.clone;
is @a.clone.raku, 'Array[Int].new(1, 2, 3)', 'typed Array clone keeps element type';
is @a.clone.WHAT.raku, 'Array[Int]', 'WHAT';
throws-like { @a.clone.push("x") }, X::TypeCheck, 'clone still type-checks';
my @b = 1,2; my $r = @b.clone; $r[0] = 9;
is-deeply @b, [1,2], 'clone is independent';
is [1,2].clone.raku, '[1, 2]', 'plain array';
my @d = 1,2,3; @d[1]:delete; ok @d.clone[1]:!exists, 'deleted slot preserved';
my @s[2;2]; @s[0;0] = 1; my @t := @s.clone; @t[0;0] = 9; is @s[0;0], 1, "shaped clone independent";
my Int %h = a => 1;
is %h.clone.raku, '(my Int % = :a(1))', 'typed Hash clone';
my %g = a => 1; my %k = %g.clone; %k<a> = 2; is %g<a>, 1, 'Hash independent';
is %g.clone.raku, '{:a(1)}', 'Hash raku';
is Map.new((a => 1)).clone.raku, 'Map.new((:a(1)))', 'Map';
is (a => 1).clone.raku, ':a(1)', 'Pair';
is (a => 1).clone.value, 1, 'Pair value';
my $l = <a b c>; is $l.clone.raku, '("a", "b", "c")', 'List clone is de-itemized';
ok Array.clone === Array, 'type object';
is (1,2).clone.WHAT.raku, 'List', 'List';
