pub(crate) mod expr;
mod helpers;
mod memo;
mod parse_result;
mod primary;
mod stmt;
use std::sync::OnceLock;

pub(crate) fn is_imported_function(name: &str) -> bool {
    stmt::simple::is_imported_function(name)
}

/// Parse a heredoc body string as an interpolated (qq-style) string expression.
/// Used by the compiler to defer heredoc interpolation to compile time.
pub(crate) fn interpolate_heredoc_content(content: &str) -> crate::ast::Expr {
    primary::quote_adverbs::process_content_with_flags(
        content,
        &primary::quote_adverbs::QuoteFlags::qq_double(),
    )
}

pub use stmt::simple::{clear_parser_lib_paths, set_parser_lib_paths, set_parser_program_path};

pub(crate) fn current_language_version() -> String {
    stmt::simple::current_language_version()
}

use std::cell::RefCell;

use crate::ast::Stmt;
use crate::value::RuntimeErrorCode;
use crate::value::{RuntimeError, Value};

thread_local! {
    static PARSE_WARNINGS: RefCell<Vec<String>> = const { RefCell::new(Vec::new()) };
}

/// Add a warning message during parsing. Collected and emitted after parse completes.
pub(super) fn add_parse_warning(msg: String) {
    PARSE_WARNINGS.with(|w| w.borrow_mut().push(msg));
}

/// Take and clear all parse warnings collected during the last parse.
/// Deduplicates warnings that may have been generated by parser backtracking.
pub(crate) fn take_parse_warnings() -> Vec<String> {
    let all: Vec<String> = PARSE_WARNINGS.with(|w| w.borrow_mut().drain(..).collect());
    let mut seen = std::collections::HashSet::new();
    let mut warnings = Vec::new();
    for w in all {
        if seen.insert(w.clone()) {
            warnings.push(w);
        }
    }
    warnings
}

static PARSE_MEMO_ENABLED: OnceLock<bool> = OnceLock::new();

pub(super) fn parse_memo_enabled() -> bool {
    *PARSE_MEMO_ENABLED.get_or_init(|| {
        #[cfg(not(target_arch = "wasm32"))]
        {
            std::env::var("MUTSU_PARSE_MEMO")
                .map(|v| v != "0")
                .unwrap_or(true)
        }
        #[cfg(target_arch = "wasm32")]
        {
            true
        }
    })
}

/// Invalidate all parse memo caches.  Called when a new user-declared operator
/// changes parsing behavior (e.g. circumfix, postcircumfix, prefix operators).
pub(crate) fn invalidate_all_memos() {
    if parse_memo_enabled() {
        expr::reset_expression_memo();
        primary::reset_primary_memo();
        stmt::reset_statement_memo();
    }
}

pub(crate) fn angle_word_value_full_allomorphic(word: &str) -> Value {
    primary::angle_word_value_full_allomorphic(word)
}

fn line_col_at_offset(source: &str, offset: usize) -> (usize, usize) {
    let offset = offset.min(source.len());
    let prefix = &source[..offset];
    let line = prefix.matches('\n').count() + 1;
    let col = prefix
        .rsplit('\n')
        .next()
        .map(|segment| segment.chars().count() + 1)
        .unwrap_or(1);
    (line, col)
}

fn leading_ws_bytes(input: &str) -> usize {
    input.len().saturating_sub(input.trim_start().len())
}

fn near_snippet(input: &str, max_chars: usize) -> Option<String> {
    let trimmed = input.trim_start();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.chars().take(max_chars).collect())
    }
}

fn parse_error_hint(message: &str) -> Option<&'static str> {
    if message.contains("method name") {
        Some("check method-call syntax after '.' (for example: '$obj.method').")
    } else if message.contains("identifier after '::'") {
        Some("qualified names require an identifier after each '::'.")
    } else if message.contains("after ','") {
        Some("a comma usually requires another expression or argument after it.")
    } else if message.contains("after comparison operator")
        || message.contains("after additive operator")
        || message.contains("after multiplicative operator")
    {
        Some("binary operators require a right-hand expression.")
    } else {
        None
    }
}

fn with_parse_hint(mut err: RuntimeError) -> RuntimeError {
    if let Some(hint) = parse_error_hint(&err.message) {
        err.hint = Some(hint.to_string());
    }
    err
}

/// Parse a full program using the nom-based parser.
/// Returns `(statements, Option<finish_content>)`.
#[allow(clippy::result_large_err)]
pub(crate) fn parse_program(input: &str) -> Result<(Vec<Stmt>, Option<String>), RuntimeError> {
    // Clear any stale parse warnings from previous/backtracked parses
    PARSE_WARNINGS.with(|w| w.borrow_mut().clear());
    let memo_enabled = parse_memo_enabled();
    if memo_enabled {
        expr::reset_expression_memo();
        primary::reset_primary_memo();
        stmt::reset_statement_memo();
    }
    stmt::reset_user_subs();
    crate::trace::trace_log!("parse", "parser start memo={}", memo_enabled);
    primary::set_original_source(input);
    // Split off =finish content before parsing
    let (source, finish_content) = if let Some(idx) = input.find("\n=finish") {
        let content = &input[idx + "\n=finish".len()..];
        // Skip to next newline
        let content = if let Some(nl) = content.find('\n') {
            &content[nl + 1..]
        } else {
            ""
        };
        (&input[..idx], Some(content.to_string()))
    } else {
        (input, None)
    };
    let result = match stmt::program(source) {
        Ok((rest, stmts)) => {
            let rest_trimmed = rest.trim();
            if !rest_trimmed.is_empty() {
                let consumed = source.len() - rest.len();
                let near_offset = consumed + leading_ws_bytes(rest);
                let (line_num, col_num) = line_col_at_offset(source, near_offset);
                let context: String = rest_trimmed.chars().take(60).collect();
                Err(RuntimeError::with_location(
                    format!(
                        "Confused. parse error: unparsed input at line {}, column {}: {:?}",
                        line_num, col_num, context
                    ),
                    RuntimeErrorCode::ParseUnparsed,
                    line_num,
                    col_num,
                ))
            } else {
                Ok((stmts, finish_content))
            }
        }
        Err(e) => {
            if e.is_fatal() {
                // Fatal parse errors (e.g. bare say/print/put) pass through directly
                let mut err = RuntimeError::new(format!("{}", e));
                err.code = Some(RuntimeErrorCode::ParseGeneric);
                if let Some(ex) = e.exception {
                    err.exception = Some(ex);
                }
                return Err(err);
            }
            if let Some(consumed) = e.consumed_from(source.len()) {
                let tail = &source[consumed..];
                let near_offset = consumed + leading_ws_bytes(tail);
                let (line_num, col_num) = line_col_at_offset(source, near_offset);
                if let Some(context) = near_snippet(tail, 60) {
                    Err(with_parse_hint(RuntimeError::with_location(
                        format!(
                            "Confused. parse error at line {}, column {}: {} — near: {:?}",
                            line_num, col_num, e, context
                        ),
                        RuntimeErrorCode::ParseExpected,
                        line_num,
                        col_num,
                    )))
                } else {
                    Err(with_parse_hint(RuntimeError::with_location(
                        format!(
                            "Confused. parse error at line {}, column {}: {}",
                            line_num, col_num, e
                        ),
                        RuntimeErrorCode::ParseExpected,
                        line_num,
                        col_num,
                    )))
                }
            } else {
                let mut err = RuntimeError::new(format!("Confused. parse error: {}", e));
                err.code = Some(RuntimeErrorCode::ParseGeneric);
                Err(with_parse_hint(err))
            }
        }
    };

    if memo_enabled && crate::trace::is_enabled("parse") {
        let (stmt_hits, stmt_misses, stmt_stores) = stmt::statement_memo_stats();
        let (expr_hits, expr_misses, expr_stores) = expr::expression_memo_stats();
        let (primary_hits, primary_misses, primary_stores) = primary::primary_memo_stats();
        crate::trace::trace_log!(
            "parse",
            "memo stats stmt[h/m/s]={}/{}/{} expr[h/m/s]={}/{}/{} primary[h/m/s]={}/{}/{}",
            stmt_hits,
            stmt_misses,
            stmt_stores,
            expr_hits,
            expr_misses,
            expr_stores,
            primary_hits,
            primary_misses,
            primary_stores
        );
    }

    result
}

/// Like `parse_program`, but pre-registers operator sub names so the parser
/// recognizes them during EVAL.
#[allow(clippy::result_large_err)]
pub(crate) fn parse_program_with_operators(
    input: &str,
    operator_names: &[String],
    operator_assoc: &std::collections::HashMap<String, String>,
    imported_function_names: &[String],
) -> Result<(Vec<Stmt>, Option<String>), RuntimeError> {
    // Set pre-seed operators before calling parse_program.
    // parse_program will call reset_user_subs, then we re-register after.
    stmt::set_eval_operator_preseed(operator_names.to_vec());
    stmt::set_eval_operator_assoc_preseed(operator_assoc.clone());
    stmt::set_eval_imported_function_preseed(imported_function_names.to_vec());
    let result = parse_program(input);
    stmt::set_eval_operator_preseed(Vec::new());
    stmt::set_eval_operator_assoc_preseed(std::collections::HashMap::new());
    stmt::set_eval_imported_function_preseed(Vec::new());
    result
}

/// Like `parse_program_partial`, but pre-registers operator sub names so the
/// parser recognizes them during EVAL.  Used to extract BEGIN phasers from
/// code that fails to parse completely.
pub(crate) fn parse_program_partial_with_operators(
    input: &str,
    operator_names: &[String],
    operator_assoc: &std::collections::HashMap<String, String>,
    imported_function_names: &[String],
) -> (Vec<Stmt>, Option<String>) {
    stmt::set_eval_operator_preseed(operator_names.to_vec());
    stmt::set_eval_operator_assoc_preseed(operator_assoc.clone());
    stmt::set_eval_imported_function_preseed(imported_function_names.to_vec());
    let result = parse_program_partial(input);
    stmt::set_eval_operator_preseed(Vec::new());
    stmt::set_eval_operator_assoc_preseed(std::collections::HashMap::new());
    stmt::set_eval_imported_function_preseed(Vec::new());
    result
}

/// Best-effort parse: returns all statements that could be parsed before the
/// first error.  Used for loading `.rakumod` modules that may contain syntax
/// mutsu does not yet support.
pub(crate) fn parse_program_partial(input: &str) -> (Vec<Stmt>, Option<String>) {
    let memo_enabled = parse_memo_enabled();
    if memo_enabled {
        expr::reset_expression_memo();
        primary::reset_primary_memo();
        stmt::reset_statement_memo();
    }
    stmt::reset_user_subs();
    primary::set_original_source(input);
    let (source, finish_content) = if let Some(idx) = input.find("\n=finish") {
        let content = &input[idx + "\n=finish".len()..];
        let content = if let Some(nl) = content.find('\n') {
            &content[nl + 1..]
        } else {
            ""
        };
        (&input[..idx], Some(content.to_string()))
    } else {
        (input, None)
    };
    let (stmts, _) = stmt::stmt_list_partial(source);
    (stmts, finish_content)
}

#[cfg(test)]
mod tests {
    use super::parse_program;
    use crate::ast::{Expr, Stmt};
    use crate::value::RuntimeErrorCode;

    #[test]
    fn parse_program_reports_line_and_column_for_unparsed_input() {
        let err = parse_program("}").unwrap_err();
        assert!(err.message.contains("line 1, column 1"));
        assert!(err.message.contains("unparsed input"));
        assert!(matches!(err.code, Some(RuntimeErrorCode::ParseUnparsed)));
        assert_eq!(err.line, Some(1));
        assert_eq!(err.column, Some(1));
    }

    #[test]
    fn parse_program_reports_line_and_column_for_parse_error() {
        let err = parse_program("say 1;\nok(,)").unwrap_err();
        assert!(err.message.contains("line 2"));
        assert!(err.message.contains("column"));
        assert!(err.message.contains("parse error"));
        assert!(matches!(err.code, Some(RuntimeErrorCode::ParseExpected)));
        assert_eq!(err.line, Some(2));
    }

    #[test]
    fn parse_program_unparsed_column_skips_leading_whitespace() {
        let err = parse_program("say 1;\n   }").unwrap_err();
        assert!(err.message.contains("line 2, column 4"));
    }

    #[test]
    fn parse_program_includes_hint_for_common_method_error() {
        let err = parse_program("$x.").unwrap_err();
        assert!(err.message.contains("parse error"));
        assert!(
            err.hint
                .as_deref()
                .is_some_and(|hint| hint.contains("method-call syntax"))
        );
    }

    #[test]
    fn parse_program_accepts_corner_bracket_string_in_listop_call() {
        let src = "sub f($a, $b, $c) { }\nf ｢say 42｣, {:out(\"ok\")}, 'msg';";
        let (stmts, _) = parse_program(src).unwrap();
        assert_eq!(stmts.len(), 2);
        match &stmts[1] {
            Stmt::Expr(Expr::Call { name, args }) => {
                assert_eq!(name, "f");
                assert_eq!(args.len(), 3);
                assert!(
                    matches!(&args[0], Expr::Literal(crate::value::Value::Str(s)) if s.as_str() == "say 42")
                );
                assert!(matches!(&args[1], Expr::Hash(_)));
                assert!(
                    matches!(&args[2], Expr::Literal(crate::value::Value::Str(s)) if s.as_str() == "msg")
                );
            }
            other => panic!("expected function call expression, got {other:?}"),
        }
    }

    #[test]
    fn parse_program_accepts_french_quote_word_list() {
        let src = "my @target = $*DISTRO.is-win ?? «/c \"\"» !! '/dev/null';";
        let (stmts, _) = parse_program(src).unwrap();
        assert_eq!(stmts.len(), 1);
    }

    #[test]
    fn parse_program_accepts_double_angle_quote_word_list_with_quoted_word() {
        let src = "my @str = <<do gjump sover \"\\r\\nth\" elaz yfo x>>;";
        let (stmts, _) = parse_program(src).unwrap();
        assert_eq!(stmts.len(), 1);
        let Stmt::VarDecl { expr, .. } = &stmts[0] else {
            panic!("expected VarDecl")
        };
        let items = match expr {
            Expr::ArrayLiteral(items) => items,
            Expr::Call { name, args } if name.resolve() == "list" => args,
            _ => panic!("expected list expression"),
        };
        assert_eq!(items.len(), 7);
        assert!(matches!(
            &items[3],
            Expr::Literal(crate::value::Value::Str(s)) if s.as_str() == "\r\nth"
        ));
    }

    #[test]
    fn parse_program_accepts_french_quote_word_list_with_interpolation() {
        let src =
            r#"subtest 'x' => { with Proc::Async.new: «"$*EXECUTABLE" -e "print 'ok'"» { } };"#;
        let (stmts, _) = parse_program(src).unwrap();
        assert_eq!(stmts.len(), 1);
    }

    #[test]
    fn parse_program_does_not_bind_with_statement_across_newline_as_modifier() {
        let src = r#"
{
    my $proc = Proc::Async.new($*EXECUTABLE, '-e', '$*OUT.write(Blob.new(65, 66, 67, 13, 10))');
    my $result = '';
    $proc.stdout.tap({ $result ~= $_ });
    await $proc.start;
}
with Proc::Async.new: :out, ($*EXECUTABLE, '-e'), 'say "pass"' {
    .stdout.tap: { }
}
"#;
        let (stmts, _) = parse_program(src).unwrap();
        assert_eq!(stmts.len(), 2);
    }

    #[test]
    fn parse_program_accepts_unicode_single_quoted_regex_atoms() {
        let src = r#"
	ok("ab/cd" ~~ m/ab ‘/’ c d/, "curly single quote");
	ok("ab/cd" ~~ m/ab ‚/’ c d/, "low-high single quote");
	ok("ab/cd" ~~ m/ab ‚/‘ c d/, "low-curly single quote");
	ok("ab/cd" ~~ m/ab ｢/｣ c d/, "corner quote");
	"#;
        let (stmts, _) = parse_program(src).unwrap();
        assert_eq!(stmts.len(), 4);
    }

    #[test]
    fn parse_program_accepts_unicode_and_ascii_minus_angle_complex_in_is_deeply() {
        let src = "use Test;\nis-deeply −<42+2i>, -<42+2i>, 'prefix, Complex';";
        let (stmts, _) = parse_program(src).unwrap();
        assert_eq!(stmts.len(), 2);
    }

    #[test]
    fn parse_program_accepts_test_call_with_bracket_metaop_assign_argument() {
        let src = r#"use Test; my $y = 5; is $y [R/]= 1, 1/5, "[R/]= works correctly (1)";"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }

    #[test]
    fn parse_program_accepts_reverse_roast_block() {
        let src = r#"
use Test;
{
    my $y = 5;
    is $y [R/]= 1, 1/5, '[R/]= works correctly (1)';
    sub r2cf(Rat $x is copy) {
        gather $x [R/]= 1 while ($x -= take $x.floor) > 0
    }
}
"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }

    #[test]
    fn parse_program_accepts_q_to_quoted_delim_inside_call_then_method() {
        let src = r#"
my @precompiled = Test::Util::run( "use lib x\n" ~ q:to"--END--").lines;
    for <C A B> {
        say 1;
    }
    --END--
say @precompiled.elems;
"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }

    #[test]
    fn parse_program_accepts_listop_q_concat_argument_for_user_sub() {
        let src = r#"
sub is_run($a, $b, $c) { }
is_run q<use lib '> ~ $pkg-path ~ q<'; use GH2897-B; (^3).map( { my-counter } ).join(",").print>,
       { :err(''), :out('0,1,2'), :status => 0 },
       'closure is preserved after deserialzation';
"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }

    #[test]
    fn parse_program_accepts_named_sub_literal_in_statement_modifier_for_argument() {
        let src = r#"use Test; is ((sub r { "OH HAI" })() for 5), "OH HAI";"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }

    #[test]
    fn parse_program_accepts_named_sub_literal_with_traits_in_expression_context() {
        let src = r#"my &f = sub named is rw { 42 }; say f();"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }

    #[test]
    fn parse_program_accepts_postfix_for_after_hash_index_default_assign() {
        let src = r#"my @a = <a b c>; my %h; %h{.value} //= .key for @a.pairs;"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }

    #[test]
    fn parse_program_rejects_explicit_do_block_with_postfix_for() {
        let src = r#"my $i; do { $i++ } for 1..3;"#;
        let err = parse_program(src).expect_err("expected do...for parse error");
        assert!(err.message.contains("X::Obsolete"), "{err:?}");
    }

    #[test]
    fn parse_program_accepts_leading_dot_decimal_with_postfix_and_method_in_listop_args() {
        let src = r#"use Test; sub postfix:<R>($x) { $x.FatRat }; isa-ok .88888888888R.WHAT, FatRat, 'leading-dot decimal with postfix/method in args';"#;
        let parsed = parse_program(src);
        assert!(parsed.is_ok(), "{parsed:?}");
    }
}
