//! The value (non-type) names the CORE setting declares, as RakuAST resolves
//! a bareword.
//!
//! Rakudo resolves a bareword against the setting at parse time: a setting
//! enum value (`Less`, `Kept`) renders as `Term::Enum`, any other defined
//! symbol (`IterationEnd`, `Order::Less`, `SIGINT`) as `Term::Name`.
//! `core_term_names.txt` records which node rakudo's own `.AST` answers for
//! each name; it is generated by `scripts/gen-core-term-names.raku`, so
//! regenerate it rather than editing it. The type names are the companion
//! list in `core_type_names`.

use std::collections::HashMap;
use std::sync::LazyLock;

/// The node a setting term renders as.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum TermKind {
    /// `RakuAST::Term::Enum.from-identifier(...)`.
    Enum,
    /// `RakuAST::Term::Name.new(...)`.
    Name,
}

static NAMES: LazyLock<HashMap<&'static str, TermKind>> = LazyLock::new(|| {
    include_str!("core_term_names.txt")
        .lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|l| {
            let (node, name) = l.split_once('\t')?;
            let kind = match node {
                "Term::Enum" => TermKind::Enum,
                "Term::Name" => TermKind::Name,
                _ => return None,
            };
            Some((name, kind))
        })
        .collect()
});

/// The node the setting term `name` renders as, or `None` when the setting
/// declares no such term.
// Cost: O(k), k = length of `name` (one hash lookup; the map is built once).
pub(super) fn kind(name: &str) -> Option<TermKind> {
    NAMES.get(name).copied()
}

#[cfg(test)]
mod tests {
    use super::{TermKind, kind};

    #[test]
    fn knows_setting_terms_and_not_types() {
        assert_eq!(kind("Less"), Some(TermKind::Enum));
        assert_eq!(kind("Kept"), Some(TermKind::Enum));
        assert_eq!(kind("IterationEnd"), Some(TermKind::Name));
        assert_eq!(kind("Order::Less"), Some(TermKind::Name));
        // A type is the other list's business.
        assert_eq!(kind("Int"), None);
        assert_eq!(kind("NoSuchTerm"), None);
    }
}
