use crate::token_kind::TokenKind;

/// Convert a `TokenKind` to its operator name string for runtime dispatch.
pub(crate) fn token_kind_to_op_name(op: &TokenKind) -> String {
    match op {
        TokenKind::Ident(name) => name.clone(),
        TokenKind::Plus => "+".to_string(),
        TokenKind::Minus => "-".to_string(),
        TokenKind::Star => "*".to_string(),
        TokenKind::StarStar => "**".to_string(),
        TokenKind::Slash => "/".to_string(),
        TokenKind::Percent => "%".to_string(),
        TokenKind::Tilde => "~".to_string(),
        TokenKind::Bang => "!".to_string(),
        TokenKind::Question => "?".to_string(),
        TokenKind::Caret => "^".to_string(),
        TokenKind::Ampersand => "&".to_string(),
        TokenKind::Pipe => "|".to_string(),
        TokenKind::Comma => ",".to_string(),
        TokenKind::EqEq => "==".to_string(),
        TokenKind::BangEq => "!=".to_string(),
        TokenKind::Lt => "<".to_string(),
        TokenKind::Lte => "<=".to_string(),
        TokenKind::Gt => ">".to_string(),
        TokenKind::Gte => ">=".to_string(),
        TokenKind::AndAnd => "&&".to_string(),
        TokenKind::OrOr => "||".to_string(),
        TokenKind::XorXor => "^^".to_string(),
        TokenKind::SmartMatch => "~~".to_string(),
        TokenKind::BangTilde => "!~".to_string(),
        TokenKind::LtEqGt => "<=>".to_string(),
        TokenKind::EqEqEq => "===".to_string(),
        TokenKind::BangEqEqEq => "!===".to_string(),
        TokenKind::DotDot => "..".to_string(),
        TokenKind::DotDotDot => "...".to_string(),
        TokenKind::BitAnd => "+&".to_string(),
        TokenKind::BitOr => "+|".to_string(),
        TokenKind::BitXor => "+^".to_string(),
        TokenKind::BitShiftLeft => "+<".to_string(),
        TokenKind::BitShiftRight => "+>".to_string(),
        TokenKind::StrBitAnd => "~&".to_string(),
        TokenKind::StrBitOr => "~|".to_string(),
        TokenKind::StrBitXor => "~^".to_string(),
        TokenKind::StrShiftLeft => "~<".to_string(),
        TokenKind::StrShiftRight => "~>".to_string(),
        TokenKind::BoolBitAnd => "?&".to_string(),
        TokenKind::BoolBitOr => "?|".to_string(),
        TokenKind::BoolBitXor => "?^".to_string(),
        TokenKind::IntBitNeg => "+^".to_string(),
        TokenKind::BoolBitNeg => "?^".to_string(),
        TokenKind::StrBitNeg => "~^".to_string(),
        TokenKind::PercentPercent => "%%".to_string(),
        TokenKind::BangPercentPercent => "!%%".to_string(),
        TokenKind::SlashSlash => "//".to_string(),
        TokenKind::OrElse => "orelse".to_string(),
        TokenKind::AndThen => "andthen".to_string(),
        TokenKind::NotAndThen => "notandthen".to_string(),
        TokenKind::OrWord => "or".to_string(),
        TokenKind::AndWord => "and".to_string(),
        TokenKind::BangBang => "!!".to_string(),
        TokenKind::QuestionQuestion => "??".to_string(),
        TokenKind::SetUnion => "(|)".to_string(),
        TokenKind::SetAddition => "(+)".to_string(),
        TokenKind::SetIntersect => "(&)".to_string(),
        TokenKind::SetMultiply => "(.)".to_string(),
        TokenKind::SetDiff => "(-)".to_string(),
        TokenKind::SetSymDiff => "(^)".to_string(),
        TokenKind::SetElem => "(elem)".to_string(),
        TokenKind::SetCont => "(cont)".to_string(),
        TokenKind::SetSubset => "(<=)".to_string(),
        TokenKind::SetSuperset => "(>=)".to_string(),
        TokenKind::SetStrictSubset => "(<)".to_string(),
        TokenKind::SetStrictSuperset => "(>)".to_string(),
        TokenKind::PlusPlus => "++".to_string(),
        TokenKind::MinusMinus => "--".to_string(),
        _ => format!("{:?}", op),
    }
}

/// Reverse of [`token_kind_to_op_name`] for the common infix operators, used to
/// lower a `RakuAST::Infix("...")` back to a `TokenKind` (ADR-0011 Phase 5).
/// Returns `None` for operators not yet handled by the RakuAST lowerer.
pub(crate) fn op_name_to_token_kind(name: &str) -> Option<TokenKind> {
    Some(match name {
        "+" => TokenKind::Plus,
        "-" => TokenKind::Minus,
        "*" => TokenKind::Star,
        "**" => TokenKind::StarStar,
        "/" => TokenKind::Slash,
        "%" => TokenKind::Percent,
        "%%" => TokenKind::PercentPercent,
        "~" => TokenKind::Tilde,
        "==" => TokenKind::EqEq,
        "!=" => TokenKind::BangEq,
        "<" => TokenKind::Lt,
        "<=" => TokenKind::Lte,
        ">" => TokenKind::Gt,
        ">=" => TokenKind::Gte,
        "<=>" => TokenKind::LtEqGt,
        "===" => TokenKind::EqEqEq,
        "&&" => TokenKind::AndAnd,
        "||" => TokenKind::OrOr,
        "^^" => TokenKind::XorXor,
        "//" => TokenKind::SlashSlash,
        ".." => TokenKind::DotDot,
        "..." => TokenKind::DotDotDot,
        // Prefix-only operators (`!$x`, `?$x`). The prefixes shared with an infix
        // spelling (`-`/`+`/`~`) already map above.
        "!" => TokenKind::Bang,
        "?" => TokenKind::Question,
        "~~" => TokenKind::SmartMatch,
        // `x => 5` — the pair constructor renders with its Debug name (there is
        // no `=>` spelling in `token_kind_to_op_name`).
        "FatArrow" => TokenKind::FatArrow,
        // Any remaining operator name is a named infix (`x`, `xx`, `eq`, `ne`,
        // `lt`/`gt`/`le`/`ge`, `cmp`, `leg`, `div`, `mod`, ...), which mutsu
        // represents with a generic `Ident` token (the inverse of
        // `token_kind_to_op_name`'s `Ident(name) => name`).
        name => TokenKind::Ident(name.to_string()),
    })
}
