use Test;

plan 7;

# Hyper prefix operators are autogenerated and callable as named functions.
is prefix:<-«>((2, 3, 4)).gist, '(-2 -3 -4)', 'prefix:<-«> direct';
{
    my &pre = &prefix:<-«>;
    is pre((2, 3, 4)).gist, '(-2 -3 -4)', '&prefix:<-«> via ref';
}
is prefix:<-«>((2, (3, 4))).gist, '(-2 (-3 -4))', 'prefix:<-«> recurses into nested lists';
is prefix:<?«>((0, 1, 2)).gist, '(False True True)', 'prefix:<?«> boolifies element-wise';

# Hyper postfix operators.
is postfix:<»i>((2, 3, 4)).gist, '(0+2i 0+3i 0+4i)', 'postfix:<»i> direct';
{
    my &post = &postfix:<»i>;
    is post((2, 3)).gist, '(0+2i 0+3i)', '&postfix:<»i> via ref';
}

# <<...>> ASCII forms.
is prefix:<-<<>((1, 2)).gist, '(-1 -2)', 'prefix:<-<<> ASCII form';
