use Test;

plan 8;

{
    sub auto-both { @_[0] ~ %_<x> }
    my @params = &auto-both.signature.params;
    is +@params, 2, 'autogenerated positional and named slurpy params';
    ok @params[0].multi-invocant, 'autogenerated positional is multi-invocant';
    ok @params[1].multi-invocant, 'autogenerated named is multi-invocant';
}

{
    sub none(;; $a) { }
    my @params = &none.signature.params;
    is +@params, 1, 'single non-multi-invocant param after ;;';
    nok @params[0].multi-invocant, 'param after ;; is not multi-invocant';
}

{
    sub exclude($a;; $b, :$c) { }
    my @params = &exclude.signature.params;
    ok @params[0].multi-invocant, 'param before ;; remains multi-invocant';
    nok @params[1].multi-invocant, 'second positional after ;; is not multi-invocant';
    nok @params[2].multi-invocant, 'named param after ;; is not multi-invocant';
}
