use Test;

# Test count is driven by `done-testing` at the end: several assertions are
# generated by `for` loops over the coercion method names.

# ---------------------------------------------------------------------------
# Str numeric coercions return a Failure for a non-numeric string.
# `.Rat` used to fall back to 0/1 while `.Int`/`.Num`/`.Complex`/`.FatRat`
# already produced the lazy X::Str::Numeric Failure.
# ---------------------------------------------------------------------------

for <Rat Int Num Complex FatRat> -> $meth {
    my $r = "foo"."$meth"();
    isa-ok $r, Failure, "'foo'.$meth returns a Failure";
    ok !$r.defined, "'foo'.$meth is undefined";
    is $r.exception.^name, 'X::Str::Numeric',
        "'foo'.$meth carries an X::Str::Numeric";
}

# A string that starts numeric but has trailing junk fails too.
for <Rat Int Num> -> $meth {
    my $r = "12abc"."$meth"();
    isa-ok $r, Failure, "'12abc'.$meth returns a Failure";
    $r.so;   # mark handled
}

# A Failure is falsy and stays handled once tested.
{
    my $r = "foo".Rat;
    nok $r.so, "'foo'.Rat is falsy via .so";
    nok $r.Bool, "'foo'.Rat is falsy via .Bool";
}

# Using an unhandled Failure throws.
dies-ok { my $x = "foo".Rat; say $x }, 'saying an unhandled Failure throws';

# The empty and whitespace-only strings are NOT failures: they numify to zero.
is "".Rat, 0, '"".Rat is 0';
is "   ".Rat, 0, '"   ".Rat is 0';
ok "".Rat.defined, '"".Rat is defined';
is "3.14".Rat, 3.14, '"3.14".Rat parses';
is " 42 ".Rat, 42, '" 42 ".Rat trims and parses';
is "1/4".Rat, 0.25, '"1/4".Rat parses a fraction';

# ---------------------------------------------------------------------------
# Str.match's :x adverb validates its value's type.
# ---------------------------------------------------------------------------

{
    my $r = "foobar".match("o", :x<hello>);
    isa-ok $r, Failure, 'an invalid :x yields a Failure from .match';
    is $r.exception.^name, 'X::Str::Match::x', 'the exception is X::Str::Match::x';
    is $r.exception.message,
        'in Str.match, got invalid value of type Str for :x, must be Int or Range',
        'the X::Str::Match::x message names the offending type';
    $r.so;   # mark handled
}

# A List is equally invalid.
{
    my $r = "foobar".match("o", :x($(1, 2)));
    isa-ok $r, Failure, 'a List :x yields a Failure too';
    $r.so;
}

# .subst throws instead of returning a Failure, but reports the same class.
throws-like { "foooobar".subst("o", "X", :x<hello>) }, X::Str::Match::x,
    '.subst throws X::Str::Match::x for an invalid :x';

# Valid :x values still work: Int, Range, Whatever, a numeric allomorph,
# a Bool and a fractional Real (truncated toward zero).
is "foooobar".match("o", :x(2)).elems, 2, ':x(Int) selects that many matches';
is "foooobar".match("o", :x(1..2)).elems, 2, ':x(Range) selects within bounds';
is "foooobar".match("o", :x(*)).elems, 4, ':x(*) selects them all';
is "foooobar".match("o", :x(<2>)).elems, 2, ':x(IntStr allomorph) is accepted';
is "foooobar".match("o", :x(True)).elems, 1, ':x(True) counts as 1';
is "foooobar".match("o", :x(2.0)).elems, 2, ':x(2.0) counts as 2';
is "foooobar".match("o", :x(1.5)).elems, 1, ':x(1.5) truncates to 1';

# ---------------------------------------------------------------------------
# printf: the method form, and Junction autothreading of the sub form.
# `printf` writes to $*OUT, so redirect it to a file to keep the TAP stream
# clean and to be able to assert on what was written.
# ---------------------------------------------------------------------------

ok Str.^can('printf'), 'printf is available as a method on Str';

my $capture = $*TMPDIR.add("mutsu-printf-capture-{$*PID}.txt");
my $fmt = "%s is %s";
my $method-result;
my $junction-result;
{
    my $fh = open($capture, :w);
    {
        my $*OUT = $fh;
        $method-result = $fmt.printf("thor", "mighty");
        $junction-result = printf("[%d]", 1 | 2);
    }
    $fh.close;
}
my $written = slurp($capture);
unlink $capture;

ok $method-result, 'the .printf method form returns a true value';
ok $written.starts-with("thor is mighty"),
    'the .printf method form writes the formatted string';
isa-ok $junction-result, Junction,
    'printf autothreads a single Junction argument';
is $written.substr("thor is mighty".chars).comb(/\d/).sort.join, "12",
    'printf ran the format once per Junction eigenstate';

# A Junction *format* autothreads through the Str(Cool) coercion in
# sprintf, giving a Junction of formatted strings.
{
    my $r = sprintf("%s" | "[%s]", 5);
    isa-ok $r, Junction, 'sprintf autothreads a Junction format';
    ok ($r eqv any("5", "[5]")), 'the Junction format threads per eigenstate';
}

# sprintf does NOT autothread a Junction *argument* - the slurpy is untyped,
# so the directive rejects it.
dies-ok { sprintf("%d", 1 | 2) }, 'sprintf does not autothread a Junction argument';

# ---------------------------------------------------------------------------
# Str.comb's named-only forms dispatch.
# ---------------------------------------------------------------------------

is "abc".comb.elems, 3, '.comb with no arguments';
is "abc".comb(:match).elems, 3, '.comb(:match) dispatches (named-arg-only call)';
is-deeply "abc".comb(:match).map(*.Str).List, ("a", "b", "c"),
    '.comb(:match) with no matcher still yields the graphemes';
is "abc".comb(:match, 2).elems, 2, '.comb(:match, $limit) honours the limit';
is "abc123def".comb(/\d/, :match).map(*.Str).join(","), "1,2,3",
    '.comb($matcher, :match) returns the matched text';
ok "abc123def".comb(/\d/, :match).head ~~ Match,
    '.comb($matcher, :match) yields Match objects';

# ---------------------------------------------------------------------------
# A user class `is Str` inherits the native string payload.
# ---------------------------------------------------------------------------

{
    my class Foo is Str { }
    my $x = Foo.new(:value("hi"));
    is $x.Str, "hi", 'an is-Str subclass stringifies to its :value payload';
    is $x.gist, "hi", 'an is-Str subclass gists to its payload';
    is "v=$x", "v=hi", 'an is-Str subclass interpolates as its payload';
    is $x.chars, 2, 'native Str methods see the payload';
    is $x.uc, "HI", '.uc runs on the payload';
    ok $x eq "hi", 'string comparison uses the payload';
    is $x.raku, '"hi"', '.raku renders the payload';
    is $x.^name, 'Foo', 'the subclass keeps its own name';

    my $empty = Foo.new;
    is $empty.Str, "", 'a payload-less is-Str subclass is the empty string';
    is $empty.chars, 0, 'and has zero chars';
}

done-testing;
