#!/usr/bin/env python3
"""Turn dist-compat-sweep TSV rows into a deduped, impact-ordered ticket queue.

The sweep (scripts/dist-compat-sweep.py) emits one TSV row per dist with a
bucket (parse_error / runtime_error / test_die / test_fail / ...) and a detail
line whose leading text is a root-cause signature. Many dists share the SAME
root cause, so we group by a normalized signature, count how many dists each
covers, and write a two-ended work-queue document ordered by impact.

Usage:
  scripts/dist-compat-tickets.py TSV [TSV ...] [--out TODO_dist/TICKETS.md]
  scripts/dist-compat-tickets.py --print TSV      # signature table to stdout

The queue is meant to be worked from BOTH ends: the primary takes tickets from
the top (highest impact), other workers take from the bottom (the long tail).
Claim a ticket by adding a `[claim: <branch>]` marker and pushing before you
start; move it to Done when the PR merges.
"""
import argparse, collections, re, sys

# Buckets that represent a real mutsu gap worth a ticket (not missing deps, not
# skipped guts/native, not a raku-side failure).
TICKET_BUCKETS = {"parse_error", "runtime_error", "test_die", "test_fail", "panic"}


def signature(bucket, detail):
    """Normalize a detail line into a coarse root-cause signature so that dists
    failing the same way cluster together."""
    s = detail
    # Drop a leading "Module: " / "t/file.t: " prefix.
    s = re.sub(r"^[\w:./-]+?:\s+", "", s)
    # Drop the sweep's own count prefix on test rows ("base=.. pass=.. | ...").
    s = re.sub(r"^base=\d+ pass=\d+ fail=\d+ die=\d+\s*\|\s*", "", s)
    s = re.sub(r"^[\w:./-]+?:\s+", "", s)  # a second file prefix inside the detail
    # Collapse volatile specifics so similar errors merge.
    s = re.sub(r"'[^']*'", "'X'", s)             # quoted strings
    s = re.sub(r'"[^"]*"', '"X"', s)
    s = re.sub(r"\bline \d+\b", "line N", s)
    s = re.sub(r"\b\d+\b", "N", s)               # bare numbers
    s = re.sub(r"(method|routine|symbol|attribute)\s+\S+", r"\1 X", s, flags=re.I)
    s = s.strip()[:120]
    return f"{bucket}: {s}" if s else bucket


def load_rows(paths):
    rows = []
    for p in paths:
        with open(p) as f:
            header = f.readline()
            for line in f:
                parts = line.rstrip("\n").split("\t")
                if len(parts) < 5:
                    continue
                dist, ver, bucket, detail, axis = parts[:5]
                rows.append((dist, ver, bucket, detail, axis))
    return rows


def build_tickets(rows):
    # dist -> its worst ticketable row (die > fail > parse > runtime > panic order
    # is not critical; we key clusters by signature and just collect dists).
    clusters = collections.defaultdict(lambda: {"dists": set(), "examples": []})
    for dist, ver, bucket, detail, axis in rows:
        if bucket not in TICKET_BUCKETS:
            continue
        sig = signature(bucket, detail)
        # A bare-bucket signature (no useful error text — e.g. a "silent" test
        # death that emitted only TAP-harness noise) carries no shared root
        # cause, so DON'T merge those: key them per-dist to keep them as separate
        # investigation tickets rather than one misleading mega-cluster.
        key = sig if ": " in sig else f"{sig} [{dist}]"
        c = clusters[key]
        c["dists"].add(dist)
        if len(c["examples"]) < 3:
            c["examples"].append((dist, detail))
    tickets = []
    for sig, c in clusters.items():
        tickets.append({
            "sig": sig,
            "n": len(c["dists"]),
            "dists": sorted(c["dists"]),
            "examples": c["examples"],
        })
    tickets.sort(key=lambda t: (-t["n"], t["sig"]))
    return tickets


def render(tickets):
    out = []
    out.append("# Dist-compat tickets (two-ended work queue)\n")
    out.append(
        "Generated by `scripts/dist-compat-tickets.py` from dist-compat-sweep TSVs.\n"
        "Each ticket is one **root cause** shared by one or more dists, ordered by\n"
        "impact (number of dists it unblocks).\n\n"
        "**How to work this queue:** the primary takes tickets from the **top**\n"
        "(highest impact); other workers take from the **bottom** (the long tail),\n"
        "so the two ends meet in the middle without colliding. To claim a ticket,\n"
        "add a `[claim: <branch>]` marker on its heading and push before you start.\n"
        "Move a ticket to **Done** when its PR merges. Rebase on `main` before\n"
        "editing this file; keep edits small (one ticket) to avoid conflicts.\n"
    )
    out.append(f"\n_{len(tickets)} open tickets._\n")
    out.append("\n## Open\n")
    for i, t in enumerate(tickets, 1):
        out.append(f"\n### T-{i:03d} — {t['sig']}  [impact: {t['n']} dist{'s' if t['n'] != 1 else ''}]\n")
        out.append(f"- dists: {', '.join(t['dists'][:12])}"
                   + (" …" if len(t['dists']) > 12 else "") + "\n")
        for dist, detail in t["examples"]:
            out.append(f"- e.g. `{dist}`: {detail[:160]}\n")
        out.append("- repro: _(fill in a minimal repro + raku baseline before fixing)_\n")
        out.append("- file: _(suspected parser/runtime file)_\n")
    out.append("\n## Claimed\n\n_(move tickets here with `[claim: <branch>]` when you start)_\n")
    out.append("\n## Done\n\n_(move tickets here when the PR merges; note the PR number)_\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", nargs="+")
    ap.add_argument("--out", default="TODO_dist/TICKETS.md")
    ap.add_argument("--print", dest="print_only", action="store_true")
    args = ap.parse_args()
    rows = load_rows(args.tsv)
    tickets = build_tickets(rows)
    if args.print_only:
        for i, t in enumerate(tickets, 1):
            print(f"T-{i:03d}  n={t['n']:3}  {t['sig']}")
        print(f"\n{len(tickets)} tickets from {len(rows)} rows", file=sys.stderr)
        return
    import os
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write(render(tickets))
    print(f"wrote {len(tickets)} tickets -> {args.out}")


if __name__ == "__main__":
    main()
