#!/usr/bin/env raku
# Prints the candidates of Rakudo's core routines: the data behind
# `&say.candidates`, `Str.^can("Int")[0].candidates`, `.cando`, `.file` and
# `.line` of a built-in (#12472).
#
# Tab-separated, one candidate per line:
#
#   sub<TAB>name<TAB>multi<TAB>file<TAB>line<TAB>signature
#   method<TAB>Owner<TAB>name<TAB>multi<TAB>file<TAB>line<TAB>signature
#
# `sub` rows are the `&`-routines of `CORE::`; `method` rows are the entries of
# `::(Owner).^method_table` for every owner `rakudo_method_tables.txt` names
# (a multi method contributes one row per candidate, an `only` method one).
# `signature` is `Signature.raku` as Rakudo prints it. Regenerate with
#
#   raku scripts/gen-rakudo-candidates.raku > src/builtins/rakudo_candidates.txt
#
# whenever the vendored Rakudo moves.

sub clean(Str $s) { $s.subst(/\s+/, ' ', :g) }

sub emit(@lead, Mu $r) {
    return unless $r ~~ Routine;
    my @cands = ($r.can("is_dispatcher") && $r.is_dispatcher) ?? $r.candidates !! ($r,);
    for @cands -> Mu $c {
        my $file = try { $c.file } // '';
        my $line = try { $c.line } // 0;
        my $sig  = try { clean($c.signature.raku) } // next;
        say join "\t", |@lead, (($c.can("multi") && $c.multi) ?? 1 !! 0), $file, $line, $sig;
    }
}

say "# Rakudo core routine candidates, generated by scripts/gen-rakudo-candidates.raku on rakudo {$*RAKU.compiler.version}";

for CORE::.keys.sort -> $k {
    next unless $k.starts-with('&');
    my $r = CORE::{$k};
    next unless $r ~~ Routine;
    emit(('sub', $k.substr(1)), $r);
}

my $tables = $*PROGRAM.parent.parent.add('src/builtins/rakudo_method_tables.txt');
my @owners = $tables.lines.grep(*.starts-with('declared' ~ "\t")).map(*.split("\t")[1]).unique.sort;
for @owners -> $owner {
    my $type := try ::($owner);
    next if $owner.starts-with("Metamodel::");
    next without $type.HOW;
    next unless $type.HOW ~~ Metamodel::ClassHOW | Metamodel::EnumHOW;
    my %mt = try { $type.^method_table } // next;
    for %mt.keys.sort -> $name {
        emit(('method', $owner, $name), %mt{$name});
    }
}
