#!/usr/bin/env python3
"""Generate (or check) src/vm/vm_exec_route.rs, the opcode -> group router.

`exec_one_dispatch`'s opcode `match` is split into `exec_ops_group_NN`
functions in src/vm/vm_exec_dispatch.rs (a debug build gives every local of
every arm its own native stack slot, so one 7k-line match cost ~140 KB of stack
per executed opcode; see #12299). The router names each `OpCode` variant once
and sends it to the group that holds its arm.

    scripts/gen-exec-route.py            rewrite the router
    scripts/gen-exec-route.py --check    fail when it is stale, when an opcode has
                                         no arm, or when two groups both claim one

When adding an opcode: write its arm (with its `// Cost:` line) in any group,
then run this script.
"""
import re
import subprocess
import sys

DISPATCH = "src/vm/vm_exec_dispatch.rs"
OPCODE = "src/opcode.rs"
ROUTE = "src/vm/vm_exec_route.rs"
EDITION = "2024"

HEADER = """//! Routes an opcode to the `exec_ops_group_NN` slice of `exec_one_dispatch` that runs it.
//!
//! Generated by `scripts/gen-exec-route.py` from the group functions in
//! `vm_exec_dispatch.rs`; `make check-exec-route` fails when this file is stale.

use super::*;

impl Interpreter {
    // Cost: O(1), a jump on the opcode discriminant.
    #[inline(always)]
    pub(super) fn route_op(
        &mut self,
        code: &CompiledCode,
        ip: &mut usize,
        compiled_fns: &CompiledFns,
    ) -> Result<(), RuntimeError> {
        match &code.ops[*ip] {
"""


def opcode_shapes():
    lines = open(OPCODE).read().split("\n")
    start = next(i for i, l in enumerate(lines) if l.startswith("pub(crate) enum OpCode {"))
    shapes = {}
    for line in lines[start + 1:]:
        if line.startswith("}"):
            break
        m = re.match(r"^    ([A-Z]\w*)\s*(\(|\{|,)", line)
        if m:
            shapes[m.group(1)] = {"(": "(..)", "{": " { .. }", ",": ""}[m.group(2)]
    return shapes


def group_variants():
    lines = open(DISPATCH).read().split("\n")
    groups: dict[str, list[str]] = {}
    current = None
    arm = re.compile(r"^            (OpCode::|[A-Za-z_])")
    for i, line in enumerate(lines):
        m = re.match(r"^    pub\(super\) fn (exec_ops_group_\d+)\(", line)
        if m:
            current = m.group(1)
            groups[current] = []
            continue
        if current is None:
            continue
        if line == "    }":
            current = None
            continue
        if arm.match(line) and not line.lstrip().startswith("//"):
            j = i
            head = []
            while True:
                head.append(lines[j])
                if "=>" in lines[j]:
                    break
                j += 1
            pat = " ".join(x.strip() for x in head).split("=>")[0].split(" if ")[0]
            groups[current] += re.findall(r"OpCode::(\w+)", pat)
    return groups


def main() -> int:
    shapes = opcode_shapes()
    groups = group_variants()
    owner: dict[str, str] = {}
    problems = []
    for g, vs in groups.items():
        for v in vs:
            if v in owner and owner[v] != g:
                problems.append(f"{v} has arms in both {owner[v]} and {g}")
            owner[v] = g
    for v in shapes:
        if v not in owner:
            problems.append(f"OpCode::{v} has no exec_ops_group arm")
    for v in owner:
        if v not in shapes:
            problems.append(f"arm for unknown OpCode::{v}")
    if problems:
        print("gen-exec-route:", *problems, sep="\n  ", file=sys.stderr)
        return 1
    out = HEADER
    for g, vs in groups.items():
        names = sorted(set(vs))
        pats = " | ".join(f"OpCode::{v}{shapes[v]}" for v in names)
        out += f"            {pats} => self.{g}(code, ip, compiled_fns),\n"
    out += "        }\n    }\n}\n"
    # Same layout `cargo fmt` gives the file, so the committed copy compares equal.
    out = subprocess.run(
        ["rustfmt", "--edition", EDITION, "--emit", "stdout"],
        input=out, capture_output=True, text=True, check=True,
    ).stdout
    if "--check" in sys.argv[1:]:
        try:
            cur = open(ROUTE).read()
        except FileNotFoundError:
            cur = ""
        if cur != out:
            print(f"gen-exec-route: {ROUTE} is stale; run scripts/gen-exec-route.py", file=sys.stderr)
            return 1
        print(f"exec route OK ({len(shapes)} opcodes in {len(groups)} groups)")
        return 0
    open(ROUTE, "w").write(out)
    print(f"wrote {ROUTE} ({len(shapes)} opcodes in {len(groups)} groups)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
