#!/usr/bin/env raku
# Prints the value (non-type) names the CORE setting declares, one per line as
# `<node>\t<name>`, sorted by name.
#
# RakuAST resolves a bareword against the setting at parse time: an enum value
# (`Less`, `Kept`) renders as `Term::Enum`, any other defined symbol
# (`IterationEnd`, `Order::Less`) as `Term::Name`. The node column is what
# rakudo's own `.AST` answers for the bare name, so the file records the
# measurement rather than a rule. src/rakuast/core_term_names.txt is this
# script's output; regenerate it with
#
#   raku scripts/gen-core-term-names.raku > src/rakuast/core_term_names.txt
#
# The companion list of type names is scripts/gen-core-type-names.raku.

sub walk(Str $prefix, $stash, %seen) {
    for $stash.keys -> $k {
        next if $k ~~ /^ <[&$@%!]> /;
        next if $k.starts-with('EXPORT') || $k eq 'GLOBAL' || $k.contains('<');
        my $name = $prefix ?? "$prefix\::$k" !! $k;
        next if %seen{$name}++;
        my $v := $stash{$k};
        if $v.DEFINITE {
            take $name;
        }
        else {
            my $who := $v.WHO;
            walk($name, $who, %seen) if $who ~~ Stash && $who.keys;
        }
    }
}

my %seen;
my @names = gather walk('', CORE::, %seen);
say "# CORE term names, generated by scripts/gen-core-term-names.raku on rakudo {$*RAKU.compiler.version}";
for @names.sort -> $name {
    # Only a name that parses as one plain identifier term is a bareword.
    next unless $name ~~ /^ [<.ident> ['-' <.ident>]*]+ % '::' $/;
    my $node = try $name.AST.statements.head.expression;
    next without $node;
    my $class = $node.^name;
    next unless $class eq 'RakuAST::Term::Enum' | 'RakuAST::Term::Name';
    say "{$class.subst('RakuAST::', '')}\t$name";
}
