#!/usr/bin/env raku
# Prints Rakudo's per-class method tables for every built-in owner the native
# method row catalog (src/builtins/native_method_row_table.rs) names.
#
# Two lists per owner, tab-separated, one line each:
#
#   declared<TAB>Owner<TAB>name<TAB>name...   keys of ::(Owner).^method_table
#                                             (what `.^can` walks per MRO level)
#   methods<TAB>Owner<TAB>name<TAB>name...    names of ::(Owner).^methods
#                                             (what `.^methods` reports)
#   only<TAB>Owner<TAB>name<TAB>name...       the `declared` names whose method
#                                             is an `only` method, not a multi
#                                             dispatcher (what an `augment`
#                                             may not redeclare, #10234)
#
# A `#[test]` in src/builtins/native_method_row.rs reads this snapshot as the
# oracle for the row catalog's DECLARED / INTROSPECTABLE / ONLY_METHOD flags
# (#11271, #10234). Owners
# that are not classes in Rakudo (roles such as Blob, RakuAST model nodes that
# mutsu models separately) are skipped. Regenerate with
#
#   raku scripts/gen-rakudo-method-tables.raku > src/builtins/rakudo_method_tables.txt
#
# whenever the row catalog gains an owner or the vendored Rakudo moves.

my $table-file = $*PROGRAM.parent.parent.add('src/builtins/native_method_row_table.rs');
my @owners = $table-file.lines
    .map({ ~$0 if / ^ \s* '("' (<-["]>+) '",' / })
    .grep(*.defined)
    .grep(!*.starts-with('RakuAST::'))
    .unique
    .sort;

sub clean(@names) { @names.grep({ .defined && $_ ne '' && !/\s/ }).unique.sort }

say "# Rakudo method tables, generated by scripts/gen-rakudo-method-tables.raku on rakudo {$*RAKU.compiler.version}";
for @owners -> $owner {
    my $type := try ::($owner);
    # The `Metamodel::*HOW` classes are NQP classes: their own HOW is an
    # `NQPClassHOW`, which has no `.defined`, so they are taken as they are.
    unless $owner.starts-with('Metamodel::') {
        next without $type.HOW;
        next unless $type.HOW ~~ Metamodel::ClassHOW | Metamodel::EnumHOW;
    }
    my @declared = try { clean($type.^method_table.keys) } // next;
    my @methods = try { clean($type.^methods.map(*.name)) } // next;
    my @only = try {
        clean($type.^method_table.pairs.grep({ !.value.?is_dispatcher }).map(*.key))
    } // next;
    say join "\t", 'declared', $owner, |@declared;
    say join "\t", 'methods', $owner, |@methods;
    say join "\t", 'only', $owner, |@only;
}
