#!/usr/bin/env raku
# Prints the type names the CORE setting declares, one per line, sorted.
#
# RakuAST resolves a bareword against the setting at parse time: a name that
# is a type object there renders as `Type::Simple` (`X::AdHoc`, `IO::Path`).
# src/rakuast/core_type_names.txt is this script's output; regenerate it with
#
#   raku scripts/gen-core-type-names.raku > src/rakuast/core_type_names.txt
#
# and record the rakudo version in the file's header line.

sub walk(Str $prefix, $stash, %seen) {
    for $stash.keys -> $k {
        next if $k ~~ /^ <[&$@%!]> /;
        next if $k.starts-with('EXPORT') || $k eq 'GLOBAL' || $k.contains('<');
        my $name = $prefix ?? "$prefix\::$k" !! $k;
        next if %seen{$name}++;
        my $v := $stash{$k};
        next if $v.DEFINITE;
        take $name;
        my $who := $v.WHO;
        walk($name, $who, %seen) if $who ~~ Stash && $who.keys;
    }
}

my %seen;
my @names = gather walk('', CORE::, %seen);
say "# CORE type names, generated by scripts/gen-core-type-names.raku on rakudo {$*RAKU.compiler.version}";
.say for @names.sort;
