use super::*;

/// Wrap a left-exclusive sequence (`^...` / `^...^`) result in `.skip(1)`: the
/// series is generated by the plain end-inclusive/exclusive sequence op and the
/// leading `^` just drops the first element (`5 ^... 0` == `(5 ... 0).skip(1)`),
/// which stays lazy for an infinite series.
fn wrap_left_exclusive_sequence(op_str: &str, expr: Expr) -> Expr {
    if op_str.starts_with('^') {
        Expr::MethodCall {
            target: Box::new(expr),
            name: crate::symbol::Symbol::intern("skip"),
            args: vec![Expr::Literal(crate::value::Value::int(1))],
            modifier: None,
            quoted: false,
        }
    } else {
        expr
    }
}

/// The source spelling of a binary operator token that a user can also
/// declare as `sub infix:<op>`. Only these can receive trailing adverbs.
fn binary_token_op_str(op: &crate::token_kind::TokenKind) -> Option<&'static str> {
    use crate::token_kind::TokenKind;
    Some(match op {
        TokenKind::Plus => "+",
        TokenKind::Minus => "-",
        TokenKind::Star => "*",
        TokenKind::Slash => "/",
        TokenKind::Percent => "%",
        TokenKind::StarStar => "**",
        TokenKind::Tilde => "~",
        _ => return None,
    })
}

/// A trailing colonpair adverb after a full expression binds to the
/// expression's *outermost* operator application (Raku: the adverb applies to
/// the preceding topmost operator — `1 + 2 - 3 :adv` adverbs `-`, and the
/// right-associative `1 ** 2 ** 3 :adv` adverbs the leftmost/outermost `**`).
/// Only user-defined operators can accept named arguments, so attachment is
/// limited to a `Binary` whose token op has a user `infix:<op>` declaration in
/// scope (rewritten to `InfixFunc`) and to an existing `InfixFunc`; anything
/// else leaves the colonpair unconsumed.
pub(super) fn attach_trailing_adverbs<'a>(
    input: &'a str,
    left: &mut Expr,
) -> Result<&'a str, PError> {
    let mut rest = input;
    loop {
        let (r_ws, _) = ws(rest)?;
        let ws_between = &rest[..rest.len() - r_ws.len()];
        if ws_between.is_empty()
            || ws_between.contains('\n')
            || !r_ws.starts_with(':')
            || r_ws.starts_with("::")
        {
            break;
        }
        let attachable = match &*left {
            Expr::Binary { op, .. } => binary_token_op_str(op)
                .is_some_and(crate::parser::stmt::simple::is_user_defined_infix),
            Expr::InfixFunc { .. } => true,
            _ => false,
        };
        if !attachable {
            break;
        }
        let Ok((r_next, adverb)) = crate::parser::primary::colonpair_expr(r_ws) else {
            break;
        };
        match left {
            Expr::Binary { .. } => {
                let Expr::Binary {
                    left: bl,
                    op,
                    right,
                } = std::mem::replace(left, Expr::Literal(crate::value::Value::NIL))
                else {
                    unreachable!()
                };
                let name = binary_token_op_str(&op).expect("checked above").to_string();
                *left = Expr::InfixFunc {
                    name,
                    left: bl,
                    right: vec![*right, adverb],
                    modifier: None,
                };
            }
            Expr::InfixFunc { right, .. } => right.push(adverb),
            _ => unreachable!(),
        }
        rest = r_next;
    }
    Ok(rest)
}

/// List-infix operators only: Z, X, meta-ops, infix funcs.
/// Used in NoSequence mode (e.g. inside parenthesized expressions).
pub(crate) fn list_infix_expr(input: &str) -> PResult<'_, Expr> {
    let (mut rest, mut left) = range_expr(input)?;
    let mut current_assoc_key = None;
    rest = parse_list_infix_loop(rest, input, &mut left, &mut current_assoc_key)?;
    rest = attach_trailing_adverbs(rest, &mut left)?;
    Ok((rest, left))
}

/// Sequence (`...`, `...^`) ONLY — no list-infix (Z/X/meta/infix-func) loop.
/// Used for an unparenthesized call / list-prefix argument, where a single
/// argument may be a sequence (`none 2 ... 5` = `none(2 ... 5)`) but must NOT
/// run the list-infix loop, which would misparse a trailing feed operator
/// (`grep {...} ==> @b`) as part of the argument.
pub(crate) fn sequence_only_expr(input: &str) -> PResult<'_, Expr> {
    let (mut rest, mut left) = range_expr(input)?;
    let mut current_assoc_key: Option<String> = None;
    loop {
        let (r, _) = ws(rest)?;
        if let Some((r2, op, op_str)) = strip_sequence_op(r) {
            if let Some(prev) = current_assoc_key.as_deref()
                && prev != op_str
            {
                return Err(non_list_associative_error(prev, op_str));
            }
            let (r2, _) = ws(r2)?;
            let (r2, mut right) =
                comparison_expr_mode(r2, ExprMode::NoSequence).map_err(|err| {
                    enrich_expected_error(
                        err,
                        format!("expected expression after '{op_str}'").as_str(),
                        r2.len(),
                    )
                })?;
            if contains_whatever(&right) && !matches!(right, Expr::Whatever) {
                right = wrap_whatevercode(&right);
            }
            if contains_whatever(&left) && !matches!(left, Expr::Whatever) {
                left = wrap_whatevercode(&left);
            }
            left = wrap_left_exclusive_sequence(
                op_str,
                Expr::Binary {
                    left: Box::new(left),
                    op,
                    right: Box::new(right),
                },
            );
            current_assoc_key = Some(op_str.to_string());
            rest = r2;
            continue;
        }
        break;
    }
    Ok((rest, left))
}

/// Sequence (..., ...^) and list-infix (Z, X, meta-ops, infix funcs).
/// All have Raku precedence level f= (list associative).
pub(crate) fn sequence_expr(input: &str) -> PResult<'_, Expr> {
    let (mut rest, mut left) = range_expr(input)?;
    let mut current_assoc_key: Option<String> = None;

    // Helper: wrap LHS WhateverCode before building the sequence node.
    fn maybe_wrap_lhs(left: &mut Expr) {
        if contains_whatever(left) && !matches!(left, Expr::Whatever) {
            *left = wrap_whatevercode(left);
        }
    }

    loop {
        let (r, _) = ws(rest)?;

        // ...^ / …^ (exclusive-end sequence), ... / … (sequence)
        if let Some((r2, op, op_str)) = strip_sequence_op(r) {
            if let Some(prev) = current_assoc_key.as_deref()
                && prev != op_str
            {
                return Err(non_list_associative_error(prev, op_str));
            }
            let (r2, _) = ws(r2)?;
            // The endpoint is parsed *below* the list-infix layer. `NoSequence` routes
            // through `list_infix_expr`, whose loop consumes a feed -- so `1, *+1 ... *
            // ==> elems()` bound the feed into the endpoint (`* ==> elems()`), and the
            // Whatever-curry below then turned that endpoint into a 1-ary WhateverCode.
            // The feed is the loosest operator in Raku and belongs to this function's own
            // list-infix loop below, outside the sequence.
            let (r2, mut right) = comparison_expr_mode(r2, ExprMode::ListopArg).map_err(|err| {
                enrich_expected_error(
                    err,
                    format!("expected expression after '{op_str}'").as_str(),
                    r2.len(),
                )
            })?;
            if contains_whatever(&right) && !matches!(right, Expr::Whatever) {
                right = wrap_whatevercode(&right);
            }
            maybe_wrap_lhs(&mut left);
            left = wrap_left_exclusive_sequence(
                op_str,
                Expr::Binary {
                    left: Box::new(left),
                    op,
                    right: Box::new(right),
                },
            );
            current_assoc_key = Some(op_str.to_string());
            rest = r2;
            continue;
        }
        // Try Z/X/meta/infix-func operators
        let new_rest = parse_list_infix_loop(rest, input, &mut left, &mut current_assoc_key)?;
        if new_rest.len() < rest.len() {
            rest = new_rest;
            continue;
        }
        break;
    }
    rest = attach_trailing_adverbs(rest, &mut left)?;
    Ok((rest, left))
}
